### ISSUE TITLE
bug: 'hide-create-button' patch fails

### ISSUE THREAD

**Issue by CruxH** [inotia00/ReVanced_Extended#103]
### Type

Error while patching

### Application

YouTube v18.01.32 (beta)

### Bug description

'hide-create-button' patch fails.

### Steps to reproduce

Include 'hide-create-button' and patch.

### Relevant log output

```shell
app.revanced.patcher.patch.PatchResultError: 'hide-create-button' depends on 'hide-create-button-bytecode-patch' but the following error was raised: PivotBarCreateButtonViewFingerprint failed at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:402) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:446) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

### Device Environment

- Patches v2.152.3
- revanced-integrations v0.91.2
- revanced-builder v3.8.0 (reisxd) on Windows

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.152.4
