### ISSUE TITLE
bug: Failed to resolve SubtitleTrackFingerprint

### ISSUE THREAD

**Issue by Zoey2936** [inotia00/ReVanced_Extended#1044]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube Music v6.08.50

### Bug description

I just patched youtube music and the error occured

### Steps to reproduce

1. Run `java -jar revanced-cli-2.21.6-all.jar -a yt-m.apk -b revanced-patches-2.181.1.jar -m revanced-integrations-0.111.2.apk -o yt-m-p.apk --keystore=revanced.keystore -i custom-branding-music-afn-blue -i custom-branding-music-name -e custom-branding-icon-revancify-blue`

### Relevant log output

```shell
disable-auto-captions failed:
app.revanced.patcher.patch.PatchResultError: Failed to resolve SubtitleTrackFingerprint
        at app.revanced.extensions.ExtensionsKt.toErrorResult(Extensions.kt:34)
        at app.revanced.patches.music.layout.autocaptions.patch.DisableAutoCaptionsPatch.execute(DisableAutoCaptionsPatch.kt:45)
        at app.revanced.patches.music.layout.autocaptions.patch.DisableAutoCaptionsPatch.execute(DisableAutoCaptionsPatch.kt:22)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:333)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.181.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.181.4)
