### ISSUE TITLE
YouTube music failing to patch in revanced manager

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1088]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube music 6.08.50

### Bug description

Gives an error while patching YouTube music app in the forked revanced manager app by inotia00

### Steps to reproduce

1. Get revanced manager app from inotia00 from https://github.com/inotia00/revanced-manager/releases/tag/v1.3.8
2. Select YouTube music apk file from apkmirror.com (v6.08.50)
3. Select all patches except custom branding icon revancify red and custom branding icon revancify blue
4. Start patching

### Relevant log output

```shell
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~vftBhVr8FB5Ko7v2pmvUog==/app.rvx.manager.flutter-1xuKshZ3rbnnTWhczqQ0jg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-QIGZBB/cache/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-QIGZBB/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:365)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~vftBhVr8FB5Ko7v2pmvUog==/app.rvx.manager.flutter-1xuKshZ3rbnnTWhczqQ0jg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-QIGZBB/cache/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-QIGZBB/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:361)
	... 6 more
```

### Screenshots or videos

![Screenshot_2023-07-07-17-56-53-103_app rvx manager flutter-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/b07d4226-19aa-4b3a-9bd8-141b3acca51c)

### Solution

Don't know the issue or solution to it but hope inotia00 can fix it.

### Additional context

I'm using Xiaomi 11T pro phone with official latest stock Android MIUI skin if that helps.

### Device Environment

Android 13 MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
exclude `custom-branding-name` patch
