### ISSUE TITLE
bug: RVX Manager/Revancify patching problem(with solution)

### ISSUE THREAD

**Issue by Stale-1** [inotia00/ReVanced_Extended#1102]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

Youtube v18.25.39
RVX Manager v1.3.8

### Bug description

There is an error in patching because of the Dependencies as well as the changes in the patch v2.181.1
![IMG_20230709_011211](https://github.com/inotia00/ReVanced_Extended/assets/74855954/a7288682-fd4e-498f-915d-7af5ff09abc1)
Because of this patches that depends on LithoPatchFilter would fail while patching. 

Aside from that, MicroG and SponsorBlock also would fail to patch if selected alone. It needs to be paired up with the list below. 

MicroG Support (need player-type-hook)
* disable-auto-captions
* enable-minimized-playback

SponsorBlock (need video-id-hook and player-type-hook)
* overlay-buttons which requires:
* spoof-app-version
* return-youtube-dislike
* remember-video-quality

LithoFilterPatch requires the following:
player-type-hook consists of:
* MicroG Support (optional) 
* disable-auto-captions
* enable-minimized-playback

video-id-hook consists of:
* SponsorBlock
* overlay-buttons which requires:
* spoof-app-version
* return-youtube-dislike
* remember-video-quality

### Steps to reproduce

1) Patch Youtube and select only MicroG. It will fail because it lacks "disable-auto-captions" and "enable-minimized-playback" 

2) Patch Youtube and Select only SponsorBlock. It would fail because it lacks "disable-auto-captions", "enable-minimized-playback", 
"overlay-buttons", "spoof-app-version", "return-youtube-dislike" and "remember-video-quality" 

3) Patch Youtube and select hide-general-ads and/or other patch that depends on LithoPatchFilter and it wouldn't work unless player-type-hook, video-id-hook and all LithoPatchFilter patches were selected. 

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping add-splash-animation: Excluded by default 
INFO: Skipping bypass-ambient-mode-restrictions: Excluded by default 
INFO: Skipping change-homepage: Excluded by default 
INFO: Skipping custom-branding-icon-mmt: Excluded by default 
INFO: Skipping custom-branding-icon-revancify-blue: Excluded by default 
INFO: Skipping custom-branding-icon-revancify-red: Excluded by default 
INFO: Skipping custom-branding-youtube-name: Excluded by default 
INFO: Skipping custom-double-tap-length: Excluded by default 
INFO: Skipping custom-seekbar-color: Excluded by default 
INFO: Skipping default-video-speed: Excluded by default 
INFO: Skipping disable-auto-captions: Excluded by default 
INFO: Skipping disable-haptic-feedback: Excluded by default 
INFO: Skipping disable-hdr-video: Excluded by default 
INFO: Skipping disable-landscape-mode: Excluded by default 
INFO: Skipping enable-debug-logging: Excluded by default 
INFO: Skipping enable-external-browser: Excluded by default 
INFO: Skipping enable-old-quality-layout: Excluded by default 
INFO: Skipping enable-open-links-directly: Excluded by default 
INFO: Skipping enable-seekbar-tapping: Excluded by default 
INFO: Skipping enable-tablet-mini-player: Excluded by default 
INFO: Skipping enable-tablet-navigation-bar: Excluded by default 
INFO: Skipping enable-timestamps-speed: Excluded by default 
INFO: Skipping enable-wide-search-bar: Excluded by default 
INFO: Skipping force-hide-player-button-background: Excluded by default 
INFO: Skipping header-switch: Excluded by default 
INFO: Skipping hide-account-menu: Excluded by default 
INFO: Skipping hide-auto-player-popup-panels: Excluded by default 
INFO: Skipping hide-autoplay-button: Excluded by default 
INFO: Skipping hide-autoplay-preview: Excluded by default 
INFO: Skipping hide-button-container: Excluded by default 
INFO: Skipping hide-captions-button: Excluded by default 
INFO: Skipping hide-cast-button: Excluded by default 
INFO: Skipping hide-category-bar: Excluded by default 
INFO: Skipping hide-channel-avatar-section: Excluded by default 
INFO: Skipping hide-channel-watermark: Excluded by default 
INFO: Skipping hide-collapse-button: Excluded by default 
INFO: Skipping hide-comment-component: Excluded by default 
INFO: Skipping hide-crowdfunding-box: Excluded by default 
INFO: Skipping hide-description-components: Excluded by default 
INFO: Skipping hide-double-tap-overlay-filter: Excluded by default 
INFO: Skipping hide-email-address: Excluded by default 
INFO: Skipping hide-endscreen-cards: Excluded by default 
INFO: Skipping hide-endscreen-overlay: Excluded by default 
INFO: Skipping hide-feed-flyout-panel: Excluded by default 
INFO: Skipping hide-filmstrip-overlay: Excluded by default 
INFO: Skipping hide-floating-microphone: Excluded by default 
INFO: Skipping hide-fullscreen-panels: Excluded by default 
INFO: Skipping hide-info-cards: Excluded by default 
INFO: Skipping hide-layout-components: Excluded by default 
INFO: Skipping hide-live-chat-button: Excluded by default 
INFO: Skipping hide-load-more-button: Excluded by default 
INFO: Skipping hide-mix-playlists: Excluded by default 
INFO: Skipping hide-music-button: Excluded by default 
INFO: Skipping hide-navigation-buttons: Excluded by default 
INFO: Skipping hide-navigation-label: Excluded by default 
INFO: Skipping hide-pip-notification: Excluded by default 
INFO: Skipping hide-player-button-background: Excluded by default 
INFO: Skipping hide-player-flyout-panel: Excluded by default 
INFO: Skipping hide-player-overlay-filter: Excluded by default 
INFO: Skipping hide-previous-next-button: Excluded by default 
INFO: Skipping hide-quick-actions: Excluded by default 
INFO: Skipping hide-seek-message: Excluded by default 
INFO: Skipping hide-seekbar: Excluded by default 
INFO: Skipping hide-snack-bar: Excluded by default 
INFO: Skipping hide-speed-overlay: Excluded by default 
INFO: Skipping hide-suggested-actions: Excluded by default 
INFO: Skipping hide-suggestions-shelf: Excluded by default 
INFO: Skipping hide-time-stamp: Excluded by default 
INFO: Skipping hide-tooltip-content: Excluded by default 
INFO: Skipping hide-trending-searches: Excluded by default 
INFO: Skipping language-switch: Excluded by default 
INFO: Skipping layout-switch: Excluded by default 
INFO: Skipping materialyou: Excluded by default 
INFO: Skipping spoof-app-version: Excluded by default 
INFO: Skipping swipe-controls: Excluded by default 
INFO: Skipping theme: Excluded by default 
INFO: Skipping translations: Excluded by default 
INFO: Merging inotia00-integrations-v0.111.6.apk 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: custom-package-name succeeded 
SEVERE: custom-video-speed failed: 
app.revanced.patcher.patch.PatchResultError: 'custom-video-speed' depends on 'enable-old-speed-layout' but the following error was raised: 'enable-old-speed-layout' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'player-type-hook' but the following error was raised: Failed to resolve YouTubeControlsOverlayFingerprint
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:312)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: default-video-quality succeeded 
INFO: disable-quic-protocol succeeded 
INFO: disable-startup-shorts-player succeeded 
INFO: enable-compact-controls-overlay succeeded 
SEVERE: enable-minimized-playback failed: 
app.revanced.patcher.patch.PatchResultError: 'enable-minimized-playback' depends on 'player-type-hook' but the following error was raised: 'player-type-hook' did not succeed previously
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:312)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: enable-new-splash-animation succeeded 
INFO: enable-new-thumbnail-preview succeeded 
INFO: force-opus-codec succeeded 
INFO: force-premium-heading succeeded 
INFO: force-vp9-codec succeeded 
SEVERE: hide-general-ads failed: 
app.revanced.patcher.patch.PatchResultError: 'hide-general-ads' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'player-type-hook' but the following error was raised: 'player-type-hook' did not succeed previously
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:312)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: hide-shorts-component failed: 
app.revanced.patcher.patch.PatchResultError: 'hide-shorts-component' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'player-type-hook' but the following error was raised: 'player-type-hook' did not succeed previously
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:312)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: hide-video-ads succeeded 
SEVERE: microg-support failed: 
app.revanced.patcher.patch.PatchResultError: 'microg-support' depends on 'microg-support-bytecode-patch' but the following error was raised: 'microg-support-bytecode-patch' depends on 'spoof-player-parameters' but the following error was raised: 'spoof-player-parameters' depends on 'player-type-hook' but the following error was raised: 'player-type-hook' did not succeed previously
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:312)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: optimize-resource succeeded 
SEVERE: overlay-buttons failed: 
app.revanced.patcher.patch.PatchResultError: 'overlay-buttons' depends on 'video-id-hook' but the following error was raised: 'video-id-hook' depends on 'player-type-hook' but the following error was raised: 'player-type-hook' did not succeed previously
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:312)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: return-youtube-dislike failed: 
app.revanced.patcher.patch.PatchResultError: 'return-youtube-dislike' depends on 'video-id-hook' but the following error was raised: 'video-id-hook' depends on 'player-type-hook' but the following error was raised: 'player-type-hook' did not succeed previously
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:312)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: settings succeeded 
SEVERE: sponsorblock failed: 
app.revanced.patcher.patch.PatchResultError: 'sponsorblock' depends on 'sponsorblock-bytecode-patch' but the following error was raised: 'sponsorblock-bytecode-patch' depends on 'video-id-hook' but the following error was raised: 'video-id-hook' depends on 'player-type-hook' but the following error was raised: 'player-type-hook' did not succeed previously
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:312)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: Compiling resources 
INFO: Writing modified dex files 
INFO: Aligning base.apk to base-Revanced-Extended_aligned.apk 
INFO: Signing base-Revanced-Extended_aligned.apk to base-Revanced-Extended_signed.apk 
INFO: Found existing keystore: revancify.keystore 
INFO: Copying base-Revanced-Extended_signed.apk to base-Revanced-Extended.apk 
INFO: Cleaned up cache directory 
INFO: Finished 



Variant: nonRoot
Arch: arm64-v8a
App: YouTube v18.25.39
CLI: inotia00-cli-v2.21.6.jar
Patches: inotia00-patches-v2.181.6.jar
Integrations: inotia00-integrations-v0.111.6.apk
Patches argument: -i custom-package-name
-i custom-video-speed
-i default-video-quality
-i disable-quic-protocol
-i disable-startup-shorts-player
-i enable-compact-controls-overlay
-i enable-minimized-playback
-i enable-new-splash-animation
-i enable-new-thumbnail-preview
-i force-opus-codec
-i force-premium-heading
-i force-vp9-codec
-i hide-general-ads
-i hide-shorts-component
-i hide-video-ads
-i microg-support
-i optimize-resource
-i overlay-buttons
-i return-youtube-dislike
-i settings
-i sponsorblock
```

### Solution

1) Include all LithoPatchFilter/LithoPatches even when not selected just like before.

2) Since LithoPatchFilter requires player-type-hook and video-id-hook.
a) Merge these patches into one patch as "Required Patches" 
* disable-auto-captions
* enable-minimized-playback
* SponsorBlock
* overlay-buttons
* spoof-app-version
* return-youtube-dislike
* remember-video-quality

b) Announce to everyone to always select the listed patches above to avoid errors. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.182.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.182.1)
