### ISSUE TITLE
bug: Patching with Termux Gives Error

### ISSUE THREAD

**Issue by anil-al** [inotia00/ReVanced_Extended#1226]
### Type

Error while patching

### Tools used

rvx-builder

### Application

YouTube Music, The last patch

### Bug description

I have upgraded the patch version, and tried to patch and had this error. What should I do? 

### Steps to reproduce

-

### Relevant log output

```shell
[builder] WARNING: aapt2 W 07-26 00:13:22 10483 10483] Unknown chunk type '200'.
[builder] brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 139): [/data/data/com.termux/files/home/rvx-builder/revanced/aapt2, link, -o, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL14677121043162303295.tmp, -0, arsc, -I, ./revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/build/resources.zip] at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:485) at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:620) at app.revanced.patcher.Patcher.save(Patcher.kt:132) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:21) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:173) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: brut.common.BrutException: could not exec (exit code = 139): [/data/data/com.termux/files/home/rvx-builder/revanced/aapt2, link, -o, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL14677121043162303295.tmp, -0, arsc, -I, ./revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/build/resources.zip] at brut.util.OS.exec(OS.java:99) at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:481) ... 13 more

Then it stucks here.
```

### Device Environment

Android 13, Samsung Tab S8+, Android Termux 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
it's outdated issue
just reinstall rvx-builder
