### ISSUE TITLE
Error Hide suggestions shelf patch

### ISSUE THREAD

**Issue by Karell2013** [inotia00/ReVanced_Extended#1393]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Youtube v18.36.39

### Bug description

Failed to patch in the version

### Steps to reproduce

Patch in rvx builder

### Relevant log output

```shell
[builder] GRAVE: Hide suggestions shelf failed: app.revanced.patcher.patch.PatchException: Failed to resolve SuggestionContentsBuilderFingerprint at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:35) at app.revanced.patches.youtube.general.suggestions.patch.SuggestionsShelfPatch.execute(SuggestionsShelfPatch.kt:72) at app.revanced.patches.youtube.general.suggestions.patch.SuggestionsShelfPatch.execute(SuggestionsShelfPatch.kt:23) at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147) at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61) at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230) at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
```

### Screenshots or videos

![image](https://github.com/inotia00/ReVanced_Extended/assets/100191384/adb0f2d5-7fb5-494e-b930-976d2e0e5619)

### Solution

How to add compatibility in the ultimate version for Youtube

### Additional context

Failed to patch in the version

### Device Environment

OneUI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
You are using an unsupported version
