### ISSUE TITLE
Patch error

### ISSUE THREAD

**Issue by arghya339** [inotia00/ReVanced_Extended#1395]
### Type

Error while patching

### Tools used

Revancify

### Application

YouTube_18.37.35

### Bug description

Patch_2.190.8 failed: ¹Custom playback speed, ²Enable old quality layout, ³Hide comment component failed, ⁴Hide general ads failed, ⁵Hide layout components, ⁶Hide shorts components, ⁷Hide suggested actions, ⁸Hide suggestions shelf.

### Steps to reproduce

I don't...

### Relevant log output

```shell
INFO: Loading patches 
INFO: Setting patch options 
INFO: Decoding app manifest 
INFO: Change homepage excluded by default 
INFO: Custom branding icon MMT excluded by default 
INFO: Custom branding icon Revancify blue excluded by default 
INFO: Custom branding icon Revancify red excluded by default 
INFO: Disable QUIC protocol excluded by default 
INFO: Disable hdr video excluded by default 
INFO: Disable landscape mode excluded by default 
INFO: Enable compact controls overlay excluded by default 
INFO: Enable tablet navigation bar excluded by default 
INFO: Force hide player button background excluded by default 
INFO: Force premium heading excluded by default 
INFO: Header switch excluded by default 
INFO: Hide autoplay button excluded by default 
INFO: Hide button container excluded by default 
INFO: Hide captions button excluded by default 
INFO: Hide cast button excluded by default 
INFO: Hide category bar excluded by default 
INFO: Hide channel avatar section excluded by default 
INFO: Hide description components excluded by default 
INFO: Hide end screen overlay excluded by default 
INFO: Hide feed flyout panel excluded by default 
INFO: Hide floating microphone excluded by default 
INFO: Hide fullscreen panels excluded by default 
INFO: Hide handle excluded by default 
INFO: Hide latest videos button excluded by default 
INFO: Hide load more button excluded by default 
INFO: Hide navigation buttons excluded by default 
INFO: Hide navigation label excluded by default 
INFO: Hide player flyout panel excluded by default 
INFO: Hide previous next button excluded by default 
INFO: Hide quick actions excluded by default 
INFO: Hide snack bar excluded by default 
INFO: Hide trending searches excluded by default 
INFO: Spoof app version excluded by default 
INFO: Merging integrations 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Add splash animation succeeded 
INFO: Append time stamps information succeeded 
INFO: Bypass ambient mode restrictions succeeded 
INFO: Custom branding YouTube name succeeded 
INFO: Custom double tap length succeeded 
INFO: Custom package name succeeded 
SEVERE: Custom playback speed failed: app.revanced.patcher.patch.PatchException: 'Custom playback speed' depends on 'OldSpeedLayoutPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'OldSpeedLayoutPatch' depends on 'LithoFilterPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' depends on 'ComponentParserPatch' that raised an exception: app.revanced.patcher.patch.PatchException: Failed to resolve IdentifierFingerprint
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:128)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Custom seekbar color succeeded 
INFO: Default playback speed succeeded 
INFO: Default video quality succeeded 
INFO: Disable Shorts on startup succeeded 
INFO: Disable auto captions succeeded 
INFO: Disable haptic feedback succeeded 
INFO: Disable pip notification succeeded 
INFO: Enable debug logging succeeded 
INFO: Enable external browser succeeded 
INFO: Enable minimized playback succeeded 
INFO: Enable new comment popup panels succeeded 
INFO: Enable new splash animation succeeded 
INFO: Enable new thumbnail preview succeeded 
SEVERE: Enable old quality layout failed: app.revanced.patcher.patch.PatchException: 'Enable old quality layout' depends on 'LithoFilterPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' depends on 'ComponentParserPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'ComponentParserPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:128)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Enable open links directly succeeded 
INFO: Enable seekbar tapping succeeded 
INFO: Enable tablet mini player succeeded 
INFO: Enable wide search bar succeeded 
INFO: Force OPUS codec succeeded 
INFO: Force VP9 codec succeeded 
INFO: Hide account menu succeeded 
INFO: Hide auto player popup panels succeeded 
INFO: Hide autoplay preview succeeded 
INFO: Hide channel watermark succeeded 
INFO: Hide collapse button succeeded 
SEVERE: Hide comment component failed: app.revanced.patcher.patch.PatchException: 'Hide comment component' depends on 'LithoFilterPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' depends on 'ComponentParserPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'ComponentParserPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:128)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Hide crowdfunding box succeeded 
INFO: Hide double tap overlay filter succeeded 
INFO: Hide end screen cards succeeded 
INFO: Hide filmstrip overlay succeeded 
SEVERE: Hide general ads failed: app.revanced.patcher.patch.PatchException: 'Hide general ads' depends on 'LithoFilterPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' depends on 'ComponentParserPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'ComponentParserPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:128)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Hide info cards succeeded 
SEVERE: Hide layout components failed: app.revanced.patcher.patch.PatchException: 'Hide layout components' depends on 'LithoFilterPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' depends on 'ComponentParserPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'ComponentParserPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:128)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Hide mix playlists succeeded 
INFO: Hide music button succeeded 
INFO: Hide player button background succeeded 
INFO: Hide player overlay filter succeeded 
INFO: Hide seek message succeeded 
INFO: Hide seekbar succeeded 
SEVERE: Hide shorts components failed: app.revanced.patcher.patch.PatchException: 'Hide shorts components' depends on 'LithoFilterPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' depends on 'ComponentParserPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'ComponentParserPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:128)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Hide speed overlay succeeded 
SEVERE: Hide suggested actions failed: app.revanced.patcher.patch.PatchException: 'Hide suggested actions' depends on 'LithoFilterPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' depends on 'ComponentParserPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'ComponentParserPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:128)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Hide suggested video overlay succeeded 
SEVERE: Hide suggestions shelf failed: app.revanced.patcher.patch.PatchException: 'Hide suggestions shelf' depends on 'LithoFilterPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' depends on 'ComponentParserPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'ComponentParserPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:128)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Hide time stamp succeeded 
INFO: Hide tooltip content succeeded 
INFO: Hide video ads succeeded 
INFO: Language switch succeeded 
INFO: Layout switch succeeded 
INFO: MaterialYou succeeded 
INFO: MicroG support succeeded 
INFO: Overlay buttons succeeded 
INFO: Return YouTube Dislike succeeded 
INFO: Settings succeeded 
INFO: SponsorBlock succeeded 
INFO: Spoof player parameters succeeded 
INFO: Swipe controls succeeded 
INFO: Theme succeeded 
INFO: Translations succeeded 
INFO: Compiling modified dex files 
INFO: Compiling modified resources 
INFO: Aligning base.apk 
INFO: Signing base-Revanced-Extended_aligned.apk 
INFO: Copying to base-Revanced-Extended.apk 
INFO: Purging temporary files 
INFO: Purged resource cache directory 
INFO: Finished
```

### Screenshots or videos

NA

### Solution

I don't.. I don't...

### Additional context

NA

### Device Environment

Android 13, MIUI 14.0.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
You are using an unsupported version
