### ISSUE TITLE
Patching Error

### ISSUE THREAD

**Issue by arghya339** [inotia00/ReVanced_Extended#1399]
### Type

Error while patching

### Tools used

Revancify

### Application

YouTube Music_6.20.51

### Bug description

Patch_2.190.8 failed: ¹Enable color match player ²Enable old style miniplayer ³Enable zen mode  ⁴Hide channel guidelines ⁵Hide music ads.

### Steps to reproduce

I don't...

### Relevant log output

```shell
INFO: Loading patches 
INFO: Setting patch options 
INFO: Decoding app manifest 
INFO: Custom branding icon MMT excluded by default 
INFO: Custom branding icon Revancify blue excluded by default 
INFO: Custom branding icon Revancify red excluded by default 
INFO: Enable custom filter excluded by default 
INFO: Enable force shuffle excluded by default 
INFO: Enable new layout excluded by default 
INFO: Enable old style library shelf excluded by default 
INFO: Hide action bar label excluded by default 
INFO: Hide button shelf excluded by default 
INFO: Hide carousel shelf excluded by default 
INFO: Hide category bar excluded by default 
INFO: Hide emoji picker excluded by default 
INFO: Hide flyout panel excluded by default 
INFO: Hide handle excluded by default 
INFO: Hide new playlist button excluded by default 
INFO: Hide playlist card excluded by default 
INFO: Hide radio button excluded by default 
INFO: Hide taste builder excluded by default 
INFO: Spoof app version excluded by default 
INFO: Merging integrations 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Amoled succeeded 
INFO: Background play succeeded 
INFO: Bitrate default value succeeded 
INFO: Certificate spoof succeeded 
INFO: Custom branding Music name succeeded 
INFO: Custom package name succeeded 
INFO: Custom playback speed succeeded 
INFO: Disable auto captions succeeded 
INFO: Enable black navigation bar succeeded 
SEVERE: Enable color match player failed: app.revanced.patcher.patch.PatchException: Failed to resolve ColorMatchPlayerParentFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:35)
	at app.revanced.patches.music.player.colormatchplayer.patch.ColorMatchPlayerPatch.execute(ColorMatchPlayerPatch.kt:74)
	at app.revanced.patches.music.player.colormatchplayer.patch.ColorMatchPlayerPatch.execute(ColorMatchPlayerPatch.kt:25)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Enable compact dialog succeeded 
INFO: Enable debug logging succeeded 
INFO: Enable force minimized player succeeded 
INFO: Enable landscape mode succeeded 
INFO: Enable minimized playback succeeded 
SEVERE: Enable old style miniplayer failed: app.revanced.patcher.patch.PatchException: Failed to resolve ColorMatchPlayerParentFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:35)
	at app.revanced.patches.music.player.oldstyleminiplayer.patch.OldStyleMiniPlayerPatch.execute(OldStyleMiniPlayerPatch.kt:55)
	at app.revanced.patches.music.player.oldstyleminiplayer.patch.OldStyleMiniPlayerPatch.execute(OldStyleMiniPlayerPatch.kt:22)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Enable opus codec succeeded 
INFO: Enable playback speed succeeded 
INFO: Enable sleep timer succeeded 
SEVERE: Enable zen mode failed: app.revanced.patcher.patch.PatchException: Failed to resolve ColorMatchPlayerParentFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:35)
	at app.revanced.patches.music.player.zenmode.patch.ZenModePatch.execute(ZenModePatch.kt:65)
	at app.revanced.patches.music.player.zenmode.patch.ZenModePatch.execute(ZenModePatch.kt:23)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Exclusive audio playback succeeded 
INFO: Hide account menu succeeded 
INFO: Hide cast button succeeded 
SEVERE: Hide channel guidelines failed: app.revanced.patcher.patch.PatchException: 'Hide channel guidelines' depends on 'LithoFilterPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' depends on 'ComponentParserPatch' that raised an exception: app.revanced.patcher.patch.PatchException: Failed to resolve IdentifierFingerprint
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:128)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Hide get premium succeeded 
SEVERE: Hide music ads failed: app.revanced.patcher.patch.PatchException: 'Hide music ads' depends on 'LithoFilterPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' depends on 'ComponentParserPatch' that raised an exception: app.revanced.patcher.patch.PatchException: 'ComponentParserPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:128)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
 
INFO: Hide navigation bar component succeeded 
INFO: Hide terms container succeeded 
INFO: Hide tooltip content succeeded 
INFO: Hook download button succeeded 
INFO: Import/Export settings succeeded 
INFO: MicroG support succeeded 
INFO: Remember playback speed succeeded 
INFO: Remember video quality succeeded 
INFO: Replace dismiss queue succeeded 
INFO: Return YouTube Dislike succeeded 
INFO: SponsorBlock succeeded 
INFO: Start page succeeded 
INFO: Translations succeeded 
INFO: Settings succeeded 
INFO: Compiling modified dex files 
INFO: Compiling modified resources 
INFO: Aligning base.apk 
INFO: Signing base-Revanced-Extended_aligned.apk 
INFO: Copying to base-Revanced-Extended.apk 
INFO: Purging temporary files 
INFO: Purged resource cache directory 
INFO: Finished
```

### Screenshots or videos

NA

### Solution

I don't.. I don't...

### Additional context

NA

### Device Environment

Android 13, MIUI 14.0.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
You are using an unsupported version
