### ISSUE TITLE
bug: Compile error

### ISSUE THREAD

**Issue by cuynu** [inotia00/ReVanced_Extended#140]
### Type

Error while patching

### Application

YouTube 17.49.37

### Bug description

This bug happening after change app name and package name on options.toml then patch again

### Steps to reproduce

Step 1. Change app name and package name on options.toml file and save it
Step 2. Patch YouTube with pre-selected patches in select all option

### Relevant log output

```shell
[builder] INFO: Reading dex files
[builder] INFO: Loading resource table...
[builder] INFO: Decoding AndroidManifest.xml only, because resources are not needed
[builder] INFO: Loading resource table from file: ./revanced-cache/1.apk
[builder] INFO: Merging /data/data/com.termux/files/home/rvx-builder/revanced/revanced-integrations-v0.92.5.apk
[builder] INFO: Skipping custom-branding-icon-afn-blue: Manually excluded
[builder] INFO: Skipping custom-branding-icon-revancify: Manually excluded
[builder] INFO: Skipping force-premium-heading: Manually excluded
[builder] INFO: Skipping materialyou: Manually excluded
[builder] INFO: Skipping optimize-resource: Manually excluded
[builder] INFO: Skipping patch-options: Manually excluded
[builder] INFO: Skipping theme: Manually excluded
[builder] INFO: Loading resource table...
[builder] INFO: Deleting existing resource cache directory
[builder] INFO: Decoding resources
[builder] INFO: Decoding AndroidManifest.xml with resources...
[builder] INFO: Loading resource table from file: ./revanced-cache/1.apk
[builder] INFO: Regular manifest package...
[builder] INFO: Decoding file-resources...
[builder] INFO: Decoding values */* XMLs...
[builder] INFO: client-spoof succeeded
[builder] INFO: custom-branding-icon-afn-red succeeded
[builder] INFO: custom-branding-name succeeded
[builder] INFO: custom-seekbar-color succeeded
[builder] INFO: custom-video-buffer succeeded
[builder] INFO: custom-video-speed succeeded
[builder] INFO: default-video-quality succeeded
[builder] INFO: default-video-speed succeeded
[builder] INFO: disable-haptic-feedback succeeded
[builder] INFO: enable-external-browser succeeded
[builder] INFO: enable-minimized-playback succeeded
[builder] INFO: enable-old-layout succeeded
[builder] INFO: enable-old-quality-layout succeeded
[builder] INFO: enable-open-links-directly succeeded
[builder] INFO: enable-seekbar-tapping succeeded
[builder] INFO: enable-tablet-miniplayer succeeded
[builder] INFO: enable-wide-searchbar succeeded
[builder] INFO: header-switch succeeded
[builder] INFO: hide-auto-captions succeeded
[builder] INFO: hide-auto-player-popup-panels succeeded
[builder] INFO: hide-autoplay-button succeeded
[builder] INFO: hide-button-container succeeded
[builder] INFO: hide-cast-button succeeded
[builder] INFO: hide-channel-watermark succeeded
[builder] INFO: hide-comment-component succeeded
[builder] INFO: hide-create-button succeeded
[builder] INFO: hide-crowdfunding-box succeeded
[builder] INFO: hide-email-address succeeded
[builder] INFO: hide-endscreen-cards succeeded
[builder] INFO: hide-endscreen-overlay succeeded
[builder] INFO: hide-filmstrip-overlay succeeded
[builder] INFO: hide-flyout-panel succeeded
[builder] INFO: hide-fullscreen-buttoncontainer succeeded
[builder] INFO: hide-general-ads succeeded
[builder] INFO: hide-info-cards succeeded
[builder] INFO: hide-mix-playlists succeeded
[builder] INFO: hide-pip-notification succeeded
[builder] INFO: hide-player-captions-button succeeded
[builder] INFO: hide-player-overlay-filter succeeded
[builder] INFO: hide-shorts-button succeeded
[builder] INFO: hide-shorts-component succeeded
[builder] INFO: hide-startup-shorts-player succeeded
[builder] INFO: hide-stories succeeded
[builder] INFO: hide-suggested-actions succeeded
[builder] INFO: hide-time-and-seekbar succeeded
[builder] INFO: hide-video-ads succeeded
[builder] INFO: layout-switch succeeded
[builder] INFO: microg-support succeeded
[builder] INFO: overlay-buttons succeeded
[builder] INFO: remove-player-button-background succeeded
[builder] INFO: return-youtube-dislike succeeded
[builder] INFO: settings succeeded
[builder] INFO: sponsorblock succeeded
[builder] INFO: swipe-controls succeeded
[builder] INFO: translations succeeded
[builder] INFO: Compiling resources
[builder] WARNING: aapt2 W 01-12 00:34:55 12834 12834] Unknown chunk type '200'.
[builder] brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/data/com.termux/files/home/rvx-builder/revanced/aapt2, link, -o, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1533275584, --version-name, 17.49.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL8067904744066946775.tmp, -0, arsc, -I, ./revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/build/resources.zip] at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487) at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:622) at app.revanced.patcher.Patcher.save(Patcher.kt:144) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:158) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/data/com.termux/files/home/rvx-builder/revanced/aapt2, link, -o, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1533275584, --version-name, 17.49.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL8067904744066946775.tmp, -0, arsc, -I, ./revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/rvx-builder/./revanced-cache/build/resources.zip] at brut.util.OS.exec(OS.java:99) at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:483) ... 13 more
```

### Device Environment

Xiaomi Redmi K20 Pro, Android 11, MIUI 12.5.6

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
include `patch-options`
