### ISSUE TITLE
bug(YouTube Music): 6.15.52 fails with these three patches included

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1414]
### Type

Error while patching

### Tools used

rvx-builder

### Application

YouTube Music 6.15.52

### Bug description

If you patch YTM 6.15.52 (it marked as supported):
Enable color match player failed
Enable old style miniplayer failed
Enable zen mode failed

### Steps to reproduce

Apply `enable-color-match-player`;`enable-old-style-miniplayer`;`enable-zen-mode`

### Relevant log output

```shell
[builder] INFO: Loading patches
[builder] INFO: Setting patch options
[builder] INFO: Decoding app manifest
[builder] INFO: Excluding Custom branding icon Revancify blue INFO: Excluding Custom branding icon Revancify red
[builder] INFO: Excluding Enable debug logging
[builder] INFO: Merging integrations
[builder] INFO: Deleting existing resource cache directory
[builder] INFO: Decoding resources
[builder] INFO: Executing patches
[builder] INFO: Amoled succeeded
[builder] INFO: Background play succeeded
[builder] INFO: Bitrate default value succeeded
[builder] INFO: Certificate spoof succeeded
[builder] INFO: Custom branding Music name succeeded
[builder] INFO: Custom branding icon MMT succeeded
[builder] INFO: Custom package name succeeded
[builder] INFO: Custom playback speed succeeded
[builder] INFO: Disable auto captions succeeded
[builder] INFO: Enable black navigation bar succeeded
[builder] SEVERE: Enable color match player failed: app.revanced.patcher.patch.PatchException: Failed to resolve PlayerColorFingerprint at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:35) at app.revanced.patches.music.player.colormatchplayer.patch.ColorMatchPlayerPatch.execute(ColorMatchPlayerPatch.kt:68) at app.revanced.patches.music.player.colormatchplayer.patch.ColorMatchPlayerPatch.execute(ColorMatchPlayerPatch.kt:25) at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147) at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61) at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230) at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
[builder] INFO: Enable compact dialog succeeded
[builder] INFO: Enable custom filter succeeded
[builder] INFO: Enable force minimized player succeeded
[builder] INFO: Enable landscape mode succeeded
[builder] INFO: Enable minimized playback succeeded
[builder] INFO: Enable new layout succeeded
[builder] INFO: Enable old style library shelf succeeded
[builder] SEVERE: Enable old style miniplayer failed: app.revanced.patcher.patch.PatchException: Failed to resolve PlayerColorFingerprint at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:35) at app.revanced.patches.music.player.oldstyleminiplayer.patch.OldStyleMiniPlayerPatch.execute(OldStyleMiniPlayerPatch.kt:55) at app.revanced.patches.music.player.oldstyleminiplayer.patch.OldStyleMiniPlayerPatch.execute(OldStyleMiniPlayerPatch.kt:22) at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147) at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61) at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230) at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
[builder] INFO: Enable opus codec succeeded
[builder] INFO: Enable playback speed succeeded
[builder] INFO: Enable sleep timer succeeded
[builder] SEVERE: Enable zen mode failed: app.revanced.patcher.patch.PatchException: Failed to resolve PlayerColorFingerprint at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:35) at app.revanced.patches.music.player.zenmode.patch.ZenModePatch.execute(ZenModePatch.kt:65) at app.revanced.patches.music.player.zenmode.patch.ZenModePatch.execute(ZenModePatch.kt:23) at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147) at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61) at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230) at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:198) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
[builder] INFO: Exclusive audio playback succeeded
[builder] INFO: Hide account menu succeeded
[builder] INFO: Hide action bar label succeeded
[builder] INFO: Hide button shelf succeeded
[builder] INFO: Hide carousel shelf succeeded
[builder] INFO: Hide cast button succeeded
[builder] INFO: Hide category bar succeeded
[builder] INFO: Hide channel guidelines succeeded
[builder] INFO: Hide emoji picker succeeded
[builder] INFO: Hide flyout panel succeeded
[builder] INFO: Hide get premium succeeded
[builder] INFO: Hide handle succeeded
[builder] INFO: Hide music ads succeeded
[builder] INFO: Hide navigation bar component succeeded
[builder] INFO: Hide new playlist button succeeded
[builder] INFO: Hide playlist card succeeded
[builder] INFO: Hide radio button succeeded
[builder] INFO: Hide taste builder succeeded
[builder] INFO: Hide terms container succeeded
[builder] INFO: Hide tooltip content succeeded
[builder] INFO: Hook download button succeeded
[builder] INFO: MicroG support succeeded
[builder] INFO: Remember playback speed succeeded
[builder] INFO: Remember repeat state succeeded
[builder] INFO: Remember shuffle state succeeded
[builder] INFO: Remember video quality succeeded
[builder] INFO: Replace dismiss queue succeeded
[builder] INFO: Return YouTube Dislike succeeded
[builder] INFO: SponsorBlock succeeded
[builder] INFO: Spoof app version succeeded
[builder] INFO: Start page succeeded
[builder] INFO: Translations succeeded
[builder] INFO: Settings succeeded
[builder] INFO: Compiling modified dex files
[builder] INFO: Compiling modified resources
[builder] INFO: Aligning com.google.android.apps.youtube.music.apk
[builder] INFO: Signing revanced_aligned.apk
[builder] INFO: Copying to revanced.apk
[builder] INFO: Purging temporary files
[builder] INFO: Purged resource cache directory INFO: Finished
[builder] Copied files over to /storage/emulated/0/! Please install ReVanced, its located in /storage/emulated/0/ReVanced-YouTubeMusic-cli_v3.1.2-patches_v2.190.12.apk and if you are building YT/YTM ReVanced without root, also install /storage/emulated/0/microg.apk.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.190.15](https://github.com/inotia00/revanced-patches/releases/tag/v2.190.15)
