### ISSUE TITLE
bug: <YouTube crash at start-up>

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1477]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.33.40
patches v2.190.21
Integrations v1.117.12

### Bug description

YouTube now crashes at start up after installing successfully patched apk.

### Steps to reproduce

Step 1. Use revancify/ReVanced manager
Step 2. Patch YouTube with latest patch and integration version.
Step 3. Install patched app and open.

### Relevant log output

```shell
java.lang.NoSuchMethodError: No static method hideBreakingNewsShelf(Landroid/view/View;)V in class Lapp/revanced/integrations/patches/layout/GeneralPatch; or its super classes (declaration of 'app.revanced.integrations.patches.layout.GeneralPatch' appears in /data/app/~~GFcqvX3QOlHuMWD8pddulQ==/app.rvx.android.youtube-eMYlA9JtcBKRb1OWCjDG6A==/base.apk!classes7.dex)
	at lad.<init>(PG:4)
	at mew.a(PG:1)
	at afle.e(PG:7)
	at afmv.B(PG:3)
	at ffz.g(PG:4)
	at ok.uO(PG:1)
	at ow.p(PG:79)
	at ow.b(PG:1)
	at nq.a(PG:7)
	at android.support.v7.widget.LinearLayoutManager.A(PG:1)
	at android.support.v7.widget.LinearLayoutManager.J(PG:7)
	at android.support.v7.widget.LinearLayoutManager.n(PG:98)
	at com.google.android.libraries.youtube.rendering.ui.ScrollToTopLinearLayoutManager.n(PG:1)
	at android.support.v7.widget.RecyclerView.aS(PG:9)
	at android.support.v7.widget.RecyclerView.F(PG:9)
	at android.support.v7.widget.RecyclerView.onLayout(PG:1)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(PG:9)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at aguo.uV(PG:19)
	at aguq.rA(PG:1)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.rA(PG:1)
	at com.google.android.apps.youtube.app.ui.actionbar.MainScrollingViewBehavior.rA(PG:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(PG:6)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchContainerLayout.g(PG:2)
	at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchContainerLayout.h(PG:7)
	at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchContainerLayout.onLayout(PG:4)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at com.google.android.apps.youtube.app.common.ui.navigationbar.NavigationBarDividerLayout.onLayout(PG:4)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.google.android.apps.youtube.app.ui.swipetocontainer.SwipeToContainerFrameLayout.onLayout(PG:1)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at bis.onLayout(PG:6)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:874)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4188)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3564)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2530)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9401)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:1003)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### Screenshots or videos

N/A

### Solution

Fix crash at start up issue.

### Additional context

Using Xiaomi 11T pro phone here and it has a built in log output app that gives a log whenever an app crashes or doesn't runs properly.
I got the logs from there.

### Device Environment

Android 13 MIUI14.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This is not a patch issue

The issue is on your side

For some reason the patches are not updated in your environment.

Clean install everything and try again

e.g.
If you are trying to patch from RVX Manager, please reinstall RVX Manager

If you are trying to patch from Revancify, remove the fetched tool, fetch it again, and then proceed with the patch.

**Comment by inotia00** [comment]
Update: Looks like an issue with Revancify

For some reason, if the `FetchPreReleasedTools` option is enabled, tools from the PR branch will be downloaded.

Turn off that option until Revancify resolves the issue.

**Comment by Rairof** [comment]
Alright thanks.
