### ISSUE TITLE
bug: patch list not shown in RVX Manager

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1602]
### Type

Other

### Tools used

ReVanced Manager

### Application

youtube 18.41.39

### Bug description

I found the latest version of rvx when I went into the app to update it Cannot select the desired patch

### Steps to reproduce

1. Update rvx Manager to the latest version
2. Select the latest version of YouTube that you support
3. Entering Patch Selection Screen

### Relevant log output

```shell
.
```

### Screenshots or videos

https://github.com/inotia00/ReVanced_Extended/assets/98168192/10391d24-3f39-47b6-a6d6-bb42ac660c10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by AniruddhaSadhukhan** [comment]
Facing same issue...

Also attaching some manager logs
```
10-28 12:29:51.905 29379 29379 D FileDialog: ...copied on background, result: /data/user/0/app.rvx.manager.flutter/cache/com.google.android.youtube_18.41.39-1540619712_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk
10-28 12:29:51.905 29379 29379 D FileDialog: ...launch
10-28 12:29:51.913 29379 29379 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.rvx.manager.flutter/cache/com.google.android.youtube_18.41.39-1540619712_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #42
10-28 12:29:51.914 29379 29379 W PackageParser: Unknown element under <application>: property at /data/user/0/app.rvx.manager.flutter/cache/com.google.android.youtube_18.41.39-1540619712_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #428
10-28 12:29:51.928 29379 29379 W IconCustomizer: can't load transform_config.xml
10-28 12:29:51.929 29379 29379 W IconCustomizer: getCustomizedIconW 168
10-28 12:29:51.938 29379  9410 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: Class 'String' has no instance method 'replace'.
10-28 12:29:51.938 29379  9410 E flutter : Receiver: "StringPatchOption"
10-28 12:29:51.938 29379  9410 E flutter : Tried calling: replace("PatchOption", "")
10-28 12:29:51.938 29379  9410 E flutter : #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
10-28 12:29:51.938 29379  9410 E flutter : #1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
10-28 12:29:51.938 29379  9410 E flutter : #2      Option._migrateV17ToV19 (package:revanced_manager/models/patch.dart:77)
10-28 12:29:51.938 29379  9410 E flutter : #3      new Option.fromJson (package:revanced_manager/models/patch.dart:69)
10-28 12:29:51.938 29379  9410 E flutter : #4      _$PatchFromJson.<anonymous closure> (package:revanced_manager/models/patch.g.dart:17)
10-28 12:29:51.938 29379  9410 E flutter : #5      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
10-28 12:29:51.938 29379  9410 E flutter : #6      ListIterator.moveNext (dart:_internal/iterable.dart:344)
10-28 12:29:51.938 29379  9410 E flutter : #7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
10-28 12:29:51.938 29379  9410 E flutter : #8      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
10-28 12:29:51.938 29379  9410 E flutter : #9      new List.of (dart:core-patch/array_patch.dart:47)
10-28 12:29:51.938 29379  9410 E flutter : #10     SetBase.toList (dart:collection/set.dart:119)
10-28 12:29:51.938 29379  9410 E flutter : #11     _$PatchFromJson (package:revanced_manager/models/patch.g.dart:18)
10-28 12:29:51.938 29379  9410 E flutter : #12     new Patch.fromJson (package:revanced_manager/models/patch.dart:18)
10-28 12:29:51.938 29379  9410 E flutter : #13     ManagerAPI.getUsedPatches.<anonymous closure> (package:revanced_manager/services/manager_api.dart:175)
10-28 12:29:51.938 29379  9410 E flutter : #14     MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
10-28 12:29:51.938 29379  9410 E flutter : #15     ListIterator.moveNext (dart:_internal/iterable.dart:344)
10-28 12:29:51.938 29379  9410 E flutter : #16     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
10-28 12:29:51.938 29379  9410 E flutter : #17     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
10-28 12:29:51.938 29379  9410 E flutter : #18     new List.of (dart:core-patch/array_patch.dart:47)
10-28 12:29:51.938 29379  9410 E flutter : #19     SetBase.toList (dart:collection/set.dart:119)
10-28 12:29:51.938 29379  9410 E flutter : #20     ManagerAPI.getUsedPatches (package:revanced_manager/services/manager_api.dart:176)
10-28 12:29:51.938 29379  9410 E flutter : #21     PatcherViewModel.loadLastSelectedPatches (package:revanced_manager/ui/views/patcher/patcher_viewmodel.dart:202)
10-28 12:29:51.938 29379  9410 E flutter : <asynchronous suspension>
10-28 12:29:51.938 29379  9410 E flutter : 
10-28 12:30:04.349 29379  9410 I flutter : NoSuchMethodError: Class 'String' has no instance method 'replace'.
10-28 12:30:04.349 29379  9410 I flutter : Receiver: "StringPatchOption"
10-28 12:30:04.349 29379  9410 I flutter : Tried calling: replace("PatchOption", "")
10-28 12:30:04.354 29379  9410 I flutter : #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
10-28 12:30:04.354 29379  9410 I flutter : #1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
10-28 12:30:04.354 29379  9410 I flutter : #2      Option._migrateV17ToV19 (package:revanced_manager/models/patch.dart:77)
10-28 12:30:04.354 29379  9410 I flutter : #3      new Option.fromJson (package:revanced_manager/models/patch.dart:69)
10-28 12:30:04.354 29379  9410 I flutter : #4      _$PatchFromJson.<anonymous closure> (package:revanced_manager/models/patch.g.dart:17)
10-28 12:30:04.354 29379  9410 I flutter : #5      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
10-28 12:30:04.354 29379  9410 I flutter : #6      ListIterator.moveNext (dart:_internal/iterable.dart:344)
10-28 12:30:04.354 29379  9410 I flutter : #7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
10-28 12:30:04.354 29379  9410 I flutter : #8      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
10-28 12:30:04.354 29379  9410 I flutter : #9      new List.of (dart:core-patch/array_patch.dart:47)
10-28 12:30:04.354 29379  9410 I flutter : #10     SetBase.toList (dart:collection/set.dart:119)
10-28 12:30:04.354 29379  9410 I flutter : #11     _$PatchFromJson (package:revanced_manager/models/patch.g.dart:18)
10-28 12:30:04.354 29379  9410 I flutter : #12     new Patch.fromJson (package:revanced_manager/models/patch.dart:18)
10-28 12:30:04.354 29379  9410 I flutter : #13     ManagerAPI.getSavedPatches.<anonymous closure> (package:revanced_manager/services/manager_api.dart:151)
10-28 12:30:04.354 29379  9410 I flutter : #14     MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
10-28 12:30:04.354 29379  9410 I flutter : #15     ListIterator.moveNext (dart:_internal/iterable.dart:344)
10-28 12:30:04.354 29379  9410 I flutter : #16     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
10-28 12:30:04.354 29379  9410 I flutter : #17     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
10-28 12:30:04.354 29379  9410 I flutter : #18     new List.of (dart:core-patch/array_patch.dart:47)
10-28 12:30:04.354 29379  9410 I flutter : #19     SetBase.toList (dart:collection/set.dart:119)
10-28 12:30:04.354 29379  9410 I flutter : #20     ManagerAPI.getSavedPatches (package:revanced_manager/services/manager_api.dart:152)
10-28 12:30:04.354 29379  9410 I flutter : #21     PatchesSelectorViewModel.isPatchNew (package:revanced_manager/ui/views/patches_selector/patches_selector_viewmodel.dart:282)
10-28 12:30:04.354 29379  9410 I flutter : #22     _PatchesSelectorViewState.build.<anonymous closure>.<anonymous closure> (package:revanced_manager/ui/views/patches_selector/patches_selector_view.dart:183)
10-28 12:30:04.354 29379  9410 I flutter : #23     ListBase.any (dart:collection/list.dart:114)
10-28 12:30:04.354 29379  9410 I flutter : #24     _PatchesSelectorViewState.build.<anonymous closure> (package:revanced_manager/ui/views/patches_selector/patches_selector_view.dart:183)
10-28 12:30:04.354 29379  9410 I flutter : #25     ViewModelBuilderState.builderWithDynamicSourceInitialise (package:stacked/src/view_models/view_model_builder.dart:213)
10-28 12:30:04.354 29379  9410 I flutter : #26     Consumer.buildWithChild (package:provider/src/consumer.dart:179)
10-28 12:30:04.354 29379  9410 I flutter : #27     SingleChildStatelessWidget.build (package:nested/nested.dart:259)
10-28 12:30:04.354 29379  9410 I flutter : #28     StatelessElement.build (package:flutter/src/widgets/framework.dart:5367)
10-28 12:30:04.354 29379  9410 I flutter : #29     SingleChildStatelessElement.build (package:nested/nested.dart:279)
10-28 12:30:04.354 29379  9410 I flutter : #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297)
10-28 12:30:04.354 29379  9410 I flutter : #31     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
10-28 12:30:04.354 29379  9410 I flutter : #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
10-28 12:30:04.354 29379  9410 I flutter : #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
10-28 12:30:04.354 29379  9410 I flutter : #34     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222)
10-28 12:30:04.354 29379  9410 I flutter : #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.354 29379  9410 I flutter : #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
10-28 12:30:04.354 29379  9410 I flutter : #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
10-28 12:30:04.354 29379  9410 I flutter : #38     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
10-28 12:30:04.355 29379  9410 I flutter : #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
10-28 12:30:04.355 29379  9410 I flutter : #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
10-28 12:30:04.355 29379  9410 I flutter : #41     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222)
10-28 12:30:04.355 29379  9410 I flutter : #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.355 29379  9410 I flutter : #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
10-28 12:30:04.355 29379  9410 I flutter : #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
10-28 12:30:04.355 29379  9410 I flutter : #45     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
10-28 12:30:04.355 29379  9410 I flutter : #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
10-28 12:30:04.355 29379  9410 I flutter : #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
10-28 12:30:04.355 29379  9410 I flutter : #48     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222)
10-28 12:30:04.355 29379  9410 I flutter : #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.355 29379  9410 I flutter : #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
10-28 12:30:04.355 29379  9410 I flutter : #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
10-28 12:30:04.355 29379  9410 I flutter : #52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
10-28 12:30:04.355 29379  9410 I flutter : #53     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
10-28 12:30:04.355 29379  9410 I flutter : #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
10-28 12:30:04.355 29379  9410 I flutter : #55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
10-28 12:30:04.355 29379  9410 I flutter : #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
10-28 12:30:04.355 29379  9410 I flutter : #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.355 29379  9410 I flutter : #58     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
10-28 12:30:04.355 29379  9410 I flutter : #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
10-28 12:30:04.355 29379  9410 I flutter : #60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
10-28 12:30:04.355 29379  9410 I flutter : #61     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
10-28 12:30:04.355 29379  9410 I flutter : #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
10-28 12:30:04.355 29379  9410 I flutter : #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
10-28 12:30:04.355 29379  9410 I flutter : #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
10-28 12:30:04.355 29379  9410 I flutter : #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.355 29379  9410 I flutter : #66     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
10-28 12:30:04.355 29379  9410 I flutter : #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6434)
10-28 12:30:04.355 29379  9410 I flutter : #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.355 29379  9410 I flutter : #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
10-28 12:30:04.355 29379  9410 I flutter : #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
10-28 12:30:04.355 29379  9410 I flutter : #71     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
10-28 12:30:04.355 29379  9410 I flutter : #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
10-28 12:30:04.355 29379  9410 I flutter : #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
10-28 12:30:04.355 29379  9410 I flutter : #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.355 29379  9410 I flutter : #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
10-28 12:30:04.355 29379  9410 I flutter : #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6434)
10-28 12:30:04.355 29379  9410 I flutter : #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.355 29379  9410 I flutter : #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
10-28 12:30:04.355 29379  9410 I flutter : #79     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6434)
10-28 12:30:04.355 29379  9410 I flutter : #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.355 29379  9410 I flutter : #81     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
10-28 12:30:04.355 29379  9410 I flutter : #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
10-28 12:30:04.355 29379  9410 I flutter : #83     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
10-28 12:30:04.355 29379  9410 I flutter : #84     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
10-28 12:30:04.355 29379  9410 I flutter : #85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
10-28 12:30:04.355 29379  9410 I flutter : #86     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
10-28 12:30:04.355 29379  9410 I flutter : #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
10-28 12:30:04.355 29379  9410 I flutter : #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.355 29379  9410 I flutter : #89     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
10-28 12:30:04.355 29379  9410 I flutter : #90     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6434)
10-28 12:30:04.355 29379  9410 I flutter : #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.355 29379  9410 I flutter : #92     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
10-28 12:30:04.355 29379  9410 I flutter : #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
10-28 12:30:04.355 29379  9410 I flutter : #94     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
10-28 12:30:04.355 29379  9410 I flutter : #95     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
10-28 12:30:04.355 29379  9410 I flutter : #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
10-28 12:30:04.355 29379  9410 I flutter : #97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
10-28 12:30:04.355 29379  9410 I flutter : #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
10-28 12:30:04.355 29379  9410 I flutter : #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
10-28 12:30:04.377 29379  9410 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
10-28 12:30:11.827 29379 29379 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10328; state: ENABLED
10-28 12:30:13.395 29379 29379 D DecorView[]: onWindowFocusChanged hasWindowFocus false
10-28 12:30:13.600 29379 29379 D DecorView[]: onWindowFocusChanged hasWindowFocus false
10-28 12:30:13.965 29379 29379 D FlutterFileDialogPlugin: onDetachedFromActivity
10-28 12:30:13.965 29379 29379 D FlutterFileDialogPlugin: doOnDetachedFromActivity - IN
10-28 12:30:13.965 29379 29379 D FlutterFileDialogPlugin: doOnDetachedFromActivity - OUT
10-28 12:30:16.978 29382 29382 I manager.flutter: Using CollectorTypeCC GC.
10-28 12:30:16.985 29382 29382 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
10-28 12:30:16.991 29382 29382 I MessageMonitor: Load libmiui_runtime
10-28 12:30:17.004 29382 29382 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10328; state: ENABLED
10-28 12:30:17.013 29382 29382 W System.err: org.w3c.dom.DOMException: Only one root element allowed
10-28 12:30:17.013 29382 29382 W System.err: 	at org.apache.harmony.xml.dom.DocumentImpl.insertChildAt(DocumentImpl.java:420)
10-28 12:30:17.013 29382 29382 W System.err: 	at org.apache.harmony.xml.dom.InnerNodeImpl.appendChild(InnerNodeImpl.java:52)
10-28 12:30:17.013 29382 29382 W System.err: 	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:307)
10-28 12:30:17.013 29382 29382 W System.err: 	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:128)
10-28 12:30:17.013 29382 29382 W System.err: 	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
10-28 12:30:17.013 29382 29382 W System.err: 	at miui.content.res.ThemeValues.parseThemeValues(ThemeValues.java:123)
10-28 12:30:17.013 29382 29382 W System.err: 	at miui.content.res.ThemeResources$LoadThemeConfigHelper.load(ThemeResources.java:486)
10-28 12:30:17.013 29382 29382 W System.err: 	at miui.content.res.ThemeZipFile.loadThemeConfigInner(ThemeZipFile.java:274)
10-28 12:30:17.013 29382 29382 W System.err: 	at miui.content.res.ThemeZipFile.loadThemeConfig(ThemeZipFile.java:256)
10-28 12:30:17.013 29382 29382 W System.err: 	at miui.content.res.ThemeResources$LoadThemeConfigHelper.newTarget(ThemeResources.java:479)
10-28 12:30:17.013 29382 29382 W System.err: 	at miui.content.res.ThemeResources.loadThemeValues(ThemeResources.java:498)
10-28 12:30:17.013 29382 29382 W System.err: 	at miui.content.res.ThemeResources.checkUpdate(ThemeResources.java:262)
10-28 12:30:17.013 29382 29382 W System.err: 	at miui.content.res.ThemeResourcesSystem.checkUpdate(ThemeResourcesSystem.java:102)
10-28 12:30:17.013 29382 29382 W System.err: 	at miui.content.res.ThemeResources.getSystem(ThemeResources.java:136)
10-28 12:30:17.013 29382 29382 W System.err: 	at android.content.res.MiuiResourcesImpl.updateConfiguration(MiuiResourcesImpl.java:248)
10-28 12:30:17.013 29382 29382 W System.err: 	at android.content.res.Resources.updateConfiguration(Resources.java:2226)
10-28 12:30:17.013 29382 29382 W System.err: 	at android.content.res.Resources.updateSystemConfiguration(Resources.java:2239)
10-28 12:30:17.013 29382 29382 W System.err: 	at android.app.ResourcesManager.applyConfigurationToResources(ResourcesManager.java:1392)
10-28 12:30:17.013 29382 29382 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6981)
10-28 12:30:17.013 29382 29382 W System.err: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
10-28 12:30:17.013 29382 29382 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
10-28 12:30:17.013 29382 29382 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-28 12:30:17.013 29382 29382 W System.err: 	at android.os.Looper.loopOnce(Looper.java:211)
10-28 12:30:17.013 29382 29382 W System.err: 	at android.os.Looper.loop(Looper.java:300)
10-28 12:30:17.013 29382 29382 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8395)
10-28 12:30:17.013 29382 29382 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-28 12:30:17.013 29382 29382 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
10-28 12:30:17.013 29382 29382 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
10-28 12:30:17.018 29382 10983 D AppScoutStateMachine: 29382-ScoutStateMachinecreated
```

**Comment by inotia00** [comment]
It does not reproduce on my side

Try reinstalling RVX Manager

**Comment by AniruddhaSadhukhan** [comment]
Thanks, clearing data of RVX manager did the trick

**Comment by flying-night-slasher** [comment]
I have this same problem
