### ISSUE TITLE
bug: <Unable to patch YouTube>

### ISSUE THREAD

**Issue by shubamg1234567890** [inotia00/ReVanced_Extended#1606]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube v18. 41.39

### Bug description

I was trying to patch the YouTube downloaded from interent

### Steps to reproduce

All the default patches.. No changes.. 

### Relevant log output

```shell
- Device Info
ReVanced Manager: 1.14.2
Build: release
Model: SM-A505F
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.41.39
Patches version: v2.195.6
Patches: Alternative thumbnails, Ambient mode switch, Append time stamps information, Change homepage, Custom branding icon Revancify Blue, Custom branding name YouTube [App name: ReVanced Extended], Custom double tap length [Double-tap to seek Values: 3, 5, 10, 15, 20, 30, 60, 120, 180], Custom package name [Package name of YouTube: app.rvx.android.youtube, Package name of YouTube Music: app.rvx.android.apps.youtube.music], Custom playback speed, Custom player overlay opacity, Custom seekbar color, Default playback speed, Default video quality, Disable HDR video, Disable QUIC protocol, Disable auto captions, Disable haptic feedback, Disable pip notification, Disable shorts on startup, Enable compact controls overlay, Enable external browser, Enable gradient loading screen, Enable language switch, Enable minimized playback, Enable new splash animation, Enable new thumbnail preview, Enable old quality layout, Enable open links directly, Enable seekbar tapping, Enable tablet mini player, Enable tablet navigation bar, Enable wide search bar, Force OPUS codec, Force video codec, Hide account menu, Hide auto player popup panels, Hide autoplay button, Hide autoplay preview, Hide button container, Hide captions button, Hide cast button, Hide category bar, Hide channel avatar section, Hide channel watermark, Hide collapse button, Hide comment component, Hide crowdfunding box, Hide description components, Hide end screen cards, Hide end screen overlay, Hide feed flyout panel, Hide filmstrip overlay, Hide floating microphone, Hide fullscreen panels, Hide general ads, Hide handle, Hide info cards, Hide latest videos button, Hide layout components, Hide load more button, Hide mix playlists, Hide music button, Hide navigation buttons, Hide navigation label, Hide player button background, Hide player flyout panel, Hide previous next button, Hide seek message, Hide seekbar, Hide shorts components, Hide snack bar, Hide suggested actions, Hide suggested video overlay, Hide suggestions shelf, Hide time stamp, Hide toolbar button, Hide tooltip content, Hide trending searches, Hide video ads, Layout switch, MicroG support, Overlay buttons [Outline icons: false], Premium heading [Use premium heading: true], Quick actions components, Return YouTube Dislike, Settings, SponsorBlock [Outline icons: false], Spoof app version, Spoof device dimensions, Spoof player parameters, Swipe controls, Theme [Dark theme background color: @android:color/black], Translations

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
An error occurred:
brut.androlib.exceptions.AndrolibException: Could not generate: values-fr/strings.xml
	at brut.androlib.res.ResourcesDecoder.generateValuesFile(ResourcesDecoder.java:223)
	at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:182)
	at app.revanced.patcher.data.ResourceContext.decodeResources$revanced_patcher(ResourceContext.kt:50)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:195)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Caused by: brut.directory.DirectoryException: file must be a directory: /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-TRGMRJ/cache/res/values-fr
	at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
	at brut.directory.FileDirectory.createDirLocal(FileDirectory.java:64)
	at brut.directory.AbstractDirectory.createDir(AbstractDirectory.java:149)
	at brut.directory.AbstractDirectory.getFileOutput(AbstractDirectory.java:122)
	at brut.androlib.res.ResourcesDecoder.generateValuesFile(ResourcesDecoder.java:205)
	... 20 more
```

### Screenshots or videos

- Device Info
ReVanced Manager: 1.14.2
Build: release
Model: SM-A505F
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.41.39
Patches version: v2.195.6
Patches: Alternative thumbnails, Ambient mode switch, Append time stamps information, Change homepage, Custom branding icon Revancify Blue, Custom branding name YouTube [App name: ReVanced Extended], Custom double tap length [Double-tap to seek Values: 3, 5, 10, 15, 20, 30, 60, 120, 180], Custom package name [Package name of YouTube: app.rvx.android.youtube, Package name of YouTube Music: app.rvx.android.apps.youtube.music], Custom playback speed, Custom player overlay opacity, Custom seekbar color, Default playback speed, Default video quality, Disable HDR video, Disable QUIC protocol, Disable auto captions, Disable haptic feedback, Disable pip notification, Disable shorts on startup, Enable compact controls overlay, Enable external browser, Enable gradient loading screen, Enable language switch, Enable minimized playback, Enable new splash animation, Enable new thumbnail preview, Enable old quality layout, Enable open links directly, Enable seekbar tapping, Enable tablet mini player, Enable tablet navigation bar, Enable wide search bar, Force OPUS codec, Force video codec, Hide account menu, Hide auto player popup panels, Hide autoplay button, Hide autoplay preview, Hide button container, Hide captions button, Hide cast button, Hide category bar, Hide channel avatar section, Hide channel watermark, Hide collapse button, Hide comment component, Hide crowdfunding box, Hide description components, Hide end screen cards, Hide end screen overlay, Hide feed flyout panel, Hide filmstrip overlay, Hide floating microphone, Hide fullscreen panels, Hide general ads, Hide handle, Hide info cards, Hide latest videos button, Hide layout components, Hide load more button, Hide mix playlists, Hide music button, Hide navigation buttons, Hide navigation label, Hide player button background, Hide player flyout panel, Hide previous next button, Hide seek message, Hide seekbar, Hide shorts components, Hide snack bar, Hide suggested actions, Hide suggested video overlay, Hide suggestions shelf, Hide time stamp, Hide toolbar button, Hide tooltip content, Hide trending searches, Hide video ads, Layout switch, MicroG support, Overlay buttons [Outline icons: false], Premium heading [Use premium heading: true], Quick actions components, Return YouTube Dislike, Settings, SponsorBlock [Outline icons: false], Spoof app version, Spoof device dimensions, Spoof player parameters, Swipe controls, Theme [Dark theme background color: @android:color/black], Translations

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
An error occurred:
brut.androlib.exceptions.AndrolibException: Could not generate: values-fr/strings.xml
	at brut.androlib.res.ResourcesDecoder.generateValuesFile(ResourcesDecoder.java:223)
	at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:182)
	at app.revanced.patcher.data.ResourceContext.decodeResources$revanced_patcher(ResourceContext.kt:50)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:195)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Caused by: brut.directory.DirectoryException: file must be a directory: /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-TRGMRJ/cache/res/values-fr
	at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
	at brut.directory.FileDirectory.createDirLocal(FileDirectory.java:64)
	at brut.directory.AbstractDirectory.createDir(AbstractDirectory.java:149)
	at brut.directory.AbstractDirectory.getFileOutput(AbstractDirectory.java:122)
	at brut.androlib.res.ResourcesDecoder.generateValuesFile(ResourcesDecoder.java:205)
	... 20 more

### Solution

The last version I patch normally was v 18.37.36

### Additional context

I got same issue in patch of v 18.40.34
..

### Device Environment

One UI  3

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
reinstall RVX Manager

**Comment by shubamg1234567890** [comment]
Sir, I literally have reinstalled it for like four times.. I swear by God but the result were same everytime 🙏🏻 even I have installed apk in my secure folder.. but no change in results.. error persists..

**Comment by inotia00** [comment]
Unfortunately, it does not reproduce on my side.

Since I don't have enough knowledge about RVX Manager, the only advice I can give you is to just use another patch method.

e.g. [rvx-builder](https://github.com/inotia00/rvx-builder/wiki/How-to-use-rvx-builder-on-Android)

**Comment by shubamg1234567890** [comment]
> Unfortunately, it does not reproduce on my side.
> 
> Since I don't have enough knowledge about RVX Manager, the only advice I can give you is to just use another patch method.
> 
> e.g. [rvx-builder](https://github.com/inotia00/rvx-builder/wiki/How-to-use-rvx-builder-on-Android) 


Sir, thankyou this revanced builder saved my day.. it's working though it's pain at first but worth it.. Thx 😊🙏🏻 once again.. May God bless you.. 🍀🍁
