### ISSUE TITLE
bug: Applying Patches Failure

### ISSUE THREAD

**Issue by abdogm** [inotia00/ReVanced_Extended#1616]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube 18.41.39

### Bug description

It happened randomly when selecting some specific patches (not selecting all)

### Steps to reproduce

When "custom playback speed" is selected (for now that is all what i found)

### Relevant log output

```shell
- Device Info
ReVanced Manager: 1.14.2
Build: release
Model: Redmi Note 7
Android version: 10
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.41.39
Patches version: v2.195.6
Patches: Append time stamps information, Custom branding icon MMT, Custom branding name YouTube [App name: ReVanced Extended], Custom double tap length [Double-tap to seek Values: 3, 5, 10, 15, 20, 30, 60, 120, 180], Custom package name [Package name of YouTube: app.rvx.android.youtube, Package name of YouTube Music: app.rvx.android.apps.youtube.music], Custom playback speed, Custom seekbar color, Default playback speed, Default video quality, Disable HDR video, Disable QUIC protocol, Disable auto captions, Disable haptic feedback, Disable pip notification, Disable shorts on startup, Enable external browser, Enable gradient loading screen, Enable language switch, Enable minimized playback, Enable new thumbnail preview, Enable old quality layout, Enable open links directly, Enable seekbar tapping, Enable tablet mini player, Enable wide search bar, Force OPUS codec, Force hide player button background, Force video codec, Hide account menu, Hide auto player popup panels, Hide autoplay button, Hide autoplay preview, Hide button container, Hide captions button, Hide cast button, Hide category bar, Hide channel avatar section, Hide channel watermark, Hide collapse button, Hide comment component, Hide crowdfunding box, Hide description components, Hide double tap overlay filter, Hide end screen overlay, Hide feed flyout panel, Hide filmstrip overlay, Hide floating microphone, Hide fullscreen panels, Hide general ads, Hide handle, Hide latest videos button, Hide layout components, Hide load more button, Hide mix playlists, Hide music button, Hide navigation buttons, Hide navigation label, Hide player flyout panel, Hide previous next button, Hide seek message, Hide shorts components, Hide snack bar, Hide suggested actions, Hide suggested video overlay, Hide suggestions shelf, Hide time stamp, Hide toolbar button, Hide tooltip content, Hide trending searches, Hide video ads, Layout switch, MicroG support, Overlay buttons [Outline icons: false], Quick actions components, Return YouTube Dislike, Settings, SponsorBlock [Outline icons: false], Spoof app version, Spoof device dimensions, Spoof player parameters, Theme [Dark theme background color: @android:color/black], Translations

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Append time stamps information succeeded
Custom branding icon MMT succeeded
Custom branding name YouTube succeeded
Custom double tap length succeeded
Custom package name succeeded
Custom playback speed failed: app.revanced.patcher.patch.PatchException: 'Custom playback speed' depends on 'OldSpeedLayoutPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: 'OldSpeedLayoutPatch' depends on 'LithoFilterPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Failed to resolve LithoFilterFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:34)
	at app.revanced.patches.youtube.utils.litho.LithoFilterPatch.execute(LithoFilterPatch.kt:58)
	at app.revanced.patches.youtube.utils.litho.LithoFilterPatch.execute(LithoFilterPatch.kt:17)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Custom seekbar color succeeded
Default playback speed succeeded
Default video quality succeeded
Disable HDR video succeeded
Disable QUIC protocol succeeded
Disable auto captions succeeded
Disable haptic feedback succeeded
Disable pip notification succeeded
Disable shorts on startup succeeded
Enable external browser succeeded
Enable gradient loading screen succeeded
Enable language switch succeeded
Enable minimized playback succeeded
Enable new thumbnail preview succeeded
Enable old quality layout failed: app.revanced.patcher.patch.PatchException: 'Enable old quality layout' depends on 'LithoFilterPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:150)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Enable open links directly succeeded
Enable seekbar tapping succeeded
Enable tablet mini player succeeded
Enable wide search bar succeeded
Force OPUS codec succeeded
Force hide player button background succeeded
Force video codec succeeded
Hide account menu failed: app.revanced.patcher.patch.PatchException: Failed to resolve AccountMenuPatchFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:34)
	at app.revanced.patches.youtube.general.accountmenu.AccountMenuPatch.execute(AccountMenuPatch.kt:117)
	at app.revanced.patches.youtube.general.accountmenu.AccountMenuPatch.execute(AccountMenuPatch.kt:23)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Hide auto player popup panels succeeded
Hide autoplay button succeeded
Hide autoplay preview succeeded
Hide button container failed: app.revanced.patcher.patch.PatchException: 'Hide button container' depends on 'LithoFilterPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:150)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Hide captions button succeeded
Hide cast button succeeded
Hide category bar succeeded
Hide channel avatar section succeeded
Hide channel watermark failed: app.revanced.patcher.patch.PatchException: 'Hide channel watermark' depends on 'LithoFilterPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:150)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Hide collapse button succeeded
Hide comment component failed: app.revanced.patcher.patch.PatchException: 'Hide comment component' depends on 'LithoFilterPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:150)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Hide crowdfunding box succeeded
Hide description components failed: app.revanced.patcher.patch.PatchException: 'Hide description components' depends on 'LithoFilterPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: 'LithoFilterPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:150)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:919)
Hide double tap overlay filter succeeded
Hide end screen overlay succeeded
Hide feed flyout panel succeeded
Hide filmstrip overlay succeeded
Hide floating microphone succeeded
Hide fullscreen panels succeeded
```

### Screenshots or videos

![Screenshot_2023-10-29-11-48-02-640_app rvx manager flutter](https://github.com/inotia00/ReVanced_Extended/assets/72724405/30b161d7-4fc9-4e38-a2c9-5674fb3a612e)

### Solution

Not completely sure but unselecting will fix it for now

### Additional context

nothing to add

### Device Environment

Android 10, MIUI 12.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
In [revanced-patches-v2.195.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.12), support for YouTube v18.41.39+has been dropped
Patch again with YouTube v18.40.34

If the issue persists, please open a new issue

**Comment by abdogm** [comment]
> In [revanced-patches-v2.195.12](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.12), support for YouTube v18.41.39+ has been dropped Please patch again with YouTube v18.40.34
> 
> If the issue persists, please open a new issue

thanks for the help
it is working fine now
