### ISSUE TITLE
bug: pip mode while download 

### ISSUE THREAD

**Issue by Sishdbds277** [inotia00/ReVanced_Extended#1622]
### Type

Other

### Tools used

ReVanced Manager

### Application

Youtube v18.41.39

### Bug description

Pip mode automatically activated while downloading any video

### Steps to reproduce

Dont know. 

### Relevant log output

```shell
--------- beginning of main
10-30 13:28:27.510 12753 12753 I manager.flutter: Using CollectorTypeCC GC.
10-30 13:28:27.520 12753 12753 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
10-30 13:28:27.536 12753 12753 W System.err: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
10-30 13:28:27.536 12753 12753 W System.err: 	at libcore.io.Linux.open(Native Method)
10-30 13:28:27.536 12753 12753 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
10-30 13:28:27.536 12753 12753 W System.err: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
10-30 13:28:27.536 12753 12753 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
10-30 13:28:27.536 12753 12753 W System.err: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8288)
10-30 13:28:27.536 12753 12753 W System.err: 	at android.system.Os.open(Os.java:494)
10-30 13:28:27.536 12753 12753 W System.err: 	at android.os.perfdebug.PerfDebugMonitorImpl.monitorVersionControl(PerfDebugMonitorImpl.java:204)
10-30 13:28:27.536 12753 12753 W System.err: 	at android.os.perfdebug.PerfDebugMonitorImpl.prepareMonitor(PerfDebugMonitorImpl.java:185)
10-30 13:28:27.536 12753 12753 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8375)
10-30 13:28:27.536 12753 12753 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-30 13:28:27.537 12753 12753 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
10-30 13:28:27.537 12753 12753 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
10-30 13:28:27.537 12753 12753 I MessageMonitor: Load libmiui_runtime
10-30 13:28:27.582 12753 12753 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 11753; state: ENABLED
10-30 13:28:27.586 12753 12778 D AppScoutStateMachine: 12753-ScoutStateMachinecreated
10-30 13:28:27.616 12753 12753 D nativeloader: Configuring classloader-namespace for other apk /data/app/~~jKnJmEFNf6g0LIU-5bw6gg==/app.rvx.manager.flutter-Kjz0eijyqcjIuEAactvNaQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~jKnJmEFNf6g0LIU-5bw6gg==/app.rvx.manager.flutter-Kjz0eijyqcjIuEAactvNaQ==/lib/arm64:/data/app/~~jKnJmEFNf6g0LIU-5bw6gg==/app.rvx.manager.flutter-Kjz0eijyqcjIuEAactvNaQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/app.rvx.manager.flutter
10-30 13:28:27.652 12753 12753 I Perf    : Connecting to perf service.
10-30 13:28:27.661 12753 12753 V GraphicsEnvironment: ANGLE Developer option for 'app.rvx.manager.flutter' set to: 'default'
10-30 13:28:27.662 12753 12753 V GraphicsEnvironment: ANGLE GameManagerService for app.rvx.manager.flutter: false
10-30 13:28:27.663 12753 12753 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
10-30 13:28:27.668 12753 12753 I ForceDarkHelperStubImpl: initialize for app.rvx.manager.flutter , ForceDarkOrigin
10-30 13:28:27.669 12753 12753 D manager.flutter: JNI_OnLoad success
10-30 13:28:27.669 12753 12753 I MiuiForceDarkConfig: setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
10-30 13:28:27.672 12753 12753 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-30 13:28:27.672 12753 12753 D NetworkSecurityConfig: No Network Security Config specified, using platform default
10-30 13:28:27.988 12753 12753 D MiuiMultiWindowAdapter: MiuiMultiWindowAdapter::getFreeformVideoWhiteListInSystem::LIST_ABOUT_SUPPORT_LANDSCAPE_VIDEO = [com.hunantv.imgo.activity, com.tencent.qqlive, com.qiyi.video, com.hunantv.imgo.activity.inter, com.tencent.qqlivei18n, com.iqiyi.i18n, tv.danmaku.bili]
10-30 13:28:28.023 12753 12753 W libc    : Access denied finding property "ro.vendor.df.effect.conflict"
10-30 13:28:28.107 12753 12753 I AdrenoGLES-0: QUALCOMM build                   : 3e33337ce3, I07ee46fc66
10-30 13:28:28.107 12753 12753 I AdrenoGLES-0: Build Date                       : 10/08/21
10-30 13:28:28.107 12753 12753 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.35.01.10
10-30 13:28:28.107 12753 12753 I AdrenoGLES-0: Local Branch                     : 
10-30 13:28:28.107 12753 12753 I AdrenoGLES-0: Remote Branch                    : 
10-30 13:28:28.107 12753 12753 I AdrenoGLES-0: Remote Branch                    : 
10-30 13:28:28.107 12753 12753 I AdrenoGLES-0: Reconstruct Branch               : 
10-30 13:28:28.107 12753 12753 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
10-30 13:28:28.107 12753 12753 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
10-30 13:28:28.112 12753 12753 I AdrenoGLES-0: PFP: 0x016ee201, ME: 0x00000000
10-30 13:28:28.130 12753 12900 W libc    : Access denied finding property "vendor.migl.debug"
10-30 13:28:28.159 12753 12753 D FlutterFileDialogPlugin: onAttachedToEngine - IN
10-30 13:28:28.159 12753 12753 D FlutterFileDialogPlugin: doOnAttachedToEngine - IN
10-30 13:28:28.159 12753 12753 D FlutterFileDialogPlugin: doOnAttachedToEngine - OUT
10-30 13:28:28.159 12753 12753 D FlutterFileDialogPlugin: onAttachedToEngine - OUT
10-30 13:28:28.159 12753 12753 D FlutterFileDialogPlugin: onAttachedToActivity
10-30 13:28:28.159 12753 12753 D FlutterFileDialogPlugin: doOnAttachedToActivity - IN
10-30 13:28:28.159 12753 12753 D FlutterFileDialogPlugin: doOnAttachedToActivity - OUT
10-30 13:28:28.199 12753 12753 D IS_CTS_MODE: false
10-30 13:28:28.199 12753 12753 D MULTI_WINDOW_ENABLED: false
10-30 13:28:28.201 12753 12753 D DecorView[]: getWindowModeFromSystem  windowmode is 1
10-30 13:28:28.226 12753 12753 D DecorView[]: getWindowModeFromSystem  windowmode is 1
10-30 13:28:28.226 12753 12753 D DecorView[]: updateDecorCaptionStatus windowMode is 1
--------- beginning of system
10-30 13:28:28.234 12753 12753 W Looper  : PerfMonitor looperActivity : package=app.rvx.manager.flutter/app.revanced.manager.flutter.MainActivity time=252ms latency=407ms  procState=-1  historyMsgCount=2 (msgIndex=2 wall=400ms seq=2 late=9ms h=android.app.ActivityThread$H w=110)
10-30 13:28:28.234 12753 12753 W Looper  : PerfMonitor looperActivity : package=app.rvx.manager.flutter/app.revanced.manager.flutter.MainActivity time=0ms latency=659ms  procState=-1  historyMsgCount=3 (msgIndex=2 wall=400ms seq=2 late=9ms h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=252ms seq=3 late=407ms h=android.app.ActivityThread$H w=159)
10-30 13:28:28.238 12753 12753 D FramePredict: FramePredict init: false
10-30 13:28:28.298 12753 12753 D VRI[MainActivity]: vri.reportNextDraw android.view.ViewRootImpl.performTraversals:3878 android.view.ViewRootImpl.doTraversal:2610 android.view.ViewRootImpl$TraversalRunnable.run:9619 android.view.Choreographer$CallbackRecord.run:1491 android.view.Choreographer$CallbackRecord.run:1499 
10-30 13:28:28.298 12753 12753 D SurfaceView: UPDATE null, mIsCastMode = false
10-30 13:28:28.299 12753 12880 E libEGL  : pre_cache appList: com.sina.weibo,com.ss.android.article.news,com.taobao.taobao,com.smile.gifmaker,com.ss.android.ugc.aweme,com.tencent.mm,tv.danmaku.bili,,
10-30 13:28:28.630 13114 13114 W sh      : type=1400 audit(0.0:566702): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:28.650 13128 13128 W sh      : type=1400 audit(0.0:566703): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:28.670 13142 13142 W sh      : type=1400 audit(0.0:566704): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:28.690 13156 13156 W sh      : type=1400 audit(0.0:566705): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:28.710 13170 13170 W sh      : type=1400 audit(0.0:566706): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:28.780 12753 12753 I Choreographer: Skipped 59 frames!  The application may be doing too much work on its main thread.
10-30 13:28:28.780 12753 12753 D SurfaceView: UPDATE Surface(name=SurfaceView[app.rvx.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0x2d3eea2, mIsProjectionMode = false
10-30 13:28:28.780 12753 12753 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
10-30 13:28:28.781 12753 12753 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
10-30 13:28:28.781 12753 12753 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
10-30 13:28:28.781 12753 12753 W Looper  : PerfMonitor doFrame : time=2ms vsyncFrame=0 latency=501ms procState=-1 historyMsgCount=6 (msgIndex=1 wall=78ms seq=8 late=9ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=5 wall=461ms seq=12 late=74ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
10-30 13:28:28.810 12753 12897 I flutter : dynamic_color: Core palette detected.
10-30 13:28:28.840 12753 12753 D DecorView[]: getWindowModeFromSystem  windowmode is 1
10-30 13:28:28.840 12753 12753 D DecorView[]: updateDecorCaptionStatus windowMode is 1
10-30 13:28:28.849 12753 12753 D VRI[MainActivity]: vri.reportNextDraw android.view.ViewRootImpl.performTraversals:3878 android.view.ViewRootImpl.doTraversal:2610 android.view.ViewRootImpl$TraversalRunnable.run:9619 android.view.Choreographer$CallbackRecord.run:1491 android.view.Choreographer$CallbackRecord.run:1499 
10-30 13:28:28.857 12753 12753 D DecorView[]: getWindowModeFromSystem  windowmode is 1
10-30 13:28:28.857 12753 12753 D DecorView[]: updateDecorCaptionStatus windowMode is 1
10-30 13:28:28.867 12753 12753 D VRI[MainActivity]: vri.reportNextDraw android.view.ViewRootImpl.performTraversals:3878 android.view.ViewRootImpl.doTraversal:2610 android.view.ViewRootImpl$TraversalRunnable.run:9619 android.view.Choreographer$CallbackRecord.run:1491 android.view.Choreographer$CallbackRecord.run:1499 
10-30 13:28:28.881 12753 12899 E LB      : fail to open node: No such file or directory
10-30 13:28:28.889 12753 12753 D VRI[MainActivity]: vri.Setup new sync id=0 syncSeqId=0
10-30 13:28:28.889 12753 12753 E SurfaceSyncer: Failed to find sync for id=0
10-30 13:28:28.891 12753 12880 D manager.flutter: MiuiProcessManagerServiceStub setSchedFifo
10-30 13:28:28.891 12753 12880 I MiuiProcessManagerImpl: setSchedFifo pid:12753, mode:3
10-30 13:28:28.903 12753 12880 E perf_hint: Session creation failed, mPreferredRateNanos: -1
10-30 13:28:28.904 12753 12753 D VRI[MainActivity]: vri.reportDrawFinished syncSeqId=0 android.view.ViewRootImpl.lambda$createSyncIfNeeded$4$android-view-ViewRootImpl:3946 android.view.ViewRootImpl$$ExternalSyntheticLambda1.run:6 android.os.Handler.handleCallback:942 android.os.Handler.dispatchMessage:99 android.os.Looper.loopOnce:211 
10-30 13:28:28.937 12753 12753 D DecorView[]: onWindowFocusChanged hasWindowFocus true
10-30 13:28:28.938 12753 12753 I HandWritingStubImpl: refreshLastKeyboardType: 1
10-30 13:28:28.938 12753 12753 I HandWritingStubImpl: getCurrentKeyboardType: 1
10-30 13:28:28.954 12753 12753 I HandWritingStubImpl: getCurrentKeyboardType: 1
10-30 13:28:29.457 12753 12753 W MirrorManager: this model don't Support
10-30 13:28:30.563 12753 12753 W InputTransport: PerfMonitor: 354ms so far, channel '2a8a21f app.rvx.manager.flutter/app.revanced.manager.flutter.MainActivity (client)' consumer ~ consumed montion event,seq=6400549
10-30 13:28:30.565 12753 12753 W InputTransport: PerfMonitor: 245ms so far, channel '2a8a21f app.rvx.manager.flutter/app.revanced.manager.flutter.MainActivity (client)' consumer ~ consumed montion event,seq=6400618
10-30 13:28:33.794 13564 13564 W sh      : type=1400 audit(0.0:566710): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:33.806 13564 13564 W sh      : type=1400 audit(0.0:566711): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:33.838 13564 13564 W sh      : type=1400 audit(0.0:566712): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:33.878 13564 13564 W sh      : type=1400 audit(0.0:566713): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:33.890 13564 13564 W sh      : type=1400 audit(0.0:566714): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:34.850 13788 13788 W sh      : type=1400 audit(0.0:566729): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:34.914 13802 13802 W sh      : type=1400 audit(0.0:566730): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:35.006 13816 13816 W sh      : type=1400 audit(0.0:566731): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:35.094 13830 13830 W sh      : type=1400 audit(0.0:566732): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:35.186 13851 13851 W sh      : type=1400 audit(0.0:566733): avc: denied { read } for name="/" dev="dm-7" ino=2 scontext=u:r:untrusted_app:s0:c217,c262,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.rvx.manager.flutter
10-30 13:28:35.311 12753 12753 W Looper  : PerfMonitor longMsg : seq=59 plan=13:28:33.766 late=0ms wall=1541ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=-1
10-30 13:28:38.585 12753 12753 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 11753; state: ENABLED
10-30 13:28:38.703 12753 12753 D DecorView[]: onWindowFocusChanged hasWindowFocus false
10-30 13:28:43.417 12753 12753 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 11753; state: ENABLED
10-30 13:28:43.418 12753 12753 I InstallPlugin: handleActivityResult(22643,0,null)
10-30 13:28:43.468 12753 12753 D DecorView[]: getWindowModeFromSystem  windowmode is 1
10-30 13:28:43.468 12753 12753 D DecorView[]: updateDecorCaptionStatus windowMode is 1
10-30 13:28:43.477 12753 12753 D DecorView[]: onWindowFocusChanged hasWindowFocus true
10-30 13:28:43.478 12753 12753 I HandWritingStubImpl: refreshLastKeyboardType: 1
10-30 13:28:43.478 12753 12753 I HandWritingStubImpl: getCurrentKeyboardType: 1
10-30 13:28:44.538 12753 12753 D DecorView[]: onWindowFocusChanged hasWindowFocus false
10-30 13:28:45.951 12753 12753 I InstallPlugin: handleActivityResult(22643,0,null)
10-30 13:28:45.990 12753 12753 D DecorView[]: onWindowFocusChanged hasWindowFocus true
10-30 13:28:45.991 12753 12753 I HandWritingStubImpl: refreshLastKeyboardType: 1
10-30 13:28:45.991 12753 12753 I HandWritingStubImpl: getCurrentKeyboardType: 1
```

### Screenshots or videos

[](https://drive.google.com/file/d/1D5gbUy7b9aJRZ3Wk49xOd63aI768_Qm7/view?usp=drivesdk)

### Device Environment

Miui 14, android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Sishdbds277** [comment]
https://drive.google.com/file/d/1D5gbUy7b9aJRZ3Wk49xOd63aI768_Qm7/view?usp=drivesdk

**Comment by inotia00** [comment]
This is natural, since external downloaders open in another windows.

When you use the Share feature provided by YouTube to forward a link to another app or open an external link on YouTube, it also opens in another window.

In this case too, YouTube switches to PiP mode, but no one is calling this a bug.
