### ISSUE TITLE
bug(YouTube): video upload cause YT app to crash

### ISSUE THREAD

**Issue by Retardium** [inotia00/ReVanced_Extended#1637]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube Version 18.40.34 (default patches only)

### Bug description

The patched YT app crashes when I upload a video - mostly videos with a duration < 60 seconds, but not all short videos cause a crash.
Long videos seem to work.

### Steps to reproduce

1. Get the "crash" labeled video I've uploaded.
2. Click upload button.
3. Choose "Upload a video".
3. Select the video.
5. Click next in the editor.
6. Crash. :'(

### Relevant log output

```shell
java.lang.IllegalStateException: MlKitContext has not been initialized
	at a.ah(PG:2)
	at albp.a(PG:1)
	at albg.a(PG:1)
	at vlk.get(PG:14)
	at uwf.<init>(PG:28)
	at xzl.<init>(PG:22)
	at abrx.eG(PG:1)
	at ftf.d(PG:4)
	at abrx.em(PG:1)
	at ftf.c(PG:2)
	at xqd.y(PG:1)
	at xpe.x(PG:7)
	at iju.M(PG:52)
	at bz.nQ(PG:3)
	at ooq.e(PG:24)
	at ooq.g(PG:205)
	at cv.aA(PG:122)
	at cv.aC(PG:10)
	at cv.I(PG:3)
	at bb.d(PG:2)
	at iqo.a(PG:7)
	at iqo.c(PG:17)
	at ipa.v(PG:94)
	at ipa.u(PG:1)
	at ipa.k(PG:4)
	at sti.K(PG:75)
	at isa.onClick(PG:3)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Additional context

Seems to be the same bug I reported here: https://github.com/inotia00/ReVanced_Extended/issues/1627

### Device Environment

Android 13, CalyxOS 4.14.1
Pixel 7 Pro

mMicroG Version 0.2.27.231613
+
regular microG Version 0.2.29.233013
app.rvx.manager.flutter Version 1.14.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by Retardium** [comment]
Video which cause a crash.
[short_video-crash.zip](https://github.com/inotia00/ReVanced_Extended/files/13227246/short_video-crash.zip)

**Comment by inotia00** [comment]
Still not reproduced on my side

There may be users who visit this page with the same issue, and they may provide more useful information, so I will leave the issue open

**Comment by inotia00** [comment]
Exclude patches one by one until the issue is not reproduced.
And please let me know which patch is the cause of the issue

**Comment by inotia00** [comment]
find which patch causes the issue, and then open the issue again.

**Comment by Retardium** [comment]
Hi, sorry for the late response.
I've update to the latest patches and the new recommended version of YT (18.45.43).
I could not experience any crashes while uploading any videos. 👍
I suspect it was a bug in the YT client.
