### ISSUE TITLE
bug(YouTube Music): `Sanitize sharing links` patch failed on 6.15.52

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1675]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube Music 6.15.52

### Bug description

`Sanitize sharing links` patch failed on 6.15.52

### Steps to reproduce

Step 1. Include `Sanitize sharing links` patch
Step 2. Patch YouTube Music 6.15.52

### Relevant log output

```shell
INFO: Loading patches
INFO: Decoding app manifest
INFO: Excluding Custom branding icon Revancify Blue
INFO: Custom branding icon Revancify Red excluded
INFO: Enable debug logging excluded
INFO: Excluding Custom branding icon Revancify Blue
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: Amoled succeeded
INFO: Background play succeeded
INFO: Bitrate default value succeeded
INFO: Certificate spoof succeeded
INFO: Custom branding icon MMT succeeded
INFO: Custom branding name YouTube Music succeeded
INFO: Custom package name succeeded
INFO: Custom playback speed succeeded
INFO: Disable auto captions succeeded
INFO: Enable black navigation bar succeeded
INFO: Enable color match player succeeded
INFO: Enable compact dialog succeeded
INFO: Enable custom filter succeeded
INFO: Enable force minimized player succeeded
INFO: Enable landscape mode succeeded
INFO: Enable minimized playback succeeded
INFO: Enable new player background succeeded
INFO: Enable old player layout succeeded
INFO: Enable old style library shelf succeeded
INFO: Enable old style miniplayer succeeded
INFO: Enable opus codec succeeded
INFO: Enable playback speed succeeded
INFO: Enable sleep timer succeeded
INFO: Enable zen mode succeeded
INFO: Exclusive audio playback succeeded
INFO: Hide account menu succeeded
INFO: Hide action bar label succeeded
INFO: Hide button shelf succeeded
INFO: Hide carousel shelf succeeded
INFO: Hide cast button succeeded
INFO: Hide category bar succeeded
INFO: Hide channel guidelines succeeded
INFO: Hide emoji picker succeeded
INFO: Hide flyout panel succeeded
INFO: Hide get premium succeeded
INFO: Hide handle succeeded
INFO: Hide music ads succeeded
INFO: Hide navigation bar component succeeded
INFO: Hide new playlist button succeeded
INFO: Hide playlist card succeeded
INFO: Hide radio button succeeded
INFO: Hide taste builder succeeded
INFO: Hide terms container succeeded
INFO: Hide tooltip content succeeded
INFO: Hook download button succeeded
INFO: MicroG support succeeded
INFO: Remember playback speed succeeded
INFO: Remember repeat state succeeded
INFO: Remember shuffle state succeeded
INFO: Remember video quality succeeded
INFO: Replace cast button succeeded
INFO: Replace dismiss queue succeeded
INFO: Return YouTube Dislike succeeded
SEVERE: Sanitize sharing links failed:
app.revanced.patcher.patch.PatchException: Failed to resolve CopyTextEndpointFingerprint
        at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:34)
        at app.revanced.patches.shared.patch.tracking.AbstractSanitizeUrlQueryPatch.invoke(AbstractSanitizeUrlQueryPatch.kt:34)
        at app.revanced.patches.shared.patch.tracking.AbstractSanitizeUrlQueryPatch.execute(AbstractSanitizeUrlQueryPatch.kt:39)
        at app.revanced.patches.music.misc.tracking.SanitizeUrlQueryPatch.execute(SanitizeUrlQueryPatch.kt:39)
        at app.revanced.patches.music.misc.tracking.SanitizeUrlQueryPatch.execute(SanitizeUrlQueryPatch.kt:13)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:246)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)

INFO: SponsorBlock succeeded
INFO: Spoof app version succeeded
INFO: Start page succeeded
INFO: Translations succeeded
INFO: Settings succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiling modified resources
INFO: Aligning ytm2.apk
INFO: Signing ytm2.apk
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
I was planning to drop support for v6.15.52
(Because the last version compatible with Android 5.0 is v6.20.51)

I forgot to drop support for v6.15.52
