### ISSUE TITLE
bug(Youtube/Hide-end-screen-overlay): entering fullscreen mode immediately crash

### ISSUE THREAD

**Issue by 0frd** [inotia00/ReVanced_Extended#1678]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube 18.43.45

### Bug description

The app Immediately crash when entering fullscreen mode

### Steps to reproduce

1. Switch hide end screen overlay on and play some videos and tap on fullscreen mode

### Relevant log output

```shell
aypl: 2 exceptions occurred. 
	at azpw.c(PG:5)
	at azpw.vE(PG:5)
	at ayyj.d(PG:5)
	at ayyj.vE(PG:2)
	at azrc.vM(PG:4)
	at azrc.b(PG:7)
	at azrd.vE(PG:6)
	at afob.f(PG:2)
	at afuo.E(PG:1)
	at kmc.c(PG:4)
	at kmc.a(PG:2)
	at kmf.pN(PG:3)
	at glg.c(PG:1)
	at kmf.pO(Unknown Source:0)
	at gwe.a(PG:44)
	at ayrt.vE(PG:2)
	at azfk.vE(PG:13)
	at azqt.c(PG:3)
	at azjl.e(PG:6)
	at azjq.f(PG:3)
	at azjq.vE(PG:2)
	at azjj.vE(PG:1)
	at azjd.vE(PG:2)
	at azfp.vE(PG:11)
	at azgm.vE(PG:3)
	at azfu.vE(PG:1)
	at azfs.d(PG:7)
	at azfr.vE(PG:7)
	at azhx.vE(PG:1)
	at ayzd.b(PG:14)
	at ayzi.vE(PG:6)
	at ayvq.vE(PG:4)
	at ayyx.vE(PG:1)
	at ayyu.d(PG:10)
	at ayyu.vE(PG:2)
	at azrc.vM(PG:4)
	at azrc.b(PG:7)
	at azrd.vE(PG:6)
	at mvy.h(PG:3)
	at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.w(PG:1)
	at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.x(PG:1)
	at ngq.o(PG:16)
	at ngq.s(PG:2)
	at ngq.c(PG:7)
	at hru.j(PG:28)
	at hhn.c(PG:2)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onConfigurationChanged(PG:12)
	at android.app.ActivityThread.performActivityConfigurationChanged(Unknown Source:145)
	at android.app.ActivityThread.performConfigurationChangedForActivity(Unknown Source:28)
	at android.app.ActivityThread.handleActivityConfigurationChanged(Unknown Source:273)
	at android.app.servertransaction.ActivityConfigurationChangeItem.execute(Unknown Source:10)
	at android.app.servertransaction.ActivityTransactionItem.execute(Unknown Source:4)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:172)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:108)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
  ComposedException 1 :
	java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setVisibility(int)' on a null object reference
		at afmc.onAnimationStart(PG:1)
		at android.animation.Animator$AnimatorListener.onAnimationStart(Unknown Source:0)
		at android.animation.ValueAnimator.notifyStartListeners(Unknown Source:31)
		at android.animation.ValueAnimator.startAnimation(Unknown Source:44)
		at android.animation.ValueAnimator.start(Unknown Source:91)
		at android.animation.ValueAnimator.start(Unknown Source:1)
		at android.animation.ObjectAnimator.start(Unknown Source:7)
		at afmd.r(PG:12)
		at afmd.q(PG:1)
		at afmd.p(PG:1)
		at afmh.m(PG:3)
		at afmh.d(PG:4)
		at afje.a(PG:53)
		at azpw.vE(PG:2)
		at ayyj.d(PG:5)
		at ayyj.vE(PG:2)
		at azrc.vM(PG:4)
		at azrc.b(PG:7)
		at azrd.vE(PG:6)
		at afob.f(PG:2)
		at afuo.E(PG:1)
		at kmc.c(PG:4)
		at kmc.a(PG:2)
		at kmf.pN(PG:3)
		at glg.c(PG:1)
		at kmf.pO(Unknown Source:0)
		at gwe.a(PG:44)
		at ayrt.vE(PG:2)
		at azfk.vE(PG:13)
		at azqt.c(PG:3)
		at azjl.e(PG:6)
		at azjq.f(PG:3)
		at azjq.vE(PG:2)
		at azjj.vE(PG:1)
		at azjd.vE(PG:2)
		at azfp.vE(PG:11)
		at azgm.vE(PG:3)
		at azfu.vE(PG:1)
		at azfs.d(PG:7)
		at azfr.vE(PG:7)
		at azhx.vE(PG:1)
		at ayzd.b(PG:14)
		at ayzi.vE(PG:6)
		at ayvq.vE(PG:4)
		at ayyx.vE(PG:1)
		at ayyu.d(PG:10)
		at ayyu.vE(PG:2)
		at azrc.vM(PG:4)
		at azrc.b(PG:7)
		at azrd.vE(PG:6)
		at mvy.h(PG:3)
		at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.w(PG:1)
		at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.x(PG:1)
		at ngq.o(PG:16)
		at ngq.s(PG:2)
		at ngq.c(PG:7)
		at hru.j(PG:28)
		at hhn.c(PG:2)
		at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onConfigurationChanged(PG:12)
		at android.app.ActivityThread.performActivityConfigurationChanged(Unknown Source:145)
		at android.app.ActivityThread.performConfigurationChangedForActivity(Unknown Source:28)
		at android.app.ActivityThread.handleActivityConfigurationChanged(Unknown Source:273)
		at android.app.servertransaction.ActivityConfigurationChangeItem.execute(Unknown Source:10)
		at android.app.servertransaction.ActivityTransactionItem.execute(Unknown Source:4)
		at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
		at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
		at android.app.ActivityThread$H.handleMessage(Unknown Source:172)
		at android.os.Handler.dispatchMessage(Unknown Source:19)
		at android.os.Looper.loopOnce(Unknown Source:182)
		at android.os.Looper.loop(Unknown Source:82)
		at android.app.ActivityThread.main(Unknown Source:108)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
		at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
	Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
		at android.util.Log.getStackTraceString(Unknown Source:13)
		at ahqp.uncaughtException(PG:1)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
		at ayet.k(PG:9)
		at azpw.c(PG:5)
		at azpw.vE(PG:5)
		at ayyj.d(PG:5)
		at ayyj.vE(PG:2)
		at azrc.vM(PG:4)
		at azrc.b(PG:7)
		at azrd.vE(PG:6)
		at afob.f(PG:2)
		at afuo.E(PG:1)
		at kmc.c(PG:4)
		at kmc.a(PG:2)
		at kmf.pN(PG:3)
		at glg.c(PG:1)
		at kmf.pO(Unknown Source:0)
		at gwe.a(PG:44)
		at ayrt.vE(PG:2)
		at azfk.vE(PG:13)
		at azqt.c(PG:3)
		at azjl.e(PG:6)
		at azjq.f(PG:3)
		at azjq.vE(PG:2)
		at azjj.vE(PG:1)
		at azjd.vE(PG:2)
		at azfp.vE(PG:11)
		at azgm.vE(PG:3)
		at azfu.vE(PG:1)
		at azfs.d(PG:7)
		at azfr.vE(PG:7)
		at azhx.vE(PG:1)
		at ayzd.b(PG:14)
		at ayzi.vE(PG:6)
		at ayvq.vE(PG:4)
		at ayyx.vE(PG:1)
		at ayyu.d(PG:10)
		at ayyu.vE(PG:2)
		at azrc.vM(PG:4)
		at azrc.b(PG:7)
		at azrd.vE(PG:6)
		at mvy.h(PG:3)
		at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.w(PG:1)
		at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.x(PG:1)
		at ngq.o(PG:16)
		at ngq.s(PG:2)
		at ngq.c(PG:7)
		at hru.j(PG:28)
		at hhn.c(PG:2)
		at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onConfigurationChanged(PG:12)
		at android.app.ActivityThread.performActivityConfigurationChanged(Unknown Source:145)
		at android.app.ActivityThread.performConfigurationChangedForActivity(Unknown Source:28)
		at android.app.ActivityThread.handleActivityConfigurationChanged(Unknown Source:273)
		at android.app.servertransaction.ActivityConfigurationChangeItem.execute(Unknown Source:10)
		at android.app.servertransaction.ActivityTransactionItem.execute(Unknown Source:4)
		at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
		at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
		at android.app.ActivityThread$H.handleMessage(Unknown Source:172)
		at android.os.Handler.dispatchMessage(Unknown Source:19)
		at android.os.Looper.loopOnce(Unknown Source:182)
		at android.os.Looper.loop(Unknown Source:82)
		at android.app.ActivityThread.main(Unknown Source:108)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
		at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
  ComposedException 2 :
	xno: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setVisibility(int)' on a null object reference
		at xgo.A(PG:1)
		at a.aO(PG:2)
		at afju.a(PG:23)
		at azpw.c(PG:3)
		at azpw.vE(PG:5)
		at ayyj.d(PG:5)
		at ayyj.vE(PG:2)
		at azrc.vM(PG:4)
		at azrc.b(PG:7)
		at azrd.vE(PG:6)
		at afob.f(PG:2)
		at afuo.E(PG:1)
		at kmc.c(PG:4)
		at kmc.a(PG:2)
		at kmf.pN(PG:3)
		at glg.c(PG:1)
		at kmf.pO(Unknown Source:0)
		at gwe.a(PG:44)
		at ayrt.vE(PG:2)
		at azfk.vE(PG:13)
		at azqt.c(PG:3)
		at azjl.e(PG:6)
		at azjq.f(PG:3)
		at azjq.vE(PG:2)
		at azjj.vE(PG:1)
		at azjd.vE(PG:2)
		at azfp.vE(PG:11)
		at azgm.vE(PG:3)
		at azfu.vE(PG:1)
		at azfs.d(PG:7)
		at azfr.vE(PG:7)
		at azhx.vE(PG:1)
		at ayzd.b(PG:14)
		at ayzi.vE(PG:6)
		at ayvq.vE(PG:4)
		at ayyx.vE(PG:1)
		at ayyu.d(PG:10)
		at ayyu.vE(PG:2)
		at azrc.vM(PG:4)
		at azrc.b(PG:7)
		at azrd.vE(PG:6)
		at mvy.h(PG:3)
		at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.w(PG:1)
		at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.x(PG:1)
		at ngq.o(PG:16)
		at ngq.s(PG:2)
		at ngq.c(PG:7)
		at hru.j(PG:28)
		at hhn.c(PG:2)
		at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onConfigurationChanged(PG:12)
		at android.app.ActivityThread.performActivityConfigurationChanged(Unknown Source:145)
		at android.app.ActivityThread.performConfigurationChangedForActivity(Unknown Source:28)
		at android.app.ActivityThread.handleActivityConfigurationChanged(Unknown Source:273)
		at android.app.servertransaction.ActivityConfigurationChangeItem.execute(Unknown Source:10)
		at android.app.servertransaction.ActivityTransactionItem.execute(Unknown Source:4)
		at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
		at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
		at android.app.ActivityThread$H.handleMessage(Unknown Source:172)
		at android.os.Handler.dispatchMessage(Unknown Source:19)
		at android.os.Looper.loopOnce(Unknown Source:182)
		at android.os.Looper.loop(Unknown Source:82)
		at android.app.ActivityThread.main(Unknown Source:108)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
		at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
	Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setVisibility(int)' on a null object reference
		at afmc.onAnimationStart(PG:1)
		at android.animation.Animator$AnimatorListener.onAnimationStart(Unknown Source:0)
		at android.animation.ValueAnimator.notifyStartListeners(Unknown Source:31)
		at android.animation.ValueAnimator.startAnimation(Unknown Source:44)
		at android.animation.ValueAnimator.start(Unknown Source:91)
		at android.animation.ValueAnimator.start(Unknown Source:1)
		at android.animation.ObjectAnimator.start(Unknown Source:7)
		at afmd.r(PG:12)
		at afmd.q(PG:1)
		at afmd.p(PG:1)
		at afmh.m(PG:3)
		at afmh.d(PG:4)
		at afje.a(PG:53)
		at azpw.vE(PG:2)
		at ayyj.d(PG:5)
		at ayyj.vE(PG:2)
		at azrc.vM(PG:4)
		at azrc.b(PG:7)
		at azrd.vE(PG:6)
		at afob.f(PG:2)
		at afuo.E(PG:1)
		at kmc.c(PG:4)
		at kmc.a(PG:2)
		at kmf.pN(PG:3)
		at glg.c(PG:1)
		at kmf.pO(Unknown Source:0)
		at gwe.a(PG:44)
		at ayrt.vE(PG:2)
		at azfk.vE(PG:13)
		at azqt.c(PG:3)
		at azjl.e(PG:6)
		at azjq.f(PG:3)
		at azjq.vE(PG:2)
		at azjj.vE(PG:1)
		at azjd.vE(PG:2)
		at azfp.vE(PG:11)
		at azgm.vE(PG:3)
		at azfu.vE(PG:1)
		at azfs.d(PG:7)
		at azfr.vE(PG:7)
		at azhx.vE(PG:1)
		at ayzd.b(PG:14)
		at ayzi.vE(PG:6)
		at ayvq.vE(PG:4)
		at ayyx.vE(PG:1)
		at ayyu.d(PG:10)
		at ayyu.vE(PG:2)
		at azrc.vM(PG:4)
		at azrc.b(PG:7)
		at azrd.vE(PG:6)
		at mvy.h(PG:3)
		at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.w(PG:1)
		at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.x(PG:1)
		at ngq.o(PG:16)
		at ngq.s(PG:2)
		at ngq.c(PG:7)
		at hru.j(PG:28)
		at hhn.c(PG:2)
		at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onConfigurationChanged(PG:12)
		at android.app.ActivityThread.performActivityConfigurationChanged(Unknown Source:145)
		at android.app.ActivityThread.performConfigurationChangedForActivity(Unknown Source:28)
		at android.app.ActivityThread.handleActivityConfigurationChanged(Unknown Source:273)
		at android.app.servertransaction.ActivityConfigurationChangeItem.execute(Unknown Source:10)
		at android.app.servertransaction.ActivityTransactionItem.execute(Unknown Source:4)
		at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
		at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
		at android.app.ActivityThread$H.handleMessage(Unknown Source:172)
		at android.os.Handler.dispatchMessage(Unknown Source:19)
		at android.os.Looper.loopOnce(Unknown Source:182)
		at android.os.Looper.loop(Unknown Source:82)
		at android.app.ActivityThread.main(Unknown Source:108)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
		at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
	Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
		at android.util.Log.getStackTraceString(Unknown Source:13)
		at ahqp.uncaughtException(PG:1)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
		at ayet.k(PG:9)
		at azpw.c(PG:5)
		at azpw.vE(PG:5)
		at ayyj.d(PG:5)
		at ayyj.vE(PG:2)
		at azrc.vM(PG:4)
		at azrc.b(PG:7)
		at azrd.vE(PG:6)
		at afob.f(PG:2)
		at afuo.E(PG:1)
		at kmc.c(PG:4)
		at kmc.a(PG:2)
		at kmf.pN(PG:3)
		at glg.c(PG:1)
		at kmf.pO(Unknown Source:0)
		at gwe.a(PG:44)
		at ayrt.vE(PG:2)
		at azfk.vE(PG:13)
		at azqt.c(PG:3)
		at azjl.e(PG:6)
		at azjq.f(PG:3)
		at azjq.vE(PG:2)
		at azjj.vE(PG:1)
		at azjd.vE(PG:2)
		at azfp.vE(PG:11)
		at azgm.vE(PG:3)
		at azfu.vE(PG:1)
		at azfs.d(PG:7)
		at azfr.vE(PG:7)
		at azhx.vE(PG:1)
		at ayzd.b(PG:14)
		at ayzi.vE(PG:6)
		at ayvq.vE(PG:4)
		at ayyx.vE(PG:1)
		at ayyu.d(PG:10)
		at ayyu.vE(PG:2)
		at azrc.vM(PG:4)
		at azrc.b(PG:7)
		at azrd.vE(PG:6)
		at mvy.h(PG:3)
		at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.w(PG:1)
		at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.x(PG:1)
		at ngq.o(PG:16)
		at ngq.s(PG:2)
		at ngq.c(PG:7)
		at hru.j(PG:28)
		at hhn.c(PG:2)
		at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onConfigurationChanged(PG:12)
		at android.app.ActivityThread.performActivityConfigurationChanged(Unknown Source:145)
		at android.app.ActivityThread.performConfigurationChangedForActivity(Unknown Source:28)
		at android.app.ActivityThread.handleActivityConfigurationChanged(Unknown Source:273)
		at android.app.servertransaction.ActivityConfigurationChangeItem.execute(Unknown Source:10)
		at android.app.servertransaction.ActivityTransactionItem.execute(Unknown Source:4)
		at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
		at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
		at android.app.ActivityThread$H.handleMessage(Unknown Source:172)
		at android.os.Handler.dispatchMessage(Unknown Source:19)
		at android.os.Looper.loopOnce(Unknown Source:182)
		at android.os.Looper.loop(Unknown Source:82)
		at android.app.ActivityThread.main(Unknown Source:108)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
		at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
```

### Device Environment

Android 13, miui 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by What-Zit-Tooya** [comment]
Works here, no crash. Same YouTube version & patched with cli

**Comment by 0frd** [comment]
My bad, i repatch it and now its working :)
