### ISSUE TITLE
bug: YouTube v18.43.45 crashing with patch v2.196.1

### ISSUE THREAD

**Issue by xd003** [inotia00/ReVanced_Extended#1680]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

v18.43.45

### Bug description

The YouTube app crashes as soon as i open it. I have used RVX Manager to patch YouTube v18.43.45 downloaded from apkmirror

### Steps to reproduce

The app crashes immediately after opening it

### Relevant log output

```shell
>> crash.log
FATAL EXCEPTION: firebase-installations-executor-2
Process: app.rvx.android.youtube, PID: 12976
java.lang.RuntimeException: Unable to find a default SSL provider.
	at com.google.android.libraries.stitch.sslguard.SslGuardSocketFactory.a(PG:8)
	at com.google.android.libraries.stitch.sslguard.SslGuardSocketFactory.createSocket(PG:6)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:185)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
	at akvq.g(PG:1)
	at akvq.b(PG:17)
	at akva.run(PG:19)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

>> dump.log
1699777909.185 10224 12976 13013 W WindDownApi: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3025)
1699777909.185 10224 12976 13013 W WindDownApi: 	at android.os.Parcel.createException(Parcel.java:3009)
1699777909.185 10224 12976 13013 W WindDownApi: 	at android.os.Parcel.readException(Parcel.java:2992)
1699777909.185 10224 12976 13013 W WindDownApi: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
1699777909.185 10224 12976 13013 W WindDownApi: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
1699777909.185 10224 12976 13013 W WindDownApi: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
1699777909.185 10224 12976 13013 W WindDownApi: 	at android.content.ContentResolver.call(ContentResolver.java:2488)
1699777909.185 10224 12976 13013 W WindDownApi: 	at android.content.ContentResolver.call(ContentResolver.java:2468)
1699777909.185 10224 12976 13013 W WindDownApi: 	at cjr.c(PG:3)
1699777909.185 10224 12976 13013 W WindDownApi: 	at fvp.a(PG:15)
1699777909.185 10224 12976 13013 W WindDownApi: 	at aykf.b(PG:1)
1699777909.185 10224 12976 13013 W WindDownApi: 	at ayls.run(PG:2)
1699777909.185 10224 12976 13013 W WindDownApi: 	at ajdd.run(PG:3)
1699777909.185 10224 12976 13013 W WindDownApi: 	at azhw.call(PG:2)
1699777909.185 10224 12976 13013 W WindDownApi: 	at akkc.a(PG:1)
1699777909.185 10224 12976 13013 W WindDownApi: 	at akjj.run(PG:4)
1699777909.185 10224 12976 13013 W WindDownApi: 	at akkd.run(PG:1)
1699777909.185 10224 12976 13013 W WindDownApi: 	at akda.run(PG:24)
1699777909.185 10224 12976 13013 W WindDownApi: 	at pzk.run(PG:40)
1699777909.185 10224 12976 13013 W WindDownApi: 	at java.lang.Thread.run(Thread.java:1012)
1699777909.185 10224 12976 13013 W WindDownApi: 	at qff.run(PG:5)
1699777909.196 10224 12976 13037 D CompatibilityChangeReporter: Compat change id reported: 183155436; UID 10224; state: ENABLED
1699777909.199 10224 12976 12976 W YT.mlplayer: Stayawake OFF
1699777909.203 10224 12976 12976 W YouTube : Suppressed bad viewport dimensions. Video quality may suffer!
1699777909.211 10224 12976 13158 I FA      : App measurement disabled by setAnalyticsCollectionEnabled(false)
1699777909.212 10224 12976 13158 I FA      : App measurement initialized, version: 82001
1699777909.212 10224 12976 13158 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
1699777909.212 10224 12976 13158 I FA      : To enable faster debug mode event logging run:
1699777909.212 10224 12976 13158 I FA      :   adb shell setprop debug.firebase.analytics.app app.rvx.android.youtube
1699777909.219 10224 12976 13161 D TrafficStats: tagSocket(101) with statsTag=0x8001, statsUid=-1
1699777909.223 10224 12976 13158 W GmsClient: unable to connect to service: com.google.android.gms.measurement.START on com.mgoogle.android.gms
1699777909.226 10224 12976 13161 W DynamiteModule: Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
1699777909.226 10224 12976 13161 W ProviderInstaller: Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
1699777909.232 10224 12976 13161 W ProviderInstaller: Failed to report request stats: null receiver
1699777909.233 10224 12976 13161 D GmsProviderInstaller: Initializing provider for app.rvx.android.youtube
1699777909.238 10224 12976 12976 W FA      : Service connection failed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
1699777909.241 10224 12976 13158 E FA      : Failed to get app instance id
1699777909.241 10224 12976 13158 E FA      : Failed to send default event parameters to service
1699777909.241 10224 12976 13158 E FA      : Failed to send measurementEnabled to service
1699777909.253 10224 12976 13161 W GmsProviderInstaller: Could not link conscrypt via default loader, trying manual loading
1699777909.259 10224 12976 13161 D GmsProviderInstaller: Can't load native library: lib/arm64-v8a/libconscrypt_gmscore_jni.so does not exist in /data/app/~~-VLur7VpoCrBmlH3lva6Ng==/com.mgoogle.android.gms-hL0PHaCldvgSMiLPfihiwA==/base.apk
1699777909.259 10224 12976 13161 D GmsProviderInstaller: Loading conscrypt_gmscore_jni from /data/user/0/app.rvx.android.youtube/cache/.gmscore/lib/arm64-v8a/libconscrypt_gmscore_jni.so
1699777909.260 10224 12976 13161 W GmsProviderInstaller: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/user/0/app.rvx.android.youtube/cache/.gmscore/lib/arm64-v8a/libconscrypt_gmscore_jni.so" not found
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at java.lang.Runtime.load0(Runtime.java:933)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at java.lang.System.load(System.java:1625)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.google.android.gms.common.security.ProviderInstallerImpl.loadConscryptDirect(ProviderInstallerImpl.java:148)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.google.android.gms.common.security.ProviderInstallerImpl.initProvider(ProviderInstallerImpl.java:120)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.google.android.gms.common.security.ProviderInstallerImpl.insertProvider(ProviderInstallerImpl.java:85)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at java.lang.reflect.Method.invoke(Native Method)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at pmn.b(PG:2)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at tpx.a(PG:13)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.google.android.libraries.stitch.sslguard.SslGuardSocketFactory.a(PG:2)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.google.android.libraries.stitch.sslguard.SslGuardSocketFactory.createSocket(PG:6)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:185)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at akvq.g(PG:1)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at akvq.b(PG:17)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at akva.run(PG:19)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
1699777909.260 10224 12976 13161 W GmsProviderInstaller: 	at java.lang.Thread.run(Thread.java:1012)
1699777909.263 10224 12976 13161 E SslGuardSocketFactory: [Ssl_Guard version 1.01(true), AndroidNSSP version 1.0(false), AndroidOpenSSL version 1.0(true), CertPathProvider version 1.0(false), AndroidKeyStoreBCWorkaround version 1.0(false), BC version 1.68(false), HarmonyJSSE version 1.0(false), AndroidKeyStore version 1.0(false), ]
1699777909.264 10224 12976 13011 W GmsClient: unable to connect to service: com.google.android.gms.clearcut.service.START on com.mgoogle.android.gms
1699777909.265 10224 12976 13161 E AndroidRuntime: FATAL EXCEPTION: firebase-installations-executor-2
1699777909.265 10224 12976 13161 E AndroidRuntime: Process: app.rvx.android.youtube, PID: 12976
1699777909.265 10224 12976 13161 E AndroidRuntime: java.lang.RuntimeException: Unable to find a default SSL provider.
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.google.android.libraries.stitch.sslguard.SslGuardSocketFactory.a(PG:8)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.google.android.libraries.stitch.sslguard.SslGuardSocketFactory.createSocket(PG:6)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:185)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at akvq.g(PG:1)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at akvq.b(PG:17)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at akva.run(PG:19)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
1699777909.265 10224 12976 13161 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
1699777909.281 10224 12976 13171 D TrafficStats: tagSocket(187) with statsTag=0x8001, statsUid=-1
1699777909.288 10224 12976 13171 W DynamiteModule: Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
```

### Device Environment

SDK: 33
PRODUCT_NAME: I2214
DEVICE_NAME: I2214
BOARD_NAME: k6895v1_64
SUPPORTED_ABIS: arm64-v8a, armeabi-v7a, armeabi
MANUFACTURER: vivo
BRAND: iQOO
MODEL: I2214

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by xd003** [comment]
Nvm, seems like something was wrong with my microg installation, resintalling latest microg has fixed the crash
