### ISSUE TITLE
bug: <The App suddenly started crashing>

### ISSUE THREAD

**Issue by NikunjKhangwal** [inotia00/ReVanced_Extended#1715]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 18.40.34

### Bug description

The app was working fine yesterday but it suddenly started crashing today for some reason. The app opens up fine and plays video for some time but then instantly crashes. (after like 20 seconds)

### Steps to reproduce

Looks like the app can't properly make connection with the server

### Relevant log output

```shell
FATAL EXCEPTION: firebase-installations-executor-2
Process: app.rvx.android.youtube, PID: 3248
java.lang.RuntimeException: Unable to find a default SSL provider.
	at com.google.android.libraries.stitch.sslguard.SslGuardSocketFactory.a(PG:8)
	at com.google.android.libraries.stitch.sslguard.SslGuardSocketFactory.createSocket(PG:6)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:185)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
	at akqt.g(PG:1)
	at akqt.c(PG:17)
	at akqe.run(PG:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

### Device Environment

Android 12, MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
Looks like it's the same as https://github.com/inotia00/ReVanced_Extended/issues/1680

Try reinstalling vanced microg and disabling battery optimizations for vanced microg so it can run in the background.

**Comment by NikunjKhangwal** [comment]
Battery optimization was already disabled. I didn't updated to patch 2.196. I'll try to reintsall microg and uldate it. Also I'm getting null pointer exception crash for .adservices as well if this information is relevant.

**Comment by inotia00** [comment]
Exclude patches one by one until the issue is not reproduced.
And please let me know which patch is the cause of the issue

**Comment by NikunjKhangwal** [comment]
Nevermind. This looks like a problem with my device itself and idk what's using causing it. It started with revanced but now I'm getting some crashes in play store and a system app as well
