### ISSUE TITLE
bug: Error while patching 18.45.41 with Overlay buttons

### ISSUE THREAD

**Issue by 123jjck** [inotia00/ReVanced_Extended#1717]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v18.45.41

### Bug description

Tried to patch the application

### Steps to reproduce

1. Include overlay buttons patch (probably any patch depends on `VideoIdPatch`)
2. Try to patch

### Relevant log output

```shell
- Device Info
ReVanced Manager: 1.15.1
Build: release
Model: SM-S911B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.45.41
Patches version: v2.199.1
Patches: Custom package name [Package name of YouTube: app.rvx.android.youtube, Package name of YouTube Music: app.rvx.android.apps.youtube.music], Custom seekbar color, Disable QUIC protocol, Disable shorts on startup, Enable external browser, Enable minimized playback, Enable old quality layout, Enable open links directly, Hide autoplay button, Hide channel watermark, Hide comment component, Hide crowdfunding box, Hide floating microphone, Hide general ads, Hide music button, Hide shorts components, Hide suggested video overlay, Hide video ads, MicroG support, Overlay buttons [Outline icons: false], Return YouTube Dislike, Sanitize sharing links, Settings, SponsorBlock [Outline icons: false], Spoof app version, Spoof player parameters, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Translations

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Custom package name succeeded
Custom seekbar color succeeded
Disable QUIC protocol succeeded
Disable shorts on startup succeeded
Enable external browser succeeded
Enable minimized playback succeeded
Enable old quality layout succeeded
Enable open links directly succeeded
Hide autoplay button succeeded
Hide channel watermark succeeded
Hide comment component succeeded
Hide crowdfunding box succeeded
Hide floating microphone succeeded
Hide general ads succeeded
Hide music button succeeded
Hide shorts components succeeded
Hide suggested video overlay succeeded
Hide video ads succeeded
MicroG support succeeded
Overlay buttons failed: app.revanced.patcher.patch.PatchException: 'Overlay buttons' depends on 'VideoIdPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Failed to resolve OrganicPlaybackContextModelFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:34)
	at app.revanced.patches.youtube.utils.videoid.general.VideoIdPatch.execute(VideoIdPatch.kt:112)
	at app.revanced.patches.youtube.utils.videoid.general.VideoIdPatch.execute(VideoIdPatch.kt:30)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Return YouTube Dislike failed: app.revanced.patcher.patch.PatchException: 'Return YouTube Dislike' depends on 'VideoIdPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: 'VideoIdPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:150)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Sanitize sharing links succeeded
SponsorBlock failed: app.revanced.patcher.patch.PatchException: 'SponsorBlock' depends on 'SponsorBlockBytecodePatch' that raised an exception:
app.revanced.patcher.patch.PatchException: 'SponsorBlockBytecodePatch' depends on 'VideoIdPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: 'VideoIdPatch' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:150)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:301)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Spoof app version succeeded
Spoof player parameters succeeded
Theme succeeded
Translations succeeded
Settings succeeded
Compiling patched dex files
Compiled classes.dex
Compiled classes2.dex
Compiled classes3.dex
Compiled classes4.dex
Compiled classes5.dex
Compiled classes6.dex
Compiled classes7.dex
Compiled classes8.dex
Compiling modified resources
```

### Device Environment

Android 14, One UI 6.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [x] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
This is a valid issue
I can't wait for the next release until this issue is fixed, so I just replaced the files in releases 

If you are using the RVX Manager, delete the cache and force close it
And re-launch RVX Manager and patch again 👍

**Comment by inotia00** [comment]
I know this is an off-topic...

- You have patched through RVX Manager yourself ✅
- You provided an accurate log of the issue ✅

Thanks to this, I was able to immediately fix issues

If others provide specific logs when reporting issues like you, I can immediately fix issues
