### ISSUE TITLE
bug: error while patching

### ISSUE THREAD

**Issue by Cantthinkofan** [inotia00/ReVanced_Extended#1774]
### Type

Error while patching

### Tools used

CLI

### Application

Youtube: 18.46.43
CLI: 4.3.1

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/152628958/4e057fed-50ff-46bb-bd70-f75c27d7d208

### Error logs

```shell
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: Disable landscape mode excluded 
INFO: Hide animated button background excluded 
INFO: Custom branding icon MMT excluded 
INFO: Custom branding icon Revancify Blue excluded 
INFO: Custom branding icon Revancify Red excluded 
INFO: Custom branding name YouTube excluded 
INFO: Hide double tap overlay filter excluded 
INFO: MaterialYou excluded 
INFO: Enable debug logging excluded 
INFO: Hide player button background excluded 
INFO: Setting patch options 
INFO: Merging integrations 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Add splash animation succeeded 
INFO: Alternative thumbnails succeeded 
INFO: Ambient mode switch succeeded 
INFO: Append time stamps information succeeded 
INFO: Change homepage succeeded 
INFO: Custom double tap length succeeded 
INFO: Custom package name succeeded 
INFO: Custom playback speed succeeded 
INFO: Custom player overlay opacity succeeded 
INFO: Custom seekbar color succeeded 
INFO: Default playback speed succeeded 
INFO: Default video quality succeeded 
INFO: Disable HDR video succeeded 
INFO: Disable QUIC protocol succeeded 
INFO: Disable auto captions succeeded 
INFO: Disable haptic feedback succeeded 
INFO: Disable pip notification succeeded 
INFO: Disable shorts on startup succeeded 
INFO: Disable speed overlay succeeded 
INFO: Enable compact controls overlay succeeded 
INFO: Enable external browser succeeded 
INFO: Enable gradient loading screen succeeded 
INFO: Enable language switch succeeded 
INFO: Enable minimized playback succeeded 
INFO: Enable music search succeeded 
INFO: Enable new splash animation succeeded 
INFO: Enable new thumbnail preview succeeded 
INFO: Enable old quality layout succeeded 
INFO: Enable open links directly succeeded 
INFO: Enable seekbar tapping succeeded 
INFO: Enable tablet mini player succeeded 
INFO: Enable tablet navigation bar succeeded 
INFO: Enable wide search bar succeeded 
INFO: Force OPUS codec succeeded 
INFO: Force fullscreen succeeded 
INFO: Force video codec succeeded 
INFO: Hide account menu succeeded 
INFO: Hide auto player popup panels succeeded 
INFO: Hide autoplay button succeeded 
INFO: Hide autoplay preview succeeded 
INFO: Hide button container succeeded 
INFO: Hide captions button succeeded 
INFO: Hide cast button succeeded 
INFO: Hide category bar succeeded 
INFO: Hide channel avatar section succeeded 
INFO: Hide channel profile components succeeded 
INFO: Hide channel watermark succeeded 
INFO: Hide collapse button succeeded 
INFO: Hide comment component succeeded 
INFO: Hide crowdfunding box succeeded 
INFO: Hide description components succeeded 
INFO: Hide end screen cards succeeded 
INFO: Hide end screen overlay succeeded 
INFO: Hide feed flyout panel succeeded 
INFO: Hide filmstrip overlay succeeded 
INFO: Hide floating microphone succeeded 
INFO: Hide fullscreen panels succeeded 
INFO: Hide general ads succeeded 
INFO: Hide handle succeeded 
INFO: Hide info cards succeeded 
INFO: Hide latest videos button succeeded 
INFO: Hide layout components succeeded 
INFO: Hide load more button succeeded 
INFO: Hide mix playlists succeeded 
INFO: Hide music button succeeded 
INFO: Hide navigation buttons succeeded 
INFO: Hide navigation label succeeded 
INFO: Hide player flyout panel succeeded 
INFO: Hide previous next button succeeded 
INFO: Hide search term thumbnail succeeded 
INFO: Hide seek message succeeded 
INFO: Hide seekbar succeeded 
INFO: Hide shorts components succeeded 
INFO: Hide snack bar succeeded 
INFO: Hide suggested actions succeeded 
INFO: Hide suggested video overlay succeeded 
INFO: Hide suggestions shelf succeeded 
INFO: Hide time stamp succeeded 
INFO: Hide toolbar button succeeded 
INFO: Hide tooltip content succeeded 
INFO: Hide trending searches succeeded 
INFO: Hide video ads succeeded 
INFO: Hide voice search button succeeded 
INFO: Layout switch succeeded 
INFO: MicroG support succeeded 
INFO: Overlay buttons succeeded 
INFO: Premium heading succeeded 
INFO: Quick actions components succeeded 
INFO: Return YouTube Dislike succeeded 
INFO: Sanitize sharing links succeeded 
INFO: Shorts outline button succeeded 
INFO: SponsorBlock succeeded 
INFO: Spoof app version succeeded 
INFO: Spoof device dimensions succeeded 
INFO: Spoof player parameters succeeded 
INFO: Swipe controls succeeded 
INFO: Theme succeeded 
INFO: Translations succeeded 
INFO: Settings succeeded 
INFO: Compiling patched dex files 
INFO: Compiled classes.dex 
INFO: Compiled classes2.dex 
INFO: Compiled classes3.dex 
INFO: Compiled classes4.dex 
INFO: Compiled classes5.dex 
INFO: Compiled classes6.dex 
INFO: Compiled classes7.dex 
INFO: Compiled classes8.dex 
INFO: Compiling modified resources 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec: [./aapt2, compile, --dir, /data/data/com.termux/files/home/revancify-data/apps/YouTube-18.46.43/base-Revanced-Extended-resource-cache/res, --legacy, -o, /data/data/com.termux/files/home/revancify-data/apps/YouTube-18.46.43/base-Revanced-Extended-resource-cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:313)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec: [./aapt2, compile, --dir, /data/data/com.termux/files/home/revancify-data/apps/YouTube-18.46.43/base-Revanced-Extended-resource-cache/res, --legacy, -o, /data/data/com.termux/files/home/revancify-data/apps/YouTube-18.46.43/base-Revanced-Extended-resource-cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:107)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
	... 13 more
Caused by: java.io.IOException: Cannot run program "./aapt2": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at brut.util.OS.exec(OS.java:97)
	... 14 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 16 more



Rooted: false
Arch: arm64-v8a
App: YouTube v18.46.43
CLI: inotia00-cli-v4.3.1.jar
Patches: inotia00-patches-v2.201.12.jar
Integrations: inotia00-integrations-v0.124.12.apk
Patches argument: -i Add splash animation -i Alternative thumbnails -i Ambient mode switch -i Append time stamps information -i Change homepage -i Custom double tap length -i Custom package name -i Custom playback speed -i Custom player overlay opacity -i Custom seekbar color -i Default playback speed -i Default video quality -i Disable HDR video -i Disable QUIC protocol -i Disable auto captions -i Disable haptic feedback -i Disable pip notification -i Disable shorts on startup -i Disable speed overlay -i Enable compact controls overlay -i Enable external browser -i Enable gradient loading screen -i Enable language switch -i Enable minimized playback -i Enable music search -i Enable new splash animation -i Enable new thumbnail preview -i Enable old quality layout -i Enable open links directly -i Enable seekbar tapping -i Enable tablet mini player -i Enable tablet navigation bar -i Enable wide search bar -i Force OPUS codec -i Force fullscreen -i Force video codec -i Hide account menu -i Hide auto player popup panels -i Hide autoplay button -i Hide autoplay preview -i Hide button container -i Hide captions button -i Hide cast button -i Hide category bar -i Hide channel avatar section -i Hide channel profile components -i Hide channel watermark -i Hide collapse button -i Hide comment component -i Hide crowdfunding box -i Hide description components -i Hide end screen cards -i Hide end screen overlay -i Hide feed flyout panel -i Hide filmstrip overlay -i Hide floating microphone -i Hide fullscreen panels -i Hide general ads -i Hide handle -i Hide info cards -i Hide latest videos button -i Hide layout components -i Hide load more button -i Hide mix playlists -i Hide music button -i Hide navigation buttons -i Hide navigation label -i Hide player flyout panel -i Hide previous next button -i Hide search term thumbnail -i Hide seek message -i Hide seekbar -i Hide shorts components -i Hide snack bar -i Hide suggested actions -i Hide suggested video overlay -i Hide suggestions shelf -i Hide time stamp -i Hide toolbar button -i Hide tooltip content -i Hide trending searches -i Hide video ads -i Hide voice search button -i Layout switch -i MicroG support -i Overlay buttons -i Premium heading -i Quick actions components -i Return YouTube Dislike -i Sanitize sharing links -i Settings -i Shorts outline button -i SponsorBlock -i Spoof app version -i Spoof device dimensions -i Spoof player parameters -i Swipe controls -i Theme -i Translations
```

### Solution

Nothing

### Device Environment

Android 13 funtouch 
Termux monet

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Adity1243** [comment]
You must be used root medhod

**Comment by Cantthinkofan** [comment]
What?

> You must be used root medhod.

**Comment by Cantthinkofan** [comment]
I must use root method?

> You must be used root medhod.

**Comment by Adity1243** [comment]
> I must use root method?
> 
> > You must be used root medhod.

I am saying  you must be used root medhod your device rooted?

**Comment by Cantthinkofan** [comment]
No its not

> > I must use root method?
> > > You must be used root medhod.
> 
> I am saying you must be used root medhod, your device rooted?
