### ISSUE TITLE
bug: "Enable wide search bar" & "Hide search term thumbnail" failed with YT 18.44.41

### ISSUE THREAD

**Issue by RVXArchive** [inotia00/ReVanced_Extended#1785]
### Type

Error while patching

### Tools used

Revancify

### Application

YouTube 18.44.41

### Bug description

Using Revancify, YT 18.44.41, Patches v2.202.1

These patches failed:
"Enable wide search bar"
"Hide search term thumbnail"

### Error logs

```shell
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: Disable landscape mode excluded 
INFO: Enable music search excluded 
INFO: Hide animated button background excluded 
INFO: Custom branding icon MMT excluded 
INFO: Custom branding icon Revancify Red excluded 
INFO: Custom branding name YouTube excluded 
INFO: Hide double tap overlay filter excluded 
INFO: Premium heading excluded 
INFO: MaterialYou excluded 
INFO: Add splash animation excluded 
INFO: Hide voice search button excluded 
INFO: Enable debug logging excluded 
INFO: Hide player button background excluded 
INFO: Shorts outline button excluded 
INFO: Setting patch options 
INFO: Merging integrations 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Alternative thumbnails succeeded 
INFO: Ambient mode switch succeeded 
INFO: Append time stamps information succeeded 
INFO: Change homepage succeeded 
INFO: Custom branding icon Revancify Blue succeeded 
INFO: Custom double tap length succeeded 
INFO: Custom package name succeeded 
INFO: Custom playback speed succeeded 
INFO: Custom player overlay opacity succeeded 
INFO: Custom seekbar color succeeded 
INFO: Default playback speed succeeded 
INFO: Default video quality succeeded 
INFO: Disable HDR video succeeded 
INFO: Disable QUIC protocol succeeded 
INFO: Disable auto captions succeeded 
INFO: Disable haptic feedback succeeded 
INFO: Disable pip notification succeeded 
INFO: Disable shorts on startup succeeded 
INFO: Disable speed overlay succeeded 
INFO: Enable compact controls overlay succeeded 
INFO: Enable external browser succeeded 
INFO: Enable gradient loading screen succeeded 
INFO: Enable language switch succeeded 
INFO: Enable minimized playback succeeded 
INFO: Enable new splash animation succeeded 
INFO: Enable new thumbnail preview succeeded 
INFO: Enable old quality layout succeeded 
INFO: Enable open links directly succeeded 
INFO: Enable seekbar tapping succeeded 
INFO: Enable tablet mini player succeeded 
INFO: Enable tablet navigation bar succeeded 
SEVERE: Enable wide search bar failed:
app.revanced.patcher.patch.PatchException: Failed to resolve CreateSearchSuggestionsFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:34)
	at app.revanced.patches.youtube.general.widesearchbar.WideSearchBarPatch.execute(WideSearchBarPatch.kt:68)
	at app.revanced.patches.youtube.general.widesearchbar.WideSearchBarPatch.execute(WideSearchBarPatch.kt:22)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
 
INFO: Force OPUS codec succeeded 
INFO: Force fullscreen succeeded 
INFO: Force video codec succeeded 
INFO: Hide account menu succeeded 
INFO: Hide auto player popup panels succeeded 
INFO: Hide autoplay button succeeded 
INFO: Hide autoplay preview succeeded 
INFO: Hide button container succeeded 
INFO: Hide captions button succeeded 
INFO: Hide cast button succeeded 
INFO: Hide category bar succeeded 
INFO: Hide channel avatar section succeeded 
INFO: Hide channel profile components succeeded 
INFO: Hide channel watermark succeeded 
INFO: Hide collapse button succeeded 
INFO: Hide comment component succeeded 
INFO: Hide crowdfunding box succeeded 
INFO: Hide description components succeeded 
INFO: Hide end screen cards succeeded 
INFO: Hide end screen overlay succeeded 
INFO: Hide feed flyout panel succeeded 
INFO: Hide filmstrip overlay succeeded 
INFO: Hide floating microphone succeeded 
INFO: Hide fullscreen panels succeeded 
INFO: Hide general ads succeeded 
INFO: Hide handle succeeded 
INFO: Hide info cards succeeded 
INFO: Hide latest videos button succeeded 
INFO: Hide layout components succeeded 
INFO: Hide load more button succeeded 
INFO: Hide mix playlists succeeded 
INFO: Hide music button succeeded 
INFO: Hide navigation buttons succeeded 
INFO: Hide navigation label succeeded 
INFO: Hide player flyout panel succeeded 
INFO: Hide previous next button succeeded 
SEVERE: Hide search term thumbnail failed:
app.revanced.patcher.patch.PatchException: Failed to resolve CreateSearchSuggestionsFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:34)
	at app.revanced.patches.youtube.general.searchterm.SearchTermThumbnailPatch.execute(SearchTermThumbnailPatch.kt:96)
	at app.revanced.patches.youtube.general.searchterm.SearchTermThumbnailPatch.execute(SearchTermThumbnailPatch.kt:22)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
 
INFO: Hide seek message succeeded 
INFO: Hide seekbar succeeded 
INFO: Hide shorts components succeeded 
INFO: Hide snack bar succeeded 
INFO: Hide suggested actions succeeded 
INFO: Hide suggested video overlay succeeded 
INFO: Hide suggestions shelf succeeded 
INFO: Hide time stamp succeeded 
INFO: Hide toolbar button succeeded 
INFO: Hide tooltip content succeeded 
INFO: Hide trending searches succeeded 
INFO: Hide video ads succeeded 
INFO: Layout switch succeeded 
INFO: MicroG support succeeded 
INFO: Overlay buttons succeeded 
INFO: Quick actions components succeeded 
INFO: Return YouTube Dislike succeeded 
INFO: Sanitize sharing links succeeded 
INFO: SponsorBlock succeeded 
INFO: Spoof app version succeeded 
INFO: Spoof device dimensions succeeded 
INFO: Spoof player parameters succeeded 
INFO: Swipe controls succeeded 
INFO: Theme succeeded 
INFO: Translations succeeded 
INFO: Settings succeeded 
INFO: Compiling patched dex files 
INFO: Compiled classes.dex 
INFO: Compiled classes2.dex 
INFO: Compiled classes3.dex 
INFO: Compiled classes4.dex 
INFO: Compiled classes5.dex 
INFO: Compiled classes6.dex 
INFO: Compiled classes7.dex 
INFO: Compiled classes8.dex 
INFO: Compiling modified resources 
INFO: Aligning base.apk 
INFO: Signing base.apk 
INFO: Purging temporary files 
INFO: Purged resource cache directory 



Rooted: false
Arch: arm64-v8a
App: YouTube v18.44.41
CLI: inotia00-cli-v4.3.1.jar
Patches: inotia00-patches-v2.202.1.jar
Integrations: inotia00-integrations-v0.125.1.apk
Patches argument: -i Alternative thumbnails -i Ambient mode switch -i Append time stamps information -i Change homepage -i Custom branding icon Revancify Blue -i Custom double tap length -i Custom package name -i Custom playback speed -i Custom player overlay opacity -i Custom seekbar color -i Default playback speed -i Default video quality -i Disable HDR video -i Disable QUIC protocol -i Disable auto captions -i Disable haptic feedback -i Disable pip notification -i Disable shorts on startup -i Disable speed overlay -i Enable compact controls overlay -i Enable external browser -i Enable gradient loading screen -i Enable language switch -i Enable minimized playback -i Enable new splash animation -i Enable new thumbnail preview -i Enable old quality layout -i Enable open links directly -i Enable seekbar tapping -i Enable tablet mini player -i Enable tablet navigation bar -i Enable wide search bar -i Force OPUS codec -i Force fullscreen -i Force video codec -i Hide account menu -i Hide auto player popup panels -i Hide autoplay button -i Hide autoplay preview -i Hide button container -i Hide captions button -i Hide cast button -i Hide category bar -i Hide channel avatar section -i Hide channel profile components -i Hide channel watermark -i Hide collapse button -i Hide comment component -i Hide crowdfunding box -i Hide description components -i Hide end screen cards -i Hide end screen overlay -i Hide feed flyout panel -i Hide filmstrip overlay -i Hide floating microphone -i Hide fullscreen panels -i Hide general ads -i Hide handle -i Hide info cards -i Hide latest videos button -i Hide layout components -i Hide load more button -i Hide mix playlists -i Hide music button -i Hide navigation buttons -i Hide navigation label -i Hide player flyout panel -i Hide previous next button -i Hide search term thumbnail -i Hide seek message -i Hide seekbar -i Hide shorts components -i Hide snack bar -i Hide suggested actions -i Hide suggested video overlay -i Hide suggestions shelf -i Hide time stamp -i Hide toolbar button -i Hide tooltip content -i Hide trending searches -i Hide video ads -i Layout switch -i MicroG support -i Overlay buttons -i Quick actions components -i Return YouTube Dislike -i Sanitize sharing links -i Settings -i SponsorBlock -i Spoof app version -i Spoof device dimensions -i Spoof player parameters -i Swipe controls -i Theme -i Translations
```

### Device Environment

Android 11, ColorOS V11.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The supported versions of the current patch are YouTube v18.25.40 ~ v18.46.43

So this is a valid issue and will be fixed in the next release

**Comment by RVXArchive** [comment]
Thanks for the fix.
