### ISSUE TITLE
bug: (YouTube/Custom branding icon YouTube) patch not working

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1795]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube 18.45.43

### Bug description

When patching YouTube normally with `Custom branding icon YouTube` patch and setting patch option to MMT, it gives this error.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: 2107113SI
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.45.43
Patches version: v2.203.1
Patches added: Add splash animation, Alternative thumbnails, Ambient mode switch, Append time stamps information, Change homepage, Custom branding icon YouTube [App icon: mmt], Custom branding name YouTube [App name: YouTube], Custom double tap length [Double-tap to seek Values: 3, 5, 10, 15, 20, 30, 60, 120, 180], Custom package name [Package name of YouTube: app.rvx.android.youtube, Package name of YouTube Music: app.rvx.android.apps.youtube.music], Custom playback speed, Custom player overlay opacity, Custom seekbar color, Default playback speed, Default video quality, Disable HDR video, Disable QUIC protocol, Disable auto captions, Disable haptic feedback, Disable landscape mode, Disable pip notification, Disable shorts on startup, Disable speed overlay, Enable compact controls overlay, Enable debug logging, Enable external browser, Enable gradient loading screen, Enable language switch, Enable minimized playback, Enable music search, Enable new splash animation, Enable new thumbnail preview, Enable old quality layout, Enable open links directly, Enable seekbar tapping, Enable tablet mini player, Enable tablet navigation bar, Enable wide search bar, Force OPUS codec, Force fullscreen, Force video codec, Hide account menu, Hide animated button background, Hide auto player popup panels, Hide autoplay button, Hide autoplay preview, Hide button container, Hide captions button, Hide cast button, Hide category bar, Hide channel avatar section, Hide channel profile components, Hide channel watermark, Hide collapse button, Hide comment component, Hide crowdfunding box, Hide description components, Hide double tap overlay filter, Hide end screen cards, Hide end screen overlay, Hide feed flyout panel, Hide filmstrip overlay, Hide floating microphone, Hide fullscreen panels, Hide general ads, Hide handle, Hide info cards, Hide latest videos button, Hide layout components, Hide load more button, Hide mix playlists, Hide music button, Hide navigation buttons, Hide navigation label, Hide player button background, Hide player flyout panel, Hide previous next button, Hide search term thumbnail, Hide seek message, Hide seekbar, Hide shorts components, Hide snack bar, Hide suggested actions, Hide suggested video overlay, Hide suggestions shelf, Hide time stamp, Hide toolbar button, Hide tooltip content, Hide trending searches, Hide video ads, Hide voice search button, Layout switch, MaterialYou, MicroG support, Overlay buttons [Outline icons: true], Premium heading [Use premium heading: true], Quick actions components, Return YouTube Dislike, Sanitize sharing links, Settings, Shorts outline button, SponsorBlock [Outline icons: true], Spoof app version, Spoof device dimensions, Spoof player parameters, Swipe controls, Theme [Dark theme background color: #FF181825, Light theme background color: #FFE6E9EF], Translations
Patches removed: Custom package name [Package name of YouTube: app.rvx.android.youtube, Package name of YouTube Music: app.rvx.android.apps.youtube.music], Hide general ads, Alternative thumbnails, Hide button container, Hide comment component, Hide feed flyout panel, Enable old quality layout, Hide player flyout panel, Hide autoplay preview, Enable compact controls overlay, Hide end screen overlay, Force fullscreen, Hide fullscreen panels, Quick actions components, Hide account menu, Disable auto captions, Hide auto player popup panels, Hide category bar, Hide channel avatar section, Hide crowdfunding box, Hide channel profile components, Hide description components, Hide floating microphone, Hide handle, Hide latest videos button, Hide layout components, Enable gradient loading screen, Hide load more button, Hide mix playlists, Hide search term thumbnail, Hide snack bar, Hide suggestions shelf, Enable tablet mini player, Hide toolbar button, Hide trending searches, Enable wide search bar, Custom branding icon YouTube [App icon: mmt], Custom branding name YouTube [App name: YouTube], Custom double tap length [Double-tap to seek Values: 3, 5, 10, 15, 20, 30, 60, 120, 180], Disable pip notification, Theme [Dark theme background color: #FF181825, Light theme background color: #FFE6E9EF], Hide tooltip content, Ambient mode switch, Force video codec, Enable external browser, Enable language switch, Layout switch, Enable minimized playback, Enable open links directly, Disable QUIC protocol, Enable new splash animation, Spoof device dimensions, Change homepage, Hide navigation label, Hide navigation buttons, Enable tablet navigation bar, Overlay buttons [Outline icons: true], Hide autoplay button, Hide captions button, Hide cast button, Hide collapse button, Hide end screen cards, Hide filmstrip overlay, Disable haptic feedback, Hide info cards, Hide music button, Custom player overlay opacity, Hide previous next button, Hide seek message, Disable speed overlay, Hide suggested actions, Hide suggested video overlay, Hide channel watermark, Append time stamps information, Custom seekbar color, Hide seekbar, Enable seekbar tapping, Enable new thumbnail preview, Hide time stamp, Hide shorts components, Disable shorts on startup, Swipe controls, Spoof player parameters, MicroG support, Return YouTube Dislike, SponsorBlock [Outline icons: true], Disable HDR video, Default video quality, Default playback speed, Hide video ads, Force OPUS codec, Spoof app version, Sanitize sharing links, Translations, Settings, Custom playback speed
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 106 patches
Custom branding icon YouTube failed: app.revanced.patcher.patch.PatchException: mmt/mipmap-xxxhdpi/adaptiveproduct_youtube_background_color_108.png: open failed: ENOENT (No such file or directory)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:185)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.FileNotFoundException: mmt/mipmap-xxxhdpi/adaptiveproduct_youtube_background_color_108.png: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:63)
	at app.revanced.patches.youtube.layout.branding.icon.CustomBrandingIconPatch.execute(CustomBrandingIconPatch.kt:125)
	at app.revanced.patches.youtube.layout.branding.icon.CustomBrandingIconPatch.execute(CustomBrandingIconPatch.kt:17)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177)
	... 18 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8139)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 23 more
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched
```

### Solution

Fix said failed patch

### Additional context

N/A

### Device Environment

Android 13 MIUI 14.0.4

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
I realized that it works when the type is set to custom and the name of the icon is typed in the text field. Only the presets don't work.

Here is an image demonstration:

![photostudio_1701821526995.jpg](https://github.com/inotia00/ReVanced_Extended/assets/84587632/30b5bb4b-c216-48b6-9623-e70ea5723aa6)

**Comment by Rairof** [comment]
I didn't used custom value as I'm not aware on how to use it so didn't checked it. Thank you

**Comment by inotia00** [comment]
In the next release, I will change it so that similar values are recognized as valid values

example)
`Revancify Blue`, `revancify_blue`, `ReVancify_blue`, `revancify Blue`
→ All are recognized as valid values

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.203.2](https://github.com/inotia00/revanced-patches/releases/tag/v2.203.2)

**Comment by Rairof** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1795#issuecomment-1842116241
It works now but partially, in the app launch screen and on top icon header, it just shows the normal official icon now unlike previously when you get the custom icon on both launching screen and on top header.
![Screenshot_2023-12-06-20-29-48-304_app rvx android apps youtube music-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/7d0ab6cb-0e43-47c9-9419-90d08f15747d)
![Screenshot_2023-12-06-20-30-05-896_app rvx android apps youtube music-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/4bd2ff28-d3d7-491e-8d02-0094d4f341f7)
![Screenshot_2023-12-06-20-33-03-881_com miui home-edit](https://github.com/inotia00/ReVanced_Extended/assets/107706560/e9220a57-fee5-4fd1-8094-7559c4572bc1)

**Comment by NormTurtle** [comment]
@inotia00 is there any way to get icons such as revanced old like
![imageREvanced](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Farchive.org%2Fdownload%2Fgithub.com-ReVancedTeam-revanced-patcher_-_2022-03-24_22-38-47%2Fcover.jpg&f=1&nofb=1&ipt=9c6cba84c61dce4d91a9a4bf98a254be02deb752556c5d1b18683d486a62c3c6&ipo=images)

**Comment by KobeW50** [comment]
> It works now but partially, in the app launch screen and on top icon header, it just shows the normal official icon now unlike previously when you get the custom icon on both launching screen and on top header.

https://github.com/inotia00/ReVanced_Extended/issues/1797

**Comment by Rairof** [comment]
Ohk thx
