### ISSUE TITLE
bug(YouTube Music/GmsCore support): can't share the stories to Facebook, Instagram and Snapchat

### ISSUE THREAD

**Issue by djlivooo** [inotia00/ReVanced_Extended#1830]
### Type

Other

### Tools used

RVX Manager

### Application

Youtube Music 6.31.55

### Bug description

I can't share songs via Instagram Stories. When I try to send it, the option appears, I hit that option, it loads, but does nothing. It stays there in YT Music. In the original app this error does not happen. Is there a solution?

https://github.com/inotia00/ReVanced_Extended/assets/98977517/8fc76f1e-6b0d-4698-9046-e1befb983856

### Error logs

```
Unable to create share intent.
java.lang.SecurityException: UID 10413 does not have permission to content://app.rvx.android.youtube.fileprovider/story_share_files/sticker.png [user 0]
 at android.os.Parcel.createException(Parcel.java:2088)
 at android.os.Parcel.readException(Parcel.java:2056)
 at android.os.Parcel.readException(Parcel.java:2004)
 at android.app.IActivityManager$Stub$Proxy.grantUriPermission(IActivityManager.java:6689)
 at android.app.ContextImpl.grantUriPermission(ContextImpl.java:2040)
 at android.content.ContextWrapper.grantUriPermission(ContextWrapper.java:819)
 at android.content.ContextWrapper.grantUriPermission(ContextWrapper.java:819)
 at aqnp.b(PG:34)
 at irh.c(PG:2)
 at afyf.c(PG:66)
 at aqnv.d(PG:16)
 at aqns.a(PG:1)
 at abvq.ob(PG:3)
 at asvd.ob(PG:3)
 at auet.run(PG:6)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:237)
 at android.app.ActivityThread.main(ActivityThread.java:8154)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: android.os.RemoteException: Remote stack trace:
 at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermission(UriGrantsManagerService.java:1202)
 at com.android.server.uri.UriGrantsManagerService.grantUriPermission(UriGrantsManagerService.java:771)
 at com.android.server.uri.UriGrantsManagerService$LocalService.grantUriPermission(UriGrantsManagerService.java:1340)
 at com.android.server.am.ActivityManagerService.grantUriPermission(ActivityManagerService.java:7835)
 at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2979)
```

### Device Environment

Android 12

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.206.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.206.1)

**Comment by djlivooo** [comment]
> fixed in [revanced-patches-v2.206.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.206.1)

Thank you so much inotia

**Comment by inotia00** [comment]
Reopened as it is a valid issue since https://github.com/inotia00/revanced-patches/pull/57

**Comment by inotia00** [comment]
fixed in [revanced-patches-v4.14.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.1)

**Comment by Kevin102000k** [comment]
how do i use this patch ,can you give a detailed tutorial and which app to use (revanced OR your RVX manager) ive been scratching my head on how to use it to share music thx in advance

**Comment by inotia00** [comment]
https://github.com/ReVanced-Extended-Community/Community-Guides/blob/main/community-wiki/guide-for-beginners.md

https://github.com/inotia00/revanced-documentation/blob/main/docs/rvx-manager.md
