### ISSUE TITLE
bug:(YouTube Music) ```Enable old layout``` patch fail

### ISSUE THREAD

**Issue by Rairof** [inotia00/ReVanced_Extended#1862]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube Music 6.31.55

### Bug description

Patch fails to be patched

### Error logs

```shell
- Device Info
ReVanced Manager: 1.18.1
Model: 2107113SI
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.youtube.music v6.31.55 (Suggested: Any)
Patches version: v2.208.1
Patches added: Enable debug logging, Enable old player layout, Hide voice search button, Replace cast button
Patches removed: None
Default patch options changed: Custom branding icon YouTube Music [App icon: mmt], Custom branding name YouTube Music [App name in notification panel: YouTube Music, App name in launcher: YouTube Music]

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Remove unused library: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 59 patches
Enable old player layout failed: app.revanced.patcher.patch.PatchException: This version is not supported. Please use YT Music 6.29.58 or earlier.
	at app.revanced.patches.music.player.oldplayerlayout.OldPlayerLayoutPatch.execute(OldPlayerLayoutPatch.kt:37)
	at app.revanced.patches.music.player.oldplayerlayout.OldPlayerLayoutPatch.execute(OldPlayerLayoutPatch.kt:14)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:345)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$37(MainActivity.kt:344)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$v-ELoclvC6W1vrKGstBtHifiD5Q(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:26)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched APK
```

### Solution

Worked previously on same YouTube music version but not anymore.

### Additional context

I'm aware for the patch being deprecated on versions 6.31.55+ but it used to work on 6.31.55 on previous patch versions and integrations, not anymore.

### Device Environment

Android 13 MIUI 14.0.7

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Rairof** [comment]
Or maybe I missed some important note somewhere, help would be appreciated.

**Comment by girshcatt** [comment]
Since the patch is depricated for 6.31.55+ it is officially incompatible with 6.31.55+

**Comment by inotia00** [comment]
error log says everything

```
This version is not supported. Please use YT Music 6.29.58 or earlier. 
```

**Comment by Rairof** [comment]
I thought it meant for versions higher than 6.31.55, not 6.31.55 too. Thank you all for clarifying. 👍
