### ISSUE TITLE
RVX crashes upon startup

### ISSUE THREAD

**Issue by Sam101011** [inotia00/ReVanced_Extended#1873]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 18.45.43

### Bug description

After patching with latest patches(2.209.1), RVX crashes immediately upon startup. Tried with a clean install, same outcome.

https://github.com/inotia00/ReVanced_Extended/assets/90930406/3d48b727-975d-4fa3-84aa-4dc6889d7e41

### Error logs

```shell
FATAL EXCEPTION: main
Process: app.rvx.android.youtube, PID: 28973
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/app.rvx.android.youtube-JrvejLVP5GMdf42wPeoXKA==/base.apk"],nativeLibraryDirectories=[/data/app/app.rvx.android.youtube-JrvejLVP5GMdf42wPeoXKA==/lib/arm64, /system/lib64, /hw_product/lib64, /system/product/lib64]]] couldn't find "libelements.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1668)
	at fvy.<clinit>(PG:3)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at androidx.core.app.CoreComponentFactory.instantiateApplication(PG:1)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1167)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1451)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7554)
	at android.app.ActivityThread.access$2600(ActivityThread.java:260)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

### Additional context

Happy New Year!
:)

### Device Environment

Android 10, EMUI 12

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The error log says that the patched APK is missing the required library file `libelements.so`

You may have had additional modifications since the patch

Do not make any additional modifications to the patched APK

This is not what DEV intended
