### ISSUE TITLE
bug(Reddit): some patches are broken in Reddit v2024.02.0+

### ISSUE THREAD

**Issue by shifoc** [inotia00/ReVanced_Extended#1896]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Reddit v2024.02.0

### Bug description

- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: SM-S908E
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.reddit.frontpage v2024.02.0
Patches version: v2.210.1
Patches added: Disable screenshot popup, Hide ads, Hide navigation buttons, Hide recently visited shelf, Hide toolbar button, Open links directly, Open links externally, Premium icon, Sanitize sharing links, Settings
Patches removed: Hide ads, Hide navigation buttons, Premium icon, Hide recently visited shelf, Disable screenshot popup, Hide toolbar button, Open links directly, Open links externally, Sanitize sharing links, Settings
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 8 patches
Open links directly failed: app.revanced.patcher.patch.PatchException: Failed to resolve ScreenNavigatorFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
	at app.revanced.patches.reddit.misc.openlink.OpenLinksDirectlyPatch.execute(OpenLinksDirectlyPatch.kt:37)
	at app.revanced.patches.reddit.misc.openlink.OpenLinksDirectlyPatch.execute(OpenLinksDirectlyPatch.kt:13)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Open links externally failed: app.revanced.patcher.patch.PatchException: Failed to resolve ScreenNavigatorFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
	at app.revanced.patches.reddit.misc.openlink.OpenLinksExternallyPatch.execute(OpenLinksExternallyPatch.kt:43)
	at app.revanced.patches.reddit.misc.openlink.OpenLinksExternallyPatch.execute(OpenLinksExternallyPatch.kt:16)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
Signing APK
Patched

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.215.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.215.1)

**Comment by shifoc** [comment]
@inotia00 I am getting this error now

![Screenshot_20240119_060454_App Manager.png](https://github.com/inotia00/ReVanced_Extended/assets/32818143/4b36deb0-3993-403e-9704-567d8065d11a)

**Comment by ANi1XO** [comment]
> @inotia00 I am getting this error now
> 
> ![Screenshot_20240119_060454_App Manager.png](https://private-user-images.githubusercontent.com/32818143/297950336-4b36deb0-3993-403e-9704-567d8065d11a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzgwNzYsIm5iZiI6MTcwNTYzNzc3NiwicGF0aCI6Ii8zMjgxODE0My8yOTc5NTAzMzYtNGIzNmRlYjAtMzk5My00MDNlLTk3MDQtNTY3ZDgwNjVkMTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA0MTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNDRkMGRjMzllNWI2NTAwMjBjYTJmOWNhZTMwODNjOTRmZmZiNjY0ZDgwMzMzZmYzMzA1MDFjODNjNzQ2YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zR-CKqNzf3c5H9_0uO2cPXT7PPeJ9tMdSyCCKY3iBbE)

Try uninstalling the old one.

**Comment by inotia00** [comment]
- in the case of `Change package name` patch added to this release, the patch method of RVX Manager and CLI is slightly different. [Additional information](https://github.com/inotia00/ReVanced_Extended/issues/1842#issuecomment-1868299915)

This is specified in the release notes of [revanced-patches-v2.207.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.207.1)

If you have applied the patch through the RVX Manager and include `Change package name` patch, you should remove the already installed Reddit app to install Reddit RVX normally

So if you want to patch through the RVX Manager, I recommend exclude `Change package name` patch

**Comment by shifoc** [comment]
Why would you choose to keep method 1 if method 2 is better and allows to download multiple reddit apps?

**Comment by inotia00** [comment]
It is difficult to elaborate, but it is due to the structural limitations of the RVX Manager.

**Comment by shifoc** [comment]
Got it! So I installed it using revancify and now I am getting this on the original reddit ![Screenshot_20240119_072918_Reddit.png](https://github.com/inotia00/ReVanced_Extended/assets/32818143/8ae2fa04-e406-4c41-a2d0-ac81489a5f42)

**Comment by i486** [comment]
I remember encountering an issue where users couldn't log in if they applied the "change package name" patch on Reddit. This was tested on the March 2024 versions of Reddit, Revancify, and ReX-Advanced. Excluding the patch was the solution for me. I'm curious if using RVX Manager would resolve the issue.

![329196647-41529124-f21b-4e5b-9303-75e49b24e61f](https://github.com/inotia00/ReVanced_Extended/assets/625325/f450a616-b4b4-490e-9d3b-4972018b26ac)
