### ISSUE TITLE
bug(YouTube Music): 4 patches failed on 6.34.51

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1906]
### Type

Error while patching

### Tools used

CLI

### Application

YouTube Music 6.34.51

### Bug description

4 patches failed on 6.34.51: `Enable color match player`, `Enable new player background`, `Enable old style miniplayer` and `Enable zen mode`

### Error logs

```shell
INFO: Loading patches
INFO: Decoding app manifest
INFO: Hide voice search button excluded
INFO: Hide double tap overlay filter excluded
INFO: Enable old player layout excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: Amoled succeeded
INFO: Background play succeeded
INFO: Bitrate default value succeeded
INFO: Certificate spoof succeeded
INFO: Change start page succeeded
INFO: Custom branding icon YouTube Music succeeded
INFO: Custom branding name YouTube Music succeeded
INFO: Custom package name succeeded
INFO: Custom playback speed succeeded
INFO: Disable auto captions succeeded
INFO: Disable overlay filter succeeded
INFO: Enable black navigation bar succeeded
SEVERE: Enable color match player failed:
app.revanced.patcher.patch.PatchException: Failed to resolve PlayerColorFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
        at app.revanced.patches.music.player.colormatchplayer.ColorMatchPlayerPatch.execute(ColorMatchPlayerPatch.kt:150)
        at app.revanced.patches.music.player.colormatchplayer.ColorMatchPlayerPatch.execute(ColorMatchPlayerPatch.kt:25)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:304)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

INFO: Enable compact dialog succeeded
INFO: Enable custom filter succeeded
INFO: Enable debug logging succeeded
INFO: Enable force minimized player succeeded
INFO: Enable landscape mode succeeded
INFO: Enable minimized playback succeeded
SEVERE: Enable new player background failed:
app.revanced.patcher.patch.PatchException: Failed to resolve NewPlayerBackgroundFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
        at app.revanced.patches.music.player.newplayerbackground.NewPlayerBackgroundPatch.execute(NewPlayerBackgroundPatch.kt:36)
        at app.revanced.patches.music.player.newplayerbackground.NewPlayerBackgroundPatch.execute(NewPlayerBackgroundPatch.kt:14)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:304)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

INFO: Enable old style library shelf succeeded
SEVERE: Enable old style miniplayer failed:
app.revanced.patcher.patch.PatchException: Failed to resolve PlayerColorFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
        at app.revanced.patches.music.player.oldstyleminiplayer.OldStyleMiniPlayerPatch.execute(OldStyleMiniPlayerPatch.kt:53)
        at app.revanced.patches.music.player.oldstyleminiplayer.OldStyleMiniPlayerPatch.execute(OldStyleMiniPlayerPatch.kt:18)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:304)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

INFO: Enable opus codec succeeded
INFO: Enable playback speed succeeded
INFO: Enable sleep timer succeeded
SEVERE: Enable zen mode failed:
app.revanced.patcher.patch.PatchException: Failed to resolve PlayerColorFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
        at app.revanced.patches.music.player.zenmode.ZenModePatch.execute(ZenModePatch.kt:63)
        at app.revanced.patches.music.player.zenmode.ZenModePatch.execute(ZenModePatch.kt:19)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:304)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

INFO: Exclusive audio playback succeeded
INFO: Hide account menu succeeded
INFO: Hide action bar component succeeded
INFO: Hide button shelf succeeded
INFO: Hide carousel shelf succeeded
INFO: Hide cast button succeeded
INFO: Hide category bar succeeded
INFO: Hide channel guidelines succeeded
INFO: Hide emoji picker succeeded
INFO: Hide flyout panel succeeded
INFO: Hide general ads succeeded
INFO: Hide get premium succeeded
INFO: Hide handle succeeded
INFO: Hide history button succeeded
INFO: Hide navigation bar component succeeded
INFO: Hide new playlist button succeeded
INFO: Hide playlist card succeeded
INFO: Hide taste builder succeeded
INFO: Hide terms container succeeded
INFO: Hide tooltip content succeeded
INFO: MicroG support succeeded
INFO: Remember playback speed succeeded
INFO: Remember repeat state succeeded
INFO: Remember shuffle state succeeded
INFO: Remember video quality succeeded
INFO: Remove viewer discretion dialog succeeded
INFO: Replace cast button succeeded
INFO: Replace dismiss queue succeeded
INFO: Return YouTube Dislike succeeded
INFO: Sanitize sharing links succeeded
INFO: SponsorBlock succeeded
INFO: Spoof app version succeeded
INFO: Translations succeeded
INFO: Settings succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Compiling modified resources
INFO: Aligning ytm.apk
INFO: Signing ytm.apk
```

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.215.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.215.1)
