### ISSUE TITLE
bug: YT Music - Microg patch fails if using original YTM package name

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1941]
### Type

Error while patching

### Tools used

rvx-builder

### Application

All...even with recommended

### Bug description

If we patch YT music with original rvx package name and also with other app's package name, it patches perfectly. But if we use original YT music patch (com.google.android.apps.youtube.music), patch fails. I want to completely replace YT music with it. Like Reddit.

### Error logs

```shell
[builder] SEVERE: MicroG support failed: app.revanced.patcher.patch.PatchException: 'MicroG support' depends on 'MicroGResourcePatch' that raised an exception: app.revanced.patcher.patch.PatchException: Original package name is not available as package name for MicroG build. at app.revanced.patches.music.utils.microg.MicroGResourcePatch.execute(MicroGResourcePatch.kt:32) at app.revanced.patches.music.utils.microg.MicroGResourcePatch.execute(MicroGResourcePatch.kt:19) at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177) at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156) at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61) at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230) at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:304) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12) at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161) at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt) at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61) at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230) at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:304) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280) at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```

### Solution

...

### Additional context

...

### Device Environment

ANDROID 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
> I want to completely replace YT music with it. Like Reddit.

You can't without root. If you are rooted you can exclude the MicroG Support patch.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/612#issuecomment-1490155183

**Comment by Vipin2003** [comment]
> > I want to completely replace YT music with it. Like Reddit.
> 
> You can't without root. If you are rooted you can exclude the MicroG Support patch.

I think it can be done bcoz in my case, there is a uninstall btn (rather than disable) in YTM. So, I can completely remove it. After that, It should be possible bcoz it was completely detached from system like reddite and other apps.
Like eg - Reddit is not a system app & it have uninstall btn. Bcoz of which rvx provides two options for it - 1 with original and with rvx package name and OG reddit is replaced by RVX reddit. Like that, I want it to be replace it with RVX YTM.
