### ISSUE TITLE
bug(YouTube): Crash when the "Remind me to take a break reminder" should pop up

### ISSUE THREAD

**Issue by cromefire** [inotia00/ReVanced_Extended#2076]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

- Turn on "Remind me to take a break"
- Wait for the specified time
- instead of the pop up going up, the App crashes

### Error logs

```shell
05-26 20:49:16.038  2768  2768 E AndroidRuntime: FATAL EXCEPTION: main
05-26 20:49:16.038  2768  2768 E AndroidRuntime: Process: app.rvx.android.youtube, PID: 2768
05-26 20:49:16.038  2768  2768 E AndroidRuntime: azqw: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at azsd.a(PG:5)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at aztc.c(PG:14)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at aztc.vS(PG:26)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at bajx.run(PG:124)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at azeh.run(PG:27)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at bapu.run(PG:11)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at bapw.run(PG:34)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8501)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at app.revanced.integrations.youtube.patches.player.PlayerPatch.setContentDescription(PlayerPatch.java:84)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at znn.K(PG:77)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at znn.v(PG:10)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at znn.b(PG:543)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at zmy.I(PG:2014)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at zmy.d(PG:33)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at aclx.eV(PG:38)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at zot.b(PG:465)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at ztq.h(PG:260)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at ztq.g(PG:61)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at yaz.run(PG:206)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at xkn.e(PG:50)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at xkn.b(PG:7)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at ztq.c(PG:47)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at ztl.c(PG:14)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at abvz.c(PG:423)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at ges.l(PG:139)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at gcq.a(PG:414)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	at aztc.vS(PG:9)
05-26 20:49:16.038  2768  2768 E AndroidRuntime: 	... 12 more
```

### Additional context

Seems to have been introduced recently

### Device Environment

Android 14, Pixel 7 Pro

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by cromefire** [comment]
Log is there now as well from the stack trace it seems like something that could be easy to fix

**Comment by cromefire** [comment]
Seems to come from the description components patch and disabling that seems to fix the issue.

**Comment by inotia00** [comment]
What are the versions of revanced patches?
