### ISSUE TITLE
bug: issue while patching

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [inotia00/ReVanced_Extended#2084]
### Type

Error while patching

### Tools used

RVX Manager

### Application

Youtube 19.20.34

### Bug description

There is a weird error at compile time

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.3
Model: SM-A125M
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.20.34 
Patches version: v4.8.4
Patches added: Default
Patches removed: Alternative thumbnails, Hide feed components, Hide feed flyout menu, Disable auto audio tracks, Disable auto captions, Hide layout components, Layout switch, Enable gradient loading screen, Navigation bar components, Disable splash animation, Spoof app version, Change start page, Enable tablet mini player, Toolbar components, Custom double tap length, Enable debug logging, Enable external browser, Enable open links directly, Disable QUIC protocol, Sanitize sharing links, Hide action buttons, Hide player buttons, Hide comments component, Player components, Description components, Hide player flyout menu, Change player flyout menu toggles, Fullscreen components, Disable haptic feedback, Overlay buttons, Seekbar components, Shorts components, Shorts outline button, Change shorts repeat state, Disable resuming shorts on startup, Return YouTube Dislike, SponsorBlock
Default patch options changed: Custom branding name YouTube [App name: RVX (inotia00)]

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Remove unused library: false
Use pre-release: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 14 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~feejdsRZPbxBZ1CnWBVcDw==/app.rvx.manager.flutter-McxEJZd6cVqVTTqJN7jmsQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YXNPHU/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1546376640, --version-name, 19.21.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.rvx.manager.flutter/cache/APKTOOL113785743237074298.tmp, -0, arsc, -I, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YXNPHU/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YXNPHU/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YXNPHU/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:487)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hsuHvwTCdC5Nf5dk5fKUQSHxuuY(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~feejdsRZPbxBZ1CnWBVcDw==/app.rvx.manager.flutter-McxEJZd6cVqVTTqJN7jmsQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YXNPHU/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1546376640, --version-name, 19.21.34, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.rvx.manager.flutter/cache/APKTOOL113785743237074298.tmp, -0, arsc, -I, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YXNPHU/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YXNPHU/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-YXNPHU/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
```

### Device Environment

Android 12 One UI 5.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [x] I have written the title and contents in English.

**Comment by inotia00** [comment]
already fixed in [revanced-patches-4.8.5](https://github.com/inotia00/revanced-patches/releases/tag/v4.8.5)
