### ISSUE TITLE
YouTube ReVancred Issues

### ISSUE THREAD

**Issue by AlexanderRom07** [inotia00/ReVanced_Extended#2093]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube 19.20.34

### Bug description

There was a problem when applying patches for YouTube on 19.20.34. It gives an error about a lack of RAM, although about 3/3.5GB is free

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.3
Model: 2201117TG
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.20.34 (Suggested: 19.20.34)
Patches version: v4.8.5
Patches added: Default
Patches removed: Custom branding icon YouTube, Custom branding name YouTube
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Remove unused library: false
Use pre-release: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 49 patches
Compiling patched dex files
Compiled 8 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 8 free bytes and 8B until OOM, target footprint 268435456, growth limit 268435456
 at com.android.tools.smali.dexlib2.dexbacked.DexBuffer.readerAt(Unknown Source:0)
 at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:0)
 at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:0)
 at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(SourceFile:0)
 at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(SourceFile:0)
 at com.android.tools.smali.dexlib2.dexbacked.DexBackedClassDef.getType(Unknown Source:20)
 at com.android.tools.smali.dexlib2.dexbacked.DexBackedField.getDefiningClass(Unknown Source:2)
 at com.android.tools.smali.dexlib2.base.reference.BaseFieldReference.compareTo(SourceFile:0)
 at com.android.tools.smali.dexlib2.base.reference.BaseFieldReference.compareTo(SourceFile:0)
 at com.android.tools.smali.dexlib2.writer.DexWriter$3.compare(SourceFile:0)
 at com.android.tools.smali.dexlib2.writer.DexWriter$3.compare(SourceFile:0)
 at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
 at java.util.TimSort.sort(TimSort.java:234)
 at java.util.Arrays.sort(Arrays.java:1344)
 at java.util.ArrayList.sort(ArrayList.java:1738)
 at java.util.Collections.sort(Collections.java:210)
 at com.android.tools.smali.dexlib2.writer.DexWriter.writeFields(Unknown Source:20)
 at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
 at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
 at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:80)
 at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
 at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
 at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)
```

### Device Environment

Xiaomi Redmi Note 11 6/128
HyperOS
Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by ILoveOpenSourceApplications** [comment]
Clear manager cache. Force stop. Try patching again.

**Comment by inotia00** [comment]
In most situations, https://github.com/inotia00/ReVanced_Extended/issues/2093#issuecomment-2134497314 will resolve the issue.
If this doesn't work for you, try patching again with YouTube v19.16.39.

**Comment by AlexanderRom07** [comment]
None of this helped:
`- Device Info
ReVanced Manager: 1.20.3
Model: 2201117TG
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.20.34)
Patches version: v4.8.5
Patches added: MaterialYou
Patches removed: Custom branding icon YouTube, Custom branding name YouTube
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Remove unused library: false
Use pre-release: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 50 patches
Compiling patched dex files
Compiled 8 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 2545048 free bytes and 2485KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at com.android.tools.smali.dexlib2.dexbacked.DexBuffer.readerAt(Unknown Source:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedMethod.getName(Unknown Source:22)
	at com.android.tools.smali.dexlib2.writer.pool.PoolMethod.getName(Unknown Source:2)
	at com.android.tools.smali.dexlib2.writer.pool.MethodPool.getName(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.pool.MethodPool.getName(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeMethods(Unknown Source:91)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:80)
	at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)`

**Comment by inotia00** [comment]
There is a memory allocation issue on your device
You can follow one of the following:
1. Try patching with another device
2. Use another patch method provided in the [documentations](https://github.com/inotia00/revanced-documentation/wiki)
