### ISSUE TITLE
bug: The application crashes after starting a video for about 1 to 2 minutes.

### ISSUE THREAD

**Issue by phoenixnguyen1249** [inotia00/ReVanced_Extended#2106]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.20.34

### Bug description

The app seems to be incompatible with Vivo devices, it keeps crashing after starting the video after 1-2 minutes.  On Redmi phones, I can still use it normally, I think this is a bug. Hope you can fix this bug 

### Device Environment

Android 13, FunTouch 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
1. The revanced-patches version used for the patch should be provided.
You can get the revanced-patches version from:
```
Settings - ReVanced Extended - Miscellaneous - Patch information - ReVanced Patches
```

2. Crash log should be attached.
Crash log can be obtained through the following command:
https://github.com/inotia00/ReVanced_Extended/issues/2068#issuecomment-2132261292

**Comment by phoenixnguyen1249** [comment]
Help, I cannot get the log. I don't know what to do next, I gave Termux permission but it still doesn't work
```
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.
```
![IMG_1717224344854_1717224426289](https://github.com/inotia00/ReVanced_Extended/assets/138687038/b5f95f0b-60ec-43d3-9f57-d9e6ac86d415)
![IMG_1717224345272_1717224427162](https://github.com/inotia00/ReVanced_Extended/assets/138687038/f0adc1f6-a904-426f-8cc9-acd945fc08d2)
![IMG_1717223469945_1717224428663](https://github.com/inotia00/ReVanced_Extended/assets/138687038/96e3cbd2-7785-407d-bcce-40087bdf0e44)

**Comment by phoenixnguyen1249** [comment]
About patch information:
Revanced Patches: 4.8.6
Revanced Integration: 1.9.4

**Comment by phoenixnguyen1249** [comment]
This is the log: 
```
06-01 17:20:50.606 12429 32306 E Security-LocalReporter: Warning: launching intent with a non-Activity Context requires FLAG_ACTIVITY_NEW_TASK, or the Android Runtime will throw a AndroidRuntimeException. Adding the flag to prevent a crash. This might lead to unexpected behavior with the back button. Please pass in an Activity Context.
06-01 18:14:53.473 21053 21053 E AndroidRuntime: FATAL EXCEPTION: main
06-01 18:14:53.473 21053 21053 E AndroidRuntime: PID: 21053
06-01 18:14:53.473 21053 21053 E AndroidRuntime: java.io.IOException: Address already in use
06-01 18:14:53.473 21053 21053 E AndroidRuntime: 	at android.net.LocalSocketImpl.bindLocal(Native Method)
06-01 18:14:53.473 21053 21053 E AndroidRuntime: 	at android.net.LocalSocketImpl.bind(LocalSocketImpl.java:275)
06-01 18:14:53.473 21053 21053 E AndroidRuntime: 	at android.net.LocalServerSocket.<init>(LocalServerSocket.java:49)
06-01 18:14:53.473 21053 21053 E AndroidRuntime: 	at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:71)
06-01 18:14:53.473 21053 21053 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.start(Server.java:53)
06-01 18:14:53.473 21053 21053 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.main(Server.java:314)
06-01 18:14:53.473 21053 21053 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-01 18:14:53.473 21053 21053 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:389)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: Error reporting crash
06-01 18:14:53.474 21053 21053 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:627)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:372)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:147)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4825)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4822)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:43)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:4813)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$LoggingHandler.uncaughtException(RuntimeInit.java:131)
06-01 18:14:53.474 21053 21053 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2300)
06-01 18:27:13.548 26392 26392 E AndroidRuntime: FATAL EXCEPTION: main
06-01 18:27:13.548 26392 26392 E AndroidRuntime: PID: 26392
06-01 18:27:13.548 26392 26392 E AndroidRuntime: java.io.IOException: Address already in use
06-01 18:27:13.548 26392 26392 E AndroidRuntime: 	at android.net.LocalSocketImpl.bindLocal(Native Method)
06-01 18:27:13.548 26392 26392 E AndroidRuntime: 	at android.net.LocalSocketImpl.bind(LocalSocketImpl.java:275)
06-01 18:27:13.548 26392 26392 E AndroidRuntime: 	at android.net.LocalServerSocket.<init>(LocalServerSocket.java:49)
06-01 18:27:13.548 26392 26392 E AndroidRuntime: 	at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:71)
06-01 18:27:13.548 26392 26392 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.start(Server.java:53)
06-01 18:27:13.548 26392 26392 E AndroidRuntime: 	at com.genymobile.scrcpy.Server.main(Server.java:314)
06-01 18:27:13.548 26392 26392 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-01 18:27:13.548 26392 26392 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:389)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: Error reporting crash
06-01 18:27:13.551 26392 26392 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:627)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:372)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:147)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4825)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4822)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:43)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:4813)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$LoggingHandler.uncaughtException(RuntimeInit.java:131)
06-01 18:27:13.551 26392 26392 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2300)
06-01 18:27:30.415 26443 26443 F app_process: runtime.cc:691]   native: #12 pc 000cbf30  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::startReg+64) (BuildId: 6cf11723a76eec8ef52880f94fda3194)
06-01 18:27:30.415 26443 26443 F app_process: runtime.cc:691]   native: #13 pc 000cbc30  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start+640) (BuildId: 6cf11723a76eec8ef52880f94fda3194)
06-01 18:27:30.415 26443 26443 F app_process: runtime.cc:691]   native: #10 pc 000cbf30  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::startReg+64) (BuildId: 6cf11723a76eec8ef52880f94fda3194)
06-01 18:27:30.415 26443 26443 F app_process: runtime.cc:691]   native: #11 pc 000cbc30  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start+640) (BuildId: 6cf11723a76eec8ef52880f94fda3194)
06-01 18:27:30.806 26459 26459 F DEBUG   :       #08 pc 00000000000cbf30  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::startReg(_JNIEnv*)+64) (BuildId: 6cf11723a76eec8ef52880f94fda3194)
06-01 18:27:30.806 26459 26459 F DEBUG   :       #09 pc 00000000000cbc30  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+640) (BuildId: 6cf11723a76eec8ef52880f94fda3194)
```
[log.txt](https://github.com/user-attachments/files/15521505/log.txt)

**Comment by inotia00** [comment]
I was busy so I just saw the issue
Thanks for providing the logcat, but the logcat doesn't seem to contain any information about RVX

Once again, can you reproduce the crash in RVX first and then get the logcat?

**Comment by phoenixnguyen1249** [comment]
I use another device (not computer), connect debug mode via OTG, then enter the command: "logcat | grep AndroidRunTime > /sdcard/log.txt".  I went back into RVX and watched some videos but it didn't have any errors (I think this is an occasional error).  But then I crashed, and this is what I got after the crash.  I'm not sure if it's correct.

**Comment by phoenixnguyen1249** [comment]
ok i will try it

**Comment by inotia00** [comment]
Sorry... I think I gave you the wrong command.

The correct command is:
```
logcat | grep AndroidRunTime > /storage/emulated/0/logcat.txt
```

To stop logcat output, type CTRL + C or close termux.

**Comment by phoenixnguyen1249** [comment]
It seems that your patch from three days ago has fixed this bug. I mean, the bug was still present in the old patch, but after I updated to the latest version, the bug no longer appeared (meaning the bug has been fixed in the latest update). Anyway, thank you for taking the time to look into this.
