### ISSUE TITLE
bug(YouTube/Visual preferences icons): An error occurred while patching when the Custom branding icon patch's app icon is YouTube

### ISSUE THREAD

**Issue by stainlf** [inotia00/ReVanced_Extended#2181]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

![Screenshot_20240623_190311](https://github.com/inotia00/ReVanced_Extended/assets/169571746/98b860ea-372b-479c-b39d-c2824478a9e9)
YouTube was added to the Custom Branding icon patch's app icon list in v4.9.1-dev.1

![Screenshot_20240623_190406](https://github.com/inotia00/ReVanced_Extended/assets/169571746/6a7559fe-6e5c-4e6e-9380-4989c9a00b6c)
But When Custom branding icon is YouTube and Visual preferences icons patch's RVX settings menu icon is a custom branding icon, an error occurs during the patch. 

Visual preferences icons patch have also been added to anddea's YouTube Music patch, and the same error is expected if this patch is merged into your patch. 

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.4
Model: SM-S928N
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.23.40)
Patches version: v4.9.2-dev.2
Patches added: Custom header for YouTube, Hide Shorts dimming, Hide double tap to like animations, MaterialYou, Visual preferences icons [RVX settings menu icon: custom_branding_icon]
Patches removed: Custom package name, Alternative thumbnails, Enable gradient loading screen, Disable splash animation, Custom branding name for YouTube, Theme, Enable debug logging, Change player flyout menu toggles, Swipe controls
Default patch options changed: Custom Shorts action buttons [Shorts icon style : outline], Custom branding icon for YouTube [App icon: youtube, Change splash icons: false], Translations for YouTube [Translations to add: ko-rKR, String resources to keep: ko], Settings for YouTube [RVX settings menu name: ReVanced Settings], SponsorBlock [Outline icons: true]

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Remove unused library: true
Use pre-release: true
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 48 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~WHwdfYxH72cBGTQQSv7EeA==/app.rva.manager.flutter-Y-6KEtPMGig3iM8Z5gcJWA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rva.manager.flutter/cache/patcher/tmp-APMJOC/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.rva.manager.flutter/cache/APKTOOL7996796765155556230.tmp, -0, arsc, -I, /data/user/0/app.rva.manager.flutter/cache/patcher/tmp-APMJOC/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.rva.manager.flutter/cache/patcher/tmp-APMJOC/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.rva.manager.flutter/cache/patcher/tmp-APMJOC/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:484)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$0x5RQW3TgU-norbj4KLWHG0V2oA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~WHwdfYxH72cBGTQQSv7EeA==/app.rva.manager.flutter-Y-6KEtPMGig3iM8Z5gcJWA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rva.manager.flutter/cache/patcher/tmp-APMJOC/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.rva.manager.flutter/cache/APKTOOL7996796765155556230.tmp, -0, arsc, -I, /data/user/0/app.rva.manager.flutter/cache/patcher/tmp-APMJOC/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.rva.manager.flutter/cache/patcher/tmp-APMJOC/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.rva.manager.flutter/cache/patcher/tmp-APMJOC/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
```

### Solution

Why did you add the YouTube icon to the Custom Branding icon patch's app icon list? I thought it was added to RVX settings menu icon to enable YouTube icon to be set. 

When excluded for the custom branding icon patch, I hope that RVX settings menu icon can be applied as the icon i want, not the default value Revancify Blue. 

Whatever it is, I hope the bug will be fixed in a possible way. Thank you.

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Because it's an icon preset that doesn't support

Just choose one of the patch option selected in the `Custom branding icon for YouTube` patch: `Afn Blue`, `Afn Red`, `MMT`, `Revanify Blue`, `Revanify Red`

**Comment by stainlf** [comment]
Ok I know just choose the patch option with an icon other than YouTube. I just wonder why YouTube was added to the patch option and if RVX settings menu icon can be applied as the icon that is not the default Revanify Blue when custom branding icon patch be excluded. When custom branding icon patch be excluded and the RVX settings menu icon is Custom branding icon, the RVX settings menu icon's default value is Revanify Blue.
