### ISSUE TITLE
bug: Overlay buttons patch failed 

### ISSUE THREAD

**Issue by NMBlanco** [inotia00/ReVanced_Extended#2305]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.16.39

### Bug description

While patching with the latest RVX patches (v4.12.1-dev.1), the "Overlay buttons" patch fails.

### Error logs

```shell
Device Info
RVX Manager: 1.21.1
Model: motorola edge 30 ultra
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.12.1-dev.1
Patches added: Visual preferences icons
Patches removed: Custom Shorts action buttons, Custom branding name for YouTube, Translations for YouTube, Enable debug logging, Swipe controls, Spoof client, GmsCore support
Default patch options changed: Custom branding icon for YouTube [App icon: vanced_black], Custom double tap length [Double-tap to seek values: 3, 4, 10, 15, 20, 30, 60, 120, 180]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Remove unused library: false
Use pre-release: true
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 46 patches
Overlay buttons failed: app.revanced.patcher.patch.PatchException: 'Overlay buttons' depends on 'OverlayButtonsBytecodePatch' that raised an exception:
app.revanced.patcher.patch.PatchException: lateinit property videoEndMethod has not been initialized
at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:242)
at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:91)
at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:282)
at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:23)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:26)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:461)
at app.revanced.manager.flutter.MainActivity.$r8$lambda$7KobHryxqqdI5JS3uiaGATjlYU8(SourceFile:0)
at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda2.run(SourceFile:0)
at java.lang.Thread.run(Thread.java:1012)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property videoEndMethod has not been initialized
at app.revanced.patches.youtube.video.information.VideoInformationPatch.getVideoEndMethod$revanced_patches(VideoInformationPatch.kt:140)
at app.revanced.patches.youtube.player.overlaybuttons.OverlayButtonsBytecodePatch.execute(OverlayButtonsBytecodePatch.kt:98)
at app.revanced.patches.youtube.player.overlaybuttons.OverlayButtonsBytecodePatch.execute(OverlayButtonsBytecodePatch.kt:24)
at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
... 19 more

at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:148)
at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:282)
at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)

at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:23)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:26)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:461)
at app.revanced.manager.flutter.MainActivity.$r8$lambda$7KobHryxqqdI5JS3uiaGATjlYU8(SourceFile:0)
at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda2.run(SourceFile:0)
at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
```

### Device Environment

Android 14, Motorola UI

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
I used the same version of patches on v19.16.39 and it patched fine for me on ReVancify.
