### ISSUE TITLE
bug(YouTube Music/GmsCore support): YT Music crashes when using the `Open GmsCore` setting

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2352]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT Music v7.16.52
Patches v4.13.1-dev.1
ReVanced GmsCore v0.3.1.4.240913 (also occurs on 0.3.1.3.240913)

### Bug description

YT Music crashes when using the `Open GmsCore` option at Settings > ReVanced Extended > Miscellaneous > Open GmsCore.

According to [@s7san007 on Telegram](https://t.me/revanced_extended_chat/352520), this is because only half of the package name is written in settings_headers.xml

![IMG_20240829_162209_013](https://github.com/user-attachments/assets/b270ed9b-a8a3-441a-9e43-870dccca9df5)

### Error logs

```shell
FATAL EXCEPTION: main
Process: com.rvx.android.apps.youtube.music, PID: 23286
android.content.ActivityNotFoundException: Unable to find explicit activity class {app.revanced/org.microg.gms.ui.SettingsActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2249)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
	at android.app.Activity.startActivityForResult(Activity.java:5760)
	at ya.startActivityForResult(PG:4)
	at android.app.Activity.startActivityForResult(Activity.java:5718)
	at ya.startActivityForResult(PG:2)
	at android.app.Activity.startActivity(Activity.java:6216)
	at com.google.android.apps.youtube.music.settings.SettingsCompatActivity.startActivity(PG:8)
	at android.app.Activity.startActivity(Activity.java:6183)
	at com.google.android.apps.youtube.music.settings.SettingsCompatActivity.startActivity(PG:4)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:445)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:445)
	at androidx.preference.Preference.H(PG:39)
	at androidx.preference.Preference.b(PG:1)
	at dsh.onClick(PG:3)
	at android.view.View.performClick(View.java:8047)
	at android.view.View.performClickInternal(View.java:8024)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31890)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Additional context

This issue also occured in a slightly older installation of YT Music (v7.10.51, from when it was a supported version).

Edit: I see now that this issue is very similar to https://github.com/inotia00/ReVanced_Extended/issues/2112, however this is occurring on GmsCore from the ReVanced team.

### Device Environment

Android 14
OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1)
