### ISSUE TITLE
bug: Patching issues with RVX Manager - v4.13.1-dev.2

### ISSUE THREAD

**Issue by DarkSanctuary** [inotia00/ReVanced_Extended#2355]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube 19.16.39

### Bug description

Errors while patching

### Error logs

```shell
- Device Info
RVX Manager: 1.21.1
Model: SM-S928B
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.13.1-dev.2
Patches added: Custom header for YouTube, Force hide player buttons background, Hide Shorts dimming, MaterialYou, Visual preferences icons
Patches removed: Translations for YouTube, Enable debug logging, Spoof streaming data
Default patch options changed: Custom branding icon for YouTube [App icon: youtube], Custom double tap length [Double-tap to seek values: 5], Overlay buttons [Icon type: thin, Change top buttons: true], GmsCore support [Check GmsCore: false]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Remove unused library: true
Use pre-release: true
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 55 patches
GmsCore support failed: app.revanced.patcher.patch.PatchException: 'GmsCore support' depends on 'Spoof client' that raised an exception:
app.revanced.patcher.patch.PatchException: Collection contains no element matching the predicate.
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:242)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:91)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:282)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:23)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:26)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:461)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$7KobHryxqqdI5JS3uiaGATjlYU8(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda2.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at app.revanced.util.BytecodeUtilsKt.updatePatchStatus(BytecodeUtils.kt:883)
	at app.revanced.patches.youtube.utils.fix.client.SpoofClientPatch.execute(SpoofClientPatch.kt:486)
	at app.revanced.patches.youtube.utils.fix.client.SpoofClientPatch.execute(SpoofClientPatch.kt:57)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	... 19 more

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:148)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:282)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:23)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:26)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:461)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$7KobHryxqqdI5JS3uiaGATjlYU8(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda2.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Spoof client failed: app.revanced.patcher.patch.PatchException: 'Spoof client' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:45)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:282)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:23)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:26)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:461)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$7KobHryxqqdI5JS3uiaGATjlYU8(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda2.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Ripping selected native libs
Aligning APK
Signing APK
Patched APK
```

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It seems to be a bug in RVX Manager

Try reinstalling RVX Manager

**Comment by DarkSanctuary** [comment]
> It seems to be a bug in RVX Manager
> 
> Try reinstalling RVX Manager

Ok it fixed it, but I got another issue. RVX Manager says instsllation cancelled.

**Comment by inotia00** [comment]
This is also an old issue with RVX Manager
(app freezing due to lack of memory)

As a temporary workaround, clear memory, force close RVX Manager, relaunch and try patching again

This issue will be fixed when Composed manager is released, until then use temporary workaround

**Comment by DarkSanctuary** [comment]
> This is also an old issue with RVX Manager (app freezing due to lack of memory)
> 
> As a temporary workaround, clear memory, force close RVX Manager, relaunch and try patching again
> 
> This issue will be fixed when Composed manager is released, until then use temporary workaround

Where do I clean memory? And how?

**Comment by DarkSanctuary** [comment]
Tried to patch with revancify, got parsing error when trying to install.

Aaaaaaaaaaargh!

**Comment by DarkSanctuary** [comment]
I cleared my ram and cache, force stopped RVX Manager, but still it wont install.

**Comment by DarkSanctuary** [comment]
I reinstalled termux and tried again, this time it worked.
