### ISSUE TITLE
Youtube Randomly Crashes

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [inotia00/ReVanced_Extended#2421]
### Type

Other

### Tools used

rvx-builder

### Application

Youtube 19.26.42

### Bug description

This issue has started occurring to me from yesterday as suddenly when i tried to ooen the app it opened as usual my videos were autoplayed too but randomly it crashes and from the logs the reasons behind crashes seem different too. 

### Error logs

```shell
Crash log 1
eqs: Unexpected exception thrown by non-Glide code
	at erf.run(PG:256)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:221)
	at android.app.ActivityThread.main(ActivityThread.java:7542)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.NoClassDefFoundError: android.support.rastermill.FrameSequence
	at android.support.rastermill.FrameSequence.decodeByteArray(Unknown Source:0)
	at aihc.a(PG:119)
	at lrw.a(PG:443)
	at bccg.oB(PG:3)
	at bcbe.c(PG:36)
	at jxz.d(PG:608)
	at aiij.b(PG:7)
	at ezj.g(PG:196)
	at erf.run(PG:238)
	... 7 more
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.rvx.android.youtube-6v5mnIwk9mlQtaeDpq3zQw==/base.apk"],nativeLibraryDirectories=[/data/app/com.rvx.android.youtube-6v5mnIwk9mlQtaeDpq3zQw==/lib/arm64, /data/app/com.rvx.android.youtube-6v5mnIwk9mlQtaeDpq3zQw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libframesequence.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at android.support.rastermill.FrameSequence.<clinit>(PG:3)
	at android.support.rastermill.FrameSequence.decodeByteArray(Unknown Source:0)
	at aihc.a(PG:119)
	at lrw.a(PG:443)
	at bccg.oB(PG:3)
	at bcbe.c(PG:36)
	at jxz.d(PG:608)
	at ahkr.a(PG:269)
	at xsd.b(PG:3)
	at alio.b(PG:13)
	at ampk.run(PG:30)
	at qpv.run(PG:3)
	at amjn.run(PG:50)
	at ggt.run(PG:69)
	at ggt.run(PG:207)
	at java.lang.Thread.run(Thread.java:919)
	at qrf.run(PG:64)



Crash Log 2:-
java.lang.NoClassDefFoundError: android.support.rastermill.FrameSequence
	at android.support.rastermill.FrameSequence.decodeByteArray(Unknown Source:0)
	at aihc.a(PG:119)
	at lrw.a(PG:443)
	at bccg.oB(PG:3)
	at bcbe.c(PG:36)
	at jxz.d(PG:608)
	at aiij.b(PG:7)
	at ezj.g(PG:196)
	at ezj.e(PG:415)
	at ezn.g(PG:5)
	at ezj.b(PG:129)
	at eoh.q(PG:20)
	at eoe.ad(PG:81)
	at eoe.r(PG:4)
	at aiim.e(PG:36)
	at aiip.l(PG:9)
	at lze.a(PG:97)
	at bcbf.N(PG:11)
	at bbdf.M(PG:13)
	at bcch.N(PG:10)
	at bbdf.M(PG:13)
	at bcbr.N(PG:9)
	at bbdf.M(PG:13)
	at bcch.N(PG:10)
	at bbdf.M(PG:13)
	at bcch.N(PG:10)
	at bbdf.M(PG:13)
	at bcch.N(PG:10)
	at bbdf.M(PG:13)
	at bbrk.U(PG:9)
	at bbco.T(PG:13)
	at bbsd.U(PG:8)
	at bbco.T(PG:13)
	at bbrx.U(PG:11)
	at bbco.T(PG:13)
	at bbwf.ow(PG:36)
	at bbum.d(PG:81)
	at bbul.ow(PG:44)
	at bbvg.ow(PG:35)
	at bbxj.ow(PG:30)
	at bbwe.oB(PG:25)
	at bbzj.ow(PG:28)
	at bbxj.ow(PG:30)
	at bbvt.ow(PG:15)
	at bbwr.e(PG:47)
	at bbcu.aL(PG:13)
	at bbvu.e(PG:10)
	at bbcu.aL(PG:13)
	at bbxk.e(PG:10)
	at bbcu.aL(PG:13)
	at bbvo.U(PG:9)
	at bbco.T(PG:13)
	at bbwf.ow(PG:36)
	at bcfk.b(PG:22)
	at bbyh.e(PG:42)
	at bbym.f(PG:17)
	at bbym.ow(PG:10)
	at bbuo.ow(PG:3)
	at bcfk.b(PG:22)
	at bbyh.e(PG:42)
	at bbym.f(PG:17)
	at bbym.ow(PG:10)
	at bbtm.e(PG:133)
	at bbtl.oB(PG:8)
	at bbqs.oB(PG:38)
	at bccc.oB(PG:11)
	at bcbd.oB(PG:27)
	at bccg.oB(PG:14)
	at bcbe.c(PG:36)
	at akul.b(PG:25)
	at alio.b(PG:13)
	at ampk.run(PG:30)
	at amor.execute(PG:1)
	at amnp.f(PG:1)
	at amnp.i(PG:95)
	at amnp.set(PG:15)
	at amna.run(PG:120)
	at amor.execute(PG:1)
	at amnp.f(PG:1)
	at amnp.i(PG:95)
	at amnp.set(PG:15)
	at amns.d(PG:1)
	at amnt.run(PG:48)
	at amor.execute(PG:1)
	at amnp.f(PG:1)
	at amnp.i(PG:95)
	at amnp.setFuture(PG:29)
	at amnr.d(PG:3)
	at amnt.run(PG:48)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:221)
	at android.app.ActivityThread.main(ActivityThread.java:7542)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.rvx.android.youtube-6v5mnIwk9mlQtaeDpq3zQw==/base.apk"],nativeLibraryDirectories=[/data/app/com.rvx.android.youtube-6v5mnIwk9mlQtaeDpq3zQw==/lib/arm64, /data/app/com.rvx.android.youtube-6v5mnIwk9mlQtaeDpq3zQw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libframesequence.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at android.support.rastermill.FrameSequence.<clinit>(PG:3)
	at android.support.rastermill.FrameSequence.decodeByteArray(Unknown Source:0)
	at aihc.a(PG:119)
	at lrw.a(PG:443)
	at bccg.oB(PG:3)
	at bcbe.c(PG:36)
	at jxz.d(PG:608)
	at ahkr.a(PG:269)
	at xsd.b(PG:3)
	at alio.b(PG:13)
	at ampk.run(PG:30)
	at qpv.run(PG:3)
	at amjn.run(PG:50)
	at ggt.run(PG:69)
	at ggt.run(PG:207)
	at java.lang.Thread.run(Thread.java:919)
	at qrf.run(PG:64)
```

### Solution

Sorry im new to coding so currently in not such  a state to provide solutions to you.I will definitely grow with time and hope to help you soon if any issue occurs🤠

### Additional context

I use rvx lite who creates his apps using your patches and the version 19.26.42 was patchee by him to try i the experimental cairo theme and ya its a pretty good theme want it to stay. 

Some Experimental Flags which dont affect the way and interfere when i try to reproduce the crash are given below (other than this no experimental flags are enabled) :-
Override Video Download Button
Cairo seekbar
Watch Panel Gestures

P. S extra info:- Its based on
Revanced Patches V 4.13.1
Revanced Integrations V 1.13.1

### Device Environment

MIUI GLOBAL 11 A10 
(ikik its old but works for me) 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube 19.26.42 is not a supported version

The recommended version supported by the patch is YouTube 19.16.39

See [docs](https://github.com/inotia00/revanced-documentation/blob/main/docs/rvx-manager.md)
