### ISSUE TITLE
bug (Reddit) : Patching error in Reddit v2024.46.0

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2483]
### Type

Error while patching

### Tools used

CLI

### Application

Reddit v2024.46.0

### Bug description

Patching error.

### Error logs

```shell
~ $ java -jar cli.jar -a reddit.apk -o Reddit -m integrations.apk --options options.json -b patches.jar
WARNING: Skipping Hide navigation buttons: Incompatible with version 2024.46.0. This patch is only compatible with version com.reddit.frontpage: 2024.25.3
INFO: Merging integrations.apk
INFO: Executing Change version code succeeded
INFO: App name will remain unchanged as it matches the original.
INFO: Executing Custom branding name for Reddit succeeded
INFO: Executing Disable screenshot popup succeeded
INFO: Executing Hide Recently Visited shelf succeeded
INFO: Executing Hide ads succeeded
INFO: Executing Hide recommended communities shelf succeeded
INFO: Executing Open links directly succeeded
INFO: Executing Open links externally succeeded
INFO: Executing Premium icon succeeded
SEVERE: Executing Remove subreddit dialog failed:
app.revanced.patcher.patch.PatchException: Failed to resolve FrequentUpdatesSheetScreenFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:30)
        at app.revanced.util.BytecodeUtilsKt.resultOrThrow(BytecodeUtils.kt:22)
        at app.revanced.patches.reddit.layout.subredditdialog.SubRedditDialogPatch.execute(SubRedditDialogPatch.kt:44)
        at app.revanced.patches.reddit.layout.subredditdialog.SubRedditDialogPatch.execute(SubRedditDialogPatch.kt:25)
        at app.revanced.patcher.Patcher$execute$1.invokeSuspend$executePatch(Patcher.kt:124)
        at app.revanced.patcher.Patcher$execute$1.invokeSuspend(Patcher.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.cli.command.MainCommand.run$lambda$30$run(MainCommand.kt:490)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:403)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

INFO: Executing Sanitize sharing links succeeded
INFO: Executing Settings for Reddit succeeded
INFO: Writing patched apks
INFO: Writing patched dex files
INFO: Wrote base.apk
INFO: Using keystore at /data/data/com.termux/files/home/Reddit/revanced.keystore
INFO: Signing base.apk
INFO: Moving base.apk to /data/data/com.termux/files/home/Reddit/base.apk
INFO: Finished
```

### Solution

If possible, no errors.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro.

Android 12.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
App is patching and working fine if `Remove subreddit dialog` patch is excluded.
