### ISSUE TITLE
bug(YouTube - SponsorBlock): Button initialize failure, buttons do not show on some devices with custom roms

### ISSUE THREAD

**Issue by acidcitrus** [inotia00/ReVanced_Extended#2500]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v19.16.39

### Bug description

Same issue present in Extended as described in https://github.com/ReVanced/revanced-patches/issues/3945

### Error logs

```shell
initialize failure
android.view.InflateException: Binary XML file line #26 in app.revanced.android.youtube:layout/revanced_sb_inline_sponsor_overlay: Binary XML file line #26 in app.revanced.android.youtube:layout/revanced_sb_inline_sponsor_overlay: Error inflating class app.revanced.extension.youtube.sponsorblock.ui.NewSegmentLayout
Caused by: android.view.InflateException: Binary XML file line #26 in app.revanced.android.youtube:layout/revanced_sb_inline_sponsor_overlay: Error inflating class app.revanced.extension.youtube.sponsorblock.ui.NewSegmentLayout
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1014)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1144)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at app.revanced.extension.youtube.sponsorblock.ui.SponsorBlockViewController.initialize(SponsorBlockViewController.java:64)
	at kzd.aa(PG:102)
	at kzd.x(PG:1)
	at knr.<init>(PG:24)
	at fxc.c(PG:5)
	at fxc.a(PG:3040)
	at qsd.a(PG:79)
	at kol.y(PG:198)
	at koi.N(PG:34)
	at cg.im(PG:26)
	at alet.e(PG:242)
	at alet.g(PG:926)
	at de.aA(PG:130)
	at de.aC(PG:83)
	at de.I(PG:98)
	at bc.e(PG:7)
	at knq.b(PG:86)
	at knq.c(PG:1)
	at com.google.android.apps.youtube.app.watchwhile.MainActivity.onPostCreate(PG:42)
	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1458)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3776)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2347)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7968)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
Caused by: java.lang.ClassCastException: android.graphics.drawable.StateListDrawable cannot be cast to android.graphics.drawable.RippleDrawable
	at app.revanced.extension.youtube.sponsorblock.ui.NewSegmentLayout.initializeButton(NewSegmentLayout.java:114)
	at app.revanced.extension.youtube.sponsorblock.ui.NewSegmentLayout.<init>(NewSegmentLayout.java:54)
	at app.revanced.extension.youtube.sponsorblock.ui.NewSegmentLayout.<init>(NewSegmentLayout.java:39)
	at app.revanced.extension.youtube.sponsorblock.ui.NewSegmentLayout.<init>(NewSegmentLayout.java:35)
	... 42 more
```

### Solution

https://github.com/ReVanced/revanced-patches/pull/3946/commits/783aaf6d94e6817cc315e014cd945c1439b14bda

### Additional context

v4.16.1

### Device Environment

DokeOS 4.0 - Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
fixed in [revanced-patches-5.0.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.0.1)
