### ISSUE TITLE
Won't compile in Revancify

### ISSUE THREAD

**Issue by paradowskidm** [inotia00/ReVanced_Extended#2526]
### Type

Error while patching

### Tools used

Revancify

### Application

YouTube 19.16.39

### Bug description

Compilation errors referring to icons

### Error logs

```shell
Root Access: false
Architecture: arm64-v8a
App: YouTube v19.16.39
CLI: ReVanced-cli-v5.0.0.jar
Patches: ReVanced-Extended-patches-v5.0.2.rvp
Arguments: --enable Hide ads --enable Alternative thumbnails --enable Bypass image region restrictions --enable Hide feed components --enable Hide feed flyout menu --enable Disable auto audio tracks --enable Disable auto captions --enable Hide layout components --enable Remove viewer discretion dialog --enable Hook download actions --enable Layout switch --enable Enable gradient loading screen --enable Miniplayer --enable Hook YouTube Music actions --enable Navigation bar components --enable Disable splash animation --enable Spoof app version --enable Change start page --enable Toolbar components --enable Custom Shorts action buttons --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --enable Custom branding icon for YouTube --options=appIcon=revancify_blue --options=changeSplashIcon=true --options=restoreOldSplashAnimation=true --enable Custom branding name for YouTube --options=appName=RVX --enable Custom double tap length --options=doubleTapLengthArrays=3,5,10,15,20,30,60,120,180 --enable Theme --options=darkThemeBackgroundColor=@android:color/black --options=lightThemeBackgroundColor=@android:color/white --enable Translations for YouTube --options=selectedTranslations=ar,bg-rBG,de-rDE,el-rGR,es-rES,fr-rFR,hu-rHU,it-rIT,ja-rJP,ko-rKR,pl-rPL,pt-rBR,ru-rRU,tr-rTR,uk-rUA,vi-rVN,zh-rCN,zh-rTW --options=selectedStringResources=af,am,ar,ar-rXB,as,az,b+es+419,b+sr+Latn,be,bg,bn,bs,ca,cs,da,de,el,en-rAU,en-rCA,en-rGB,en-rIN,en-rXA,en-rXC,es,es-rUS,et,eu,fa,fi,fr,fr-rCA,gl,gu,hi,hr,hu,hy,id,in,is,it,iw,ja,ka,kk,km,kn,ko,ky,lo,lt,lv,mk,ml,mn,mr,ms,my,nb,ne,nl,no,or,pa,pl,pt,pt-rBR,pt-rPT,ro,ru,si,sk,sl,sq,sr,sv,sw,ta,te,th,tl,tr,uk,ur,uz,vi,zh,zh-rCN,zh-rHK,zh-rTW,zu --enable Remove background playback restrictions --enable Enable OPUS codec --enable Enable debug logging --enable Enable external browser --enable Enable open links directly --enable Disable QUIC protocol --enable Change share sheet --enable Sanitize sharing links --enable Watch history --enable Hide action buttons --enable Ambient mode control --enable Hide player buttons --enable Hide comments components --enable Player components --enable Description components --enable Hide player flyout menu --enable Change player flyout menu toggles --enable Fullscreen components --enable Disable haptic feedback --enable Overlay buttons --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=iconType=cairo --options=bottomMargin=2.5dip --options=widerButtonsSpace=false --options=changeTopButtons=false --enable Seekbar components --enable Shorts components --enable Disable resuming Shorts on startup --enable Swipe controls --enable Spoof streaming data --enable GmsCore support --options=gmsCoreVendorGroupId=app.revanced --options=checkGmsCore=true --options=disableGmsServiceBroker=false --options=packageNameYouTube=app.rvx.android.youtube --options=packageNameYouTubeMusic=app.rvx.android.apps.youtube.music --enable Return YouTube Dislike --enable Settings for YouTube --options=insertPosition=@string/about_key --options=settingsLabel=ReVancedExtended --enable SponsorBlock --options=outlineIcon=false --enable Video playback

Logs:

INFO: Loading patches 
INFO: Deleting existing temporary files directory 
INFO: Decoding app manifest 
INFO: "Change version code" disabled 
INFO: "Hide Shorts dimming" disabled 
INFO: "Custom header for YouTube" disabled 
INFO: "Force hide player buttons background" disabled 
INFO: "Hide shortcuts" disabled 
INFO: "MaterialYou" disabled 
INFO: "Visual preferences icons for YouTube" disabled 
INFO: "Return YouTube Username" disabled 
INFO: Setting patch options 
INFO: Deleting existing temporary files directory 
INFO: Decoding resources 
INFO: Initializing lookup maps 
INFO: Executing patches 
INFO: "Alternative thumbnails" succeeded 
INFO: "Ambient mode control" succeeded 
INFO: "Bypass image region restrictions" succeeded 
INFO: "Change player flyout menu toggles" succeeded 
INFO: "Change share sheet" succeeded 
INFO: "Change start page" succeeded 
INFO: "Custom Shorts action buttons" succeeded 
INFO: "Custom branding icon for YouTube" succeeded 
INFO: "Custom branding name for YouTube" succeeded 
INFO: "Custom double tap length" succeeded 
INFO: "Description components" succeeded 
INFO: "Disable QUIC protocol" succeeded 
INFO: "Disable auto audio tracks" succeeded 
INFO: "Disable auto captions" succeeded 
INFO: "Disable haptic feedback" succeeded 
INFO: "Disable resuming Shorts on startup" succeeded 
INFO: "Disable splash animation" succeeded 
INFO: "Enable OPUS codec" succeeded 
INFO: "Enable debug logging" succeeded 
INFO: "Enable external browser" succeeded 
INFO: "Enable gradient loading screen" succeeded 
INFO: "Enable open links directly" succeeded 
INFO: "Fullscreen components" succeeded 
INFO: "GmsCore support" succeeded 
INFO: "Hide action buttons" succeeded 
INFO: "Hide ads" succeeded 
INFO: "Hide comments components" succeeded 
INFO: "Hide feed components" succeeded 
INFO: "Hide feed flyout menu" succeeded 
INFO: "Hide layout components" succeeded 
INFO: "Hide player buttons" succeeded 
INFO: "Hide player flyout menu" succeeded 
INFO: "Hook download actions" succeeded 
INFO: "Layout switch" succeeded 
INFO: "Miniplayer" succeeded 
INFO: "Navigation bar components" succeeded 
INFO: "Overlay buttons" succeeded 
INFO: "Player components" succeeded 
INFO: "Remove background playback restrictions" succeeded 
INFO: "Remove viewer discretion dialog" succeeded 
INFO: "Return YouTube Dislike" succeeded 
INFO: "Sanitize sharing links" succeeded 
INFO: "Seekbar components" succeeded 
INFO: "Shorts components" succeeded 
INFO: "SponsorBlock" succeeded 
INFO: "Spoof app version" succeeded 
INFO: "Spoof streaming data" succeeded 
INFO: "Swipe controls" succeeded 
INFO: "Theme" succeeded 
INFO: "Toolbar components" succeeded 
INFO: "Translations for YouTube" succeeded 
INFO: "Video playback" succeeded 
INFO: "Watch history" succeeded 
INFO: "Hook YouTube Music actions" succeeded 
INFO: "Settings for YouTube" succeeded 
INFO: Compiling modified resources 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/drawable/playlist_repeat_button.xml:11: error: resource drawable/yt_outline_arrow_repeat_1_white_24 (aka app.rvx.android.youtube:drawable/yt_outline_arrow_repeat_1_white_24) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/drawable/playlist_repeat_button.xml:14: error: resource drawable/yt_outline_arrow_repeat_1_white_24 (aka app.rvx.android.youtube:drawable/yt_outline_arrow_repeat_1_white_24) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/drawable/playlist_shuffle_button.xml:5: error: resource drawable/yt_outline_arrow_shuffle_1_white_24 (aka app.rvx.android.youtube:drawable/yt_outline_arrow_shuffle_1_white_24) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/drawable/playlist_shuffle_button.xml:8: error: resource drawable/yt_outline_arrow_shuffle_1_white_24 (aka app.rvx.android.youtube:drawable/yt_outline_arrow_shuffle_1_white_24) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/drawable/playlist_shuffle_button.xml:11: error: resource drawable/yt_outline_arrow_shuffle_1_white_24 (aka app.rvx.android.youtube:drawable/yt_outline_arrow_shuffle_1_white_24) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/drawable/playlist_shuffle_button.xml:14: error: resource drawable/yt_outline_arrow_shuffle_1_white_24 (aka app.rvx.android.youtube:drawable/yt_outline_arrow_shuffle_1_white_24) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/drawable/revanced_mute_volume_button.xml:5: error: resource drawable/revanced_volume_unmuted_button (aka app.rvx.android.youtube:drawable/revanced_volume_unmuted_button) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/drawable/revanced_mute_volume_button.xml:8: error: resource drawable/revanced_volume_muted_button (aka app.rvx.android.youtube:drawable/revanced_volume_muted_button) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/drawable/revanced_repeat_button.xml:5: error: resource drawable/yt_outline_arrow_repeat_1_white_24 (aka app.rvx.android.youtube:drawable/yt_outline_arrow_repeat_1_white_24) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/drawable/revanced_repeat_button.xml:8: error: resource drawable/yt_outline_arrow_repeat_1_white_24 (aka app.rvx.android.youtube:drawable/yt_outline_arrow_repeat_1_white_24) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/drawable/revanced_repeat_button.xml:11: error: resource drawable/yt_outline_arrow_repeat_1_white_24 (aka app.rvx.android.youtube:drawable/yt_outline_arrow_repeat_1_white_24) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/layout/youtube_controls_bottom_ui_container.xml:25: error: resource drawable/revanced_speed_button (aka app.rvx.android.youtube:drawable/revanced_speed_button) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/layout/youtube_controls_bottom_ui_container.xml:26: error: resource drawable/revanced_copy_button (aka app.rvx.android.youtube:drawable/revanced_copy_button) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/layout/youtube_controls_bottom_ui_container.xml:27: error: resource drawable/revanced_copy_timestamp_button (aka app.rvx.android.youtube:drawable/revanced_copy_timestamp_button) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/layout/youtube_controls_bottom_ui_container.xml:29: error: resource drawable/revanced_whitelist_button (aka app.rvx.android.youtube:drawable/revanced_whitelist_button) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/layout/youtube_controls_bottom_ui_container.xml:30: error: resource drawable/revanced_play_all_button (aka app.rvx.android.youtube:drawable/revanced_play_all_button) not found. 
WARNING: /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/res/layout/youtube_controls_bottom_ui_container.xml:32: error: resource drawable/revanced_download_button (aka app.rvx.android.youtube:drawable/revanced_download_button) not found. 
WARNING: error: failed linking file resources. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/data/com.termux/files/usr/tmp/APKTOOL17439672905001818504.tmp, -0, arsc, -I, /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/1.apk, --manifest, /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/AndroidManifest.xml, /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:249)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
	at app.revanced.patcher.patch.ResourcePatchContext.get(ResourcePatchContext.kt:133)
	at app.revanced.patcher.Patcher.get(Patcher.kt:159)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:327)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/data/com.termux/files/usr/tmp/APKTOOL17439672905001818504.tmp, -0, arsc, -I, /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/1.apk, --manifest, /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/AndroidManifest.xml, /data/data/com.termux/files/home/Revancify/data/apps/YouTube/19.16.39-ReVanced-Extended-temporary-files/patcher/apk/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:245)
	... 13 more
```

### Device Environment

Galaxy S24 ultra, Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/2520

Revancify should work with inotia00's patches within the next 24 hrs (so I've been told)

**Comment by nick-77** [comment]
It's fixed now, tried twice before commenting 👍
