### ISSUE TITLE
bug: Patching is broken on newest YouTube beta version

### ISSUE THREAD

**Issue by GeekCornerGH** [inotia00/ReVanced_Extended#255]
### Type

Error while patching

### Application

YouTube v18.06.32 beta

### Bug description

I guess YouTube changed something on their code, which broke many patches

### Steps to reproduce

1. Patch YouTube using 18.06.32 beta apk, and latest patch/integrations
2. See errors

### Relevant log output

```shell
INFOS: Reading dex files
INFOS: Decoding AndroidManifest.xml only, because resources are not needed
INFOS: Merging revanced-extended-integrations.apk
INFOS: Skipping custom-branding-icon-afn-blue: Excluded by default
INFOS: Skipping custom-branding-icon-afn-red: Manually excluded
INFOS: Skipping custom-branding-icon-revancify: Excluded by default
INFOS: Skipping force-premium-heading: Excluded by default
INFOS: Skipping materialyou: Excluded by default
INFOS: Deleting existing resource cache directory
GRAVE: Failed to delete existing resource cache directory
INFOS: Decoding resources
INFOS: client-spoof succeeded
INFOS: custom-branding-name succeeded
INFOS: custom-seekbar-color succeeded
INFOS: custom-video-speed succeeded
GRAVE: default-video-quality failed:
app.revanced.patcher.patch.PatchResultError: 'default-video-quality' depends on 'default-video-quality-bytecode-patch' but the following error was raised: Failed to resolve VideoQualitySetterFingerprint
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
GRAVE: default-video-speed failed:
app.revanced.patcher.patch.PatchResultError: 'default-video-speed' depends on 'default-video-speed-bytecode-patch' but the following error was raised: Failed to resolve VideoSpeedChangedFingerprint
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFOS: disable-haptic-feedback succeeded
INFOS: enable-external-browser succeeded
INFOS: enable-minimized-playback succeeded
INFOS: enable-old-layout succeeded
INFOS: enable-old-quality-layout succeeded
INFOS: enable-open-links-directly succeeded
INFOS: enable-seekbar-tapping succeeded
GRAVE: enable-tablet-miniplayer failed:
app.revanced.patcher.patch.PatchResultError: 'enable-tablet-miniplayer' depends on 'enable-tablet-miniplayer-bytecode-patch' but the following error was raised: Failed to resolve MiniPlayerOverrideFingerprint
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFOS: enable-wide-searchbar succeeded
INFOS: force-vp9-codec succeeded
INFOS: header-switch succeeded
INFOS: hide-auto-captions succeeded
INFOS: hide-auto-player-popup-panels succeeded
INFOS: hide-autoplay-button succeeded
INFOS: hide-button-container succeeded
INFOS: hide-cast-button succeeded
INFOS: hide-channel-watermark succeeded
INFOS: hide-comment-component succeeded
INFOS: hide-create-button succeeded
INFOS: hide-crowdfunding-box succeeded
INFOS: hide-email-address succeeded
INFOS: hide-endscreen-cards succeeded
INFOS: hide-endscreen-overlay succeeded
INFOS: hide-filmstrip-overlay succeeded
INFOS: hide-flyout-panel succeeded
INFOS: hide-fullscreen-panels succeeded
INFOS: hide-general-ads succeeded
INFOS: hide-info-cards succeeded
INFOS: hide-live-chat-button succeeded
INFOS: hide-mix-playlists succeeded
INFOS: hide-next-prev-button succeeded
INFOS: hide-pip-notification succeeded
INFOS: hide-player-captions-button succeeded
INFOS: hide-player-overlay-filter succeeded
INFOS: hide-shorts-button succeeded
INFOS: hide-shorts-component succeeded
INFOS: hide-snackbar succeeded
INFOS: hide-startup-shorts-player succeeded
INFOS: hide-stories succeeded
INFOS: hide-suggested-actions succeeded
INFOS: hide-time-and-seekbar succeeded
INFOS: hide-tooltip-content succeeded
GRAVE: hide-video-ads failed:
app.revanced.patcher.patch.PatchResultError: 'hide-video-ads' depends on 'hide-video-ads-bytecode-patch' but the following error was raised: 'hide-video-ads-bytecode-patch' depends on 'general-video-ads-patch' but the following error was raised: Failed to resolve MainstreamVideoAdsFingerprint
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFOS: layout-switch succeeded
GRAVE: microg-support failed:
app.revanced.patcher.patch.PatchResultError: 'microg-support' depends on 'microg-support-bytecode-patch' but the following error was raised: java.lang.NullPointerException
        at app.revanced.shared.util.microg.MicroGBytecodeHelper.returnEarly(MicroGBytecodeHelper.kt:221)
        at app.revanced.shared.util.microg.MicroGBytecodeHelper.patchBytecode(MicroGBytecodeHelper.kt:104)
        at app.revanced.patches.youtube.misc.microg.bytecode.patch.MicroGBytecodePatch.execute(MicroGBytecodePatch.kt:45)
        at app.revanced.patches.youtube.misc.microg.bytecode.patch.MicroGBytecodePatch.execute(MicroGBytecodePatch.kt:19)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:335)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:308)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFOS: optimize-resource succeeded
INFOS: overlay-buttons succeeded
INFOS: patch-options succeeded
INFOS: remove-player-button-background succeeded
GRAVE: return-youtube-dislike failed:
app.revanced.patcher.patch.PatchResultError: 'return-youtube-dislike' depends on 'return-youtube-dislike-bytecode-patch' but the following error was raised: Failed to resolve LikeFingerprint
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFOS: settings succeeded
INFOS: sponsorblock succeeded
INFOS: swipe-controls succeeded
INFOS: theme succeeded
INFOS: translations succeeded
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Why would you report a bug after installing a version which isn't recommended?

**Comment by cuynu** [comment]
> Why would you report a bug after installing a version which isn't recommended?

Lol

**Comment by GeekCornerGH** [comment]
> Why would you report a bug after installing a version which isn't recommended?

To let inotia aware of the situation?

**Comment by inotia00** [comment]
non recommended version no support

**Comment by ILoveOpenSourceApplications** [comment]
> To let inotia aware of the situation?

Wow, and I suppose why he hasn't bumped the patch support for that version?
