### ISSUE TITLE
bug(YouTube - Shorts components): Patch failing during building with certain patch selection

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2581]
### Type

Error while patching

### Tools used

RVX Manager

### Application

YouTube v19.44.39

### Bug description

During patching the process fails at `Shorts components`. The following is the logs from the manager.

```kotlin
- Device Info
RVX Manager: 1.23.5
Model: SM-S911B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.44.39 (Suggested: 19.44.39)
Patches version: v5.1.1
Patches added: Default
Patches removed: Alternative thumbnails, Bypass image region restrictions, Hide feed flyout menu, Disable auto audio tracks, Remove viewer discretion dialog, Hook download actions, Layout switch, Enable gradient loading screen, Miniplayer, Hook YouTube Music actions, Navigation bar components, Disable splash animation, Spoof app version, Change start page, Toolbar components, Custom Shorts action buttons, Custom branding icon for YouTube, Custom branding name for YouTube, Custom double tap length, Translations for YouTube, Visual preferences icons for YouTube, Enable OPUS codec, Enable debug logging, Disable QUIC protocol, Change share sheet, Watch history, Hide action buttons, Hide player buttons, Change player flyout menu toggles, Disable haptic feedback, Overlay buttons, Swipe controls, Spoof streaming data, Return YouTube Dislike, Settings for YouTube, SponsorBlock
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Remove unused library: true
Use pre-release: false
Patches source: inotia00/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Initializing lookup maps
Executing patches
Applied 19 patches
Shorts components failed: app.revanced.patcher.patch.PatchException: The patch "Shorts components" depends on "BytecodePatch (shortsCustomActionsPatch)", which raised an exception:
app.revanced.patcher.patch.PatchException: com.android.tools.smali.dexlib2.builder.instruction.BuilderInstruction11n cannot be cast to com.android.tools.smali.dexlib2.iface.instruction.ReferenceInstruction
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:90)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:72)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:323)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:101)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:47)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:317)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Oku38Rh6VOg9CiulxEElyw3q4GI(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda0.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.ClassCastException: com.android.tools.smali.dexlib2.builder.instruction.BuilderInstruction11n cannot be cast to com.android.tools.smali.dexlib2.iface.instruction.ReferenceInstruction
	at app.revanced.patches.youtube.shorts.components.ShortsComponentPatchKt.shortsCustomActionsPatch$lambda$16$lambda$15(ShortsComponentPatch.kt:318)
	at app.revanced.patches.youtube.shorts.components.ShortsComponentPatchKt.$r8$lambda$_1kFXTZAyHEM0_da04n367_vgpo(Unknown Source:0)
	at app.revanced.patches.youtube.shorts.components.ShortsComponentPatchKt$$ExternalSyntheticLambda2.invoke(Unknown Source:2)
	at app.revanced.patcher.patch.Patch.execute(SourceFile:71)
	at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(SourceFile:166)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:84)
	... 19 more

	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:75)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:323)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:101)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:47)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:317)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Oku38Rh6VOg9CiulxEElyw3q4GI(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda0.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Compiling modified resources
Ripping selected native libs
Aligning APK
Signing APK
Patched APK
``` 

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by worthlesspieceofshit** [comment]
Clear rvx manager cache and data, shoukd fix this.

This is caused by a change in the options.json file.

**Comment by ILoveOpenSourceApplications** [comment]
I know this because with default selection, there's no failing. 

![Screenshot_20241221_175715_RVX Manager](https://github.com/user-attachments/assets/863617bb-dd30-4998-9661-8bcbd60ac0c1)

**Comment by inotia00** [comment]
reflected in [revanced-patches-5.1.2](https://github.com/inotia00/revanced-patches/releases/tag/v5.1.2)
