### ISSUE TITLE
bug:  YT Crash on start without opening

### ISSUE THREAD

**Issue by adeep** [inotia00/ReVanced_Extended#2615]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube 19.44.39

### Bug description

Youtube crash after patched and first run. Never opens after other run.
Used RVX Manager and choose default patch list and crashed, then disabled all patches but "GMS core"  and still crashed.
-I uninstall-reinstall GMS Core
-Follow dontkillmyapp guide and disabled all app sleeps and optimization

![6001181009418241220](https://github.com/user-attachments/assets/2151d80c-0c36-4c88-9dba-4e08b7969f7c)

### Error logs

```shell
FATAL EXCEPTION: main
Process: app.rvx.android.youtube, PID: 17680
java.lang.NoClassDefFoundError: app.revanced.extension.youtube.patches.general.GeneralPatch
	at app.revanced.extension.youtube.patches.general.GeneralPatch.useTranslucentNavigationStatusBar(GeneralPatch.java:250)
	at bbqj.eV(PG:8)
	at ypr.<init>(PG:161)
	at fyj.b(PG:92)
	at fyj.a(PG:100)
	at bbhn.e(PG:12)
	at bbhn.a(PG:7)
	at fyj.b(PG:93)
	at fyj.a(PG:100)
	at bbhn.e(PG:12)
	at bbhn.a(PG:7)
	at fyj.b(PG:94)
	at fyj.a(PG:100)
	at bbhn.e(PG:12)
	at bbhn.a(PG:7)
	at hdf.f(PG:14)
	at fyj.b(PG:96)
	at fyj.a(PG:100)
	at bbhm.a(PG:5)
	at fyj.m(PG:104)
	at fyj.a(PG:80)
	at bbhn.e(PG:12)
	at bbhn.a(PG:7)
	at ajkl.d(PG:11)
	at fyj.r(PG:3776)
	at fyj.a(PG:55)
	at bbhn.e(PG:12)
	at bbhn.a(PG:7)
	at fyj.f(PG:1439)
	at fyj.a(PG:40)
	at bbhn.e(PG:12)
	at bbhn.a(PG:7)
	at fyj.f(PG:1596)
	at fyj.a(PG:40)
	at bbhn.e(PG:12)
	at bbhn.a(PG:7)
	at bbhm.a(PG:5)
	at fym.l(PG:24)
	at fyl.b(PG:15)
	at fyl.a(PG:2995)
	at bbhn.e(PG:12)
	at bbhn.a(PG:7)
	at ymp.a(PG:15)
	at ymo.a(PG:3)
	at yms.a(PG:3)
	at ymp.a(PG:43)
	at gne.onCreate(PG:61)
	at nrm.onCreate(PG:1)
	at nta.onCreate(PG:131)
	at app.revanced.extension.youtube.swipecontrols.SwipeControlsHostActivity.onCreate(SwipeControlsHostActivity.kt:72)
	at com.google.android.apps.youtube.app.watchwhile.MainActivity.onCreate(PG:25)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.ExceptionInInitializerError
	at app.revanced.extension.youtube.patches.general.GeneralPatch.switchCreateWithNotificationButton(GeneralPatch.java:231)
	at abqx.<init>(PG:48)
	at gaa.i(PG:2946)
	at gaa.a(PG:71)
	at bbhn.e(PG:12)
	at bbhn.a(PG:7)
	at gbt.run(PG:262)
	at ynx.run(PG:20)
	at alui.run(PG:21)
	at qsd.run(PG:3)
	at amwy.run(PG:50)
	at qab.run(PG:333)
	at java.lang.Thread.run(Thread.java:764)
	at qta.run(PG:64)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.content.ContextWrapper.getResources(ContextWrapper.java:91)
	at android.view.ContextThemeWrapper.getResourcesInternal(ContextThemeWrapper.java:127)
	at android.view.ContextThemeWrapper.getResources(ContextThemeWrapper.java:121)
	at fw.getResources(PG:5)
	at app.revanced.extension.shared.utils.Utils.getLocalizedContextAndSetResources(Utils.java:297)
	at app.revanced.extension.shared.utils.Utils.getResources(Utils.java:268)
	at app.revanced.extension.shared.utils.ResourceUtils.getIdentifier(ResourceUtils.java:24)
	at app.revanced.extension.shared.utils.ResourceUtils.getIdentifier(ResourceUtils.java:19)
	at app.revanced.extension.shared.utils.ResourceUtils.getIdIdentifier(ResourceUtils.java:56)
	at app.revanced.extension.youtube.patches.general.GeneralPatch.<clinit>(GeneralPatch.java:388)
	... 14 more
```

### Additional context

After Logcat log I disabled "Navigation Bar Components" but it gives more complex error.
https://katb.in/oqodoqodozi

### Device Environment

Android 9 (Samsung S8)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [ ] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Possibly a duplicate or related to https://github.com/inotia00/ReVanced_Extended/issues/2604
