### ISSUE TITLE
bug: YouTube fails to compile

### ISSUE THREAD

**Issue by johnconner122** [inotia00/ReVanced_Extended#30]
### Type

Error while patching

### Application

YouTube v17.49.37

### Bug description

When I try to patch YouTube, it fails to compile

### Steps to reproduce

`java -jar revanced-cli-2.18.3-all.jar -a YouTube_v17.49.37.apk -c -o YouTubeRevanced.apk -b revanced-patches-2.147.0-xtended.jar -m app-release-unsigned-xtended.apk`

### Relevant log output

```shell
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-hdpi\product_logo_youtube_color_144.png: error: failed reading from input: PNG chunk type 0c9e7af2 is too large: chunk length is 97955069 but chunk starts at byte 8249/18792.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-hdpi\product_logo_youtube_color_144.png: error: file failed to compile.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-hdpi\product_logo_youtube_color_192.png: error: failed reading from input: PNG chunk type 36200c1c is too large: chunk length is 1212305961 but chunk starts at byte 8249/27407.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-hdpi\product_logo_youtube_color_192.png: error: file failed to compile.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-hdpi\product_logo_youtube_color_24.png: error: failed reading from input: PNG chunk type f9e82dff is too large: chunk length is 791811443 but chunk starts at byte 2201/2225.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-hdpi\product_logo_youtube_color_24.png: error: file failed to compile.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-hdpi\product_logo_youtube_color_36.png: error: failed reading from input: PNG chunk type b90bea96 is too large: chunk length is 224050839 but chunk starts at byte 3629/3668.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-hdpi\product_logo_youtube_color_36.png: error: file failed to compile.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-mdpi\product_logo_youtube_color_144.png: error: failed reading from input: PNG chunk type fbee032f is too large: chunk length is 1075314622 but chunk starts at byte 8249/11832.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-mdpi\product_logo_youtube_color_144.png: error: file failed to compile.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-mdpi\product_logo_youtube_color_192.png: error: failed reading from input: PNG chunk type a8dab028 is too large: chunk length is 2768520468 but chunk starts at byte 8249/16529.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-mdpi\product_logo_youtube_color_192.png: error: file failed to compile.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-mdpi\product_logo_youtube_color_24.png: error: failed reading from input: PNG chunk type 9b0c669d is too large: chunk length is 1527301896 but chunk starts at byte 1400/1424.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-mdpi\product_logo_youtube_color_24.png: error: file failed to compile.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-mdpi\product_logo_youtube_color_36.png: error: failed reading from input: PNG chunk type 0599a1d0 is too large: chunk length is 2328475468 but chunk starts at byte 2321/2348.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-mdpi\product_logo_youtube_color_36.png: error: file failed to compile.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-xhdpi\product_logo_youtube_color_144.png: error: failed reading from input: PNG chunk type 020f08ec is too large: chunk length is 2103935449 but chunk starts at byte 19099/19456.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-xhdpi\product_logo_youtube_color_144.png: error: file failed to compile.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-xhdpi\product_logo_youtube_color_192.png: error: failed reading from input: PNG chunk type 05969a6e is too large: chunk length is 1040584770 but chunk starts at byte 29441/29918.
WARNING: D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res\drawable-xhdpi\product_logo_youtube_color_192.png: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Rizwan\AppData\Local\Temp\brut_util_Jar_111801587447870560265417521055808439310.tmp, compile, --dir, D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res, --legacy, -o, D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\build\resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:368)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:622)
        at app.revanced.patcher.Patcher.save(Patcher.kt:235)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:162)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Rizwan\AppData\Local\Temp\brut_util_Jar_111801587447870560265417521055808439310.tmp, compile, --dir, D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\res, --legacy, -o, D:\Softwares\Apps & Softwares\Android\Android Apps\Revanced\revanced-cache\build\resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:364)
        ... 13 more
```

### Device Environment

`Android 8.1`

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
It is an issue that I have never seen before
Would you like to reinstall Java?

**Comment by johnconner122** [comment]
It only occurred when I built `revanced-patches` in `Android Studio`

**Comment by inotia00** [comment]
Damm.. this was my side issue
For some reason, all the png images were broken during the commit to github.

It will be fixed in the next release
