### ISSUE TITLE
Error while patching v17.49.37 clean

### ISSUE THREAD

**Issue by xXRazzRXx** [inotia00/ReVanced_Extended#51]
### Type

Error while patching

### Application

YouTube v17.49.37.
Revancify:
Patches v2.147.0
CLI v2.18.3
Integrations v0.86.0

### Bug description

Error while patching. Data and cash cleared, updates deleted and reinstalled up to date

### Steps to reproduce

Step 1. Launch termux
Step 2. Type "revancify"
Step 3. Select "patch app"
Step 4. Select YouTube 

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Loading resource table... 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Loading resource table from file: revanced-cache/1.apk 
INFO: Merging ./revanced-integrations-v0.86.0.apk 
INFO: Skipping background-play: Excluded by default 
INFO: Skipping black-navbar: Excluded by default 
INFO: Skipping client-spoof-music: Excluded by default 
INFO: Skipping codecs-unlock: Excluded by default 
INFO: Skipping compact-header: Excluded by default 
INFO: Skipping custom-branding-icon-blue: Excluded by default 
INFO: Skipping custom-branding-icon-revancify: Excluded by default 
INFO: Skipping custom-branding-music-red: Excluded by default 
INFO: Skipping custom-branding-music-revancify: Excluded by default 
INFO: Skipping custom-video-speed: Excluded by default 
INFO: Skipping default-video-quality: Excluded by default 
INFO: Skipping disable-haptic-feedback: Excluded by default 
INFO: Skipping enable-external-browser: Excluded by default 
INFO: Skipping enable-hdr-auto-brightness: Excluded by default 
INFO: Skipping enable-minimized-playback: Excluded by default 
INFO: Skipping enable-old-layout: Excluded by default 
INFO: Skipping enable-oldstyle-quality-layout: Excluded by default 
INFO: Skipping enable-open-links-directly: Excluded by default 
INFO: Skipping enable-seekbar-tapping: Excluded by default 
INFO: Skipping enable-tablet-miniplayer: Excluded by default 
INFO: Skipping exclusive-audio-playback: Excluded by default 
INFO: Skipping force-premium-heading: Excluded by default 
INFO: Skipping header-switch: Excluded by default 
INFO: Skipping hide-auto-captions: Excluded by default 
INFO: Skipping hide-auto-player-popup-panels: Excluded by default 
INFO: Skipping hide-channel-watermark: Excluded by default 
INFO: Skipping hide-comment-component: Excluded by default 
INFO: Skipping hide-create-button: Excluded by default 
INFO: Skipping hide-crowdfunding-box: Excluded by default 
INFO: Skipping hide-endscreen-overlay: Excluded by default 
INFO: Skipping hide-filmstrip-overlay: Excluded by default 
INFO: Skipping hide-flyout-panel: Excluded by default 
INFO: Skipping hide-general-ads: Excluded by default 
INFO: Skipping hide-get-premium: Excluded by default 
INFO: Skipping hide-mix-playlists: Excluded by default 
INFO: Skipping hide-music-cast-button: Excluded by default 
INFO: Skipping hide-player-captions-button: Excluded by default 
INFO: Skipping hide-player-overlay-filter: Excluded by default 
INFO: Skipping hide-shorts-component: Excluded by default 
INFO: Skipping hide-startup-shorts-player: Excluded by default 
INFO: Skipping hide-stories: Excluded by default 
INFO: Skipping hide-suggested-actions: Excluded by default 
INFO: Skipping hide-video-ads: Excluded by default 
INFO: Skipping materialyou: Excluded by default 
INFO: Skipping microg-support: Excluded by default 
INFO: Skipping minimized-playback-music: Excluded by default 
INFO: Skipping minimized-player: Excluded by default 
INFO: Skipping miniplayer-color: Excluded by default 
INFO: Skipping music-microg-support: Excluded by default 
INFO: Skipping music-settings: Excluded by default 
INFO: Skipping music-video-ads: Excluded by default 
INFO: Skipping optimize-resource-music: Excluded by default 
INFO: Skipping patch-options: Excluded by default 
INFO: Skipping tablet-mode: Excluded by default 
INFO: Skipping tasteBuilder-remover: Excluded by default 
INFO: Skipping theme: Excluded by default 
INFO: Skipping translations-music: Excluded by default 
INFO: Skipping upgrade-button-remover: Excluded by default 
INFO: Loading resource table... 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Decoding AndroidManifest.xml with resources... 
INFO: Loading resource table from file: revanced-cache/1.apk 
INFO: Regular manifest package... 
INFO: Decoding file-resources... 
INFO: Decoding values */* XMLs... 
INFO: client-spoof succeeded 
INFO: custom-branding-icon-red succeeded 
INFO: custom-branding-name succeeded 
INFO: custom-video-buffer succeeded 
INFO: default-video-speed succeeded 
INFO: enable-wide-searchbar succeeded 
INFO: hide-autoplay-button succeeded 
INFO: hide-button-container succeeded 
INFO: hide-cast-button succeeded 
INFO: hide-email-address succeeded 
INFO: hide-endscreen-cards succeeded 
INFO: hide-fullscreen-buttoncontainer succeeded 
INFO: hide-info-cards succeeded 
INFO: hide-pip-notification succeeded 
INFO: hide-shorts-button succeeded 
INFO: hide-time-and-seekbar succeeded 
INFO: layout-switch succeeded 
INFO: optimize-resource succeeded 
INFO: overlay-buttons succeeded 
INFO: remove-player-button-background succeeded 
INFO: return-youtube-dislike succeeded 
INFO: settings succeeded 
INFO: sponsorblock succeeded 
INFO: swipe-controls succeeded 
INFO: translations succeeded 
INFO: Compiling resources 
WARNING: /data/data/com.termux/files/home/storage/Revancify/revanced-cache/res/xml/revanced_prefs.xml:289: error: resource array/revanced_video_speed_entries (aka com.google.android.youtube:array/revanced_video_speed_entries) not found. 
WARNING: /data/data/com.termux/files/home/storage/Revancify/revanced-cache/res/xml/revanced_prefs.xml:289: error: resource array/revanced_video_speed_entry_values (aka com.google.android.youtube:array/revanced_video_speed_entry_values) not found. 
WARNING: error: failed linking file resources. 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [./binaries/aapt2_arm64, link, -o, /data/data/com.termux/files/home/storage/Revancify/revanced-cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1533275584, --version-name, 17.49.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL16834503693803772275.tmp, -0, arsc, -I, revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/storage/Revancify/revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/storage/Revancify/revanced-cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:622)
	at app.revanced.patcher.Patcher.save(Patcher.kt:235)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:162)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [./binaries/aapt2_arm64, link, -o, /data/data/com.termux/files/home/storage/Revancify/revanced-cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1533275584, --version-name, 17.49.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL16834503693803772275.tmp, -0, arsc, -I, revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/storage/Revancify/revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/storage/Revancify/revanced-cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:483)
	... 13 more
```

### Device Environment

Android 12 SKQ1.21006.001
MIUI Global 13.0.3.0 (SKHRUXM)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
![documentations](https://user-images.githubusercontent.com/108592928/209469392-59be5872-d6ee-4f41-94b0-44cbaebacdea.png)
Before proceeding with the patch, read the [documentations](https://github.com/inotia00/revanced-documentation/wiki/Before-start-(Prerequisites)) 

`patch-options` must be include

**Comment by xXRazzRXx** [comment]
Hello, sorry, but ['patch-options'] is already included in Options File Editor, or I'm just too low iq to understand.

![IMG_20221225_191830](https://user-images.githubusercontent.com/121381729/209471713-85119776-5859-487c-92e6-8172be7767e5.jpg)

**Comment by inotia00** [comment]
![patch-options](https://user-images.githubusercontent.com/108592928/209473723-f81764ab-2728-43e2-8fa1-4f8567fecdfa.png)
nah.. You excluded it

**Comment by inotia00** [comment]
revancify may not fully support this `patch-options`, as it is slightly out of compatibility with my patch.

Patch through other method

**Comment by xXRazzRXx** [comment]
I see, thanks

**Comment by xXRazzRXx** [comment]
All fine now, turns out i needed to reinstall/update revancify, although it still states that patch-options are excluded by default. Maybe this is why i should reapply patches after every phone reboot? Thanks

**Comment by inotia00** [comment]
No problem, glad the issue has been resolved
