### ISSUE TITLE
bug: app keeps crashing

### ISSUE THREAD

**Issue by HiddenDeath** [inotia00/ReVanced_Extended#534]
### Type

Error at runtime

### Application

ReVanced Extended 18.11.35

### Bug description

can't even enter after clean install

### Steps to reproduce

1. open the app

### Relevant log output

```shell
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.rvx.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: android.view.InflateException: Binary XML file line #4 in app.rvx.android.youtube:layout/watch_while_activity_with_drawer: Binary XML file line #2 in app.rvx.android.youtube:layout/next_gen_watch_layout: Error inflating class com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:697)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:63)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:12)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:127)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
Caused by: android.view.InflateException: Binary XML file line #4 in app.rvx.android.youtube:layout/watch_while_activity_with_drawer: Binary XML file line #2 in app.rvx.android.youtube:layout/next_gen_watch_layout: Error inflating class com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout
Caused by: android.view.InflateException: Binary XML file line #2 in app.rvx.android.youtube:layout/next_gen_watch_layout: Error inflating class com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(Unknown Source:201)
	at android.view.LayoutInflater.createViewFromTag(Unknown Source:69)
	at android.view.LayoutInflater.parseInclude(Unknown Source:229)
	at android.view.LayoutInflater.rInflate(Unknown Source:71)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.parseInclude(Unknown Source:300)
	at android.view.LayoutInflater.rInflate(Unknown Source:71)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.parseInclude(Unknown Source:300)
	at android.view.LayoutInflater.rInflate(Unknown Source:71)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.rInflate(Unknown Source:102)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.parseInclude(Unknown Source:300)
	at android.view.LayoutInflater.rInflate(Unknown Source:71)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.inflate(Unknown Source:104)
	at android.view.LayoutInflater.inflate(Unknown Source:29)
	at android.view.LayoutInflater.inflate(Unknown Source:5)
	at mer.m(PG:4)
	at fjo.j(PG:44)
	at fjo.a(PG:38)
	at aspm.a(PG:1)
	at fjo.k(PG:47)
	at fjo.a(PG:37)
	at aspm.a(PG:1)
	at fjo.o(PG:4)
	at fjo.a(PG:33)
	at aspm.a(PG:1)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.o(PG:14)
	at ifz.a(PG:26)
	at qr.onCreate(PG:3)
	at bt.onCreate(PG:1)
	at fud.onCreate(PG:8)
	at mff.onCreate(PG:1)
	at app.revanced.integrations.swipecontrols.SwipeControlsHostActivity.onCreate(SwipeControlsHostActivity.kt:1)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:4)
	at android.app.Activity.performCreate(Unknown Source:119)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:433)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:63)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:12)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:127)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
Caused by: java.lang.VerifyError: Verifier rejected class pdl: emp pdl.d(emt, pwg, pcu, pwq, java.util.List, int, nnu, boolean) failed to verify: emp pdl.d(emt, pwg, pcu, pwq, java.util.List, int, nnu, boolean): [0x8A] register v2 has type Conflict but expected Precise Reference: java.lang.StringBuilder (declaration of 'pdl' appears in /data/app/~~t8BUrv7-i1W_uChui1VWLg==/app.rvx.android.youtube-562ciJxaguVDRtrkmuyk0w==/base.apk!classes6.dex)
	at pda.c(PG:1)
	at fjo.b(PG:3)
	at fjo.a(PG:40)
	at aspt.a(PG:1)
	at aspl.a(PG:2)
	at fjo.b(PG:4)
	at fjo.a(PG:40)
	at aspl.a(PG:2)
	at fjo.c(PG:65)
	at fjo.a(PG:39)
	at aspm.a(PG:1)
	at fjo.c(PG:67)
	at fjo.a(PG:39)
	at aspm.a(PG:1)
	at fjo.j(PG:3)
	at fjo.a(PG:38)
	at aspm.a(PG:1)
	at fjp.xr(PG:1)
	at fjo.n(PG:89)
	at fjo.a(PG:34)
	at aspm.a(PG:1)
	at fmr.k(PG:3)
	at lvx.n(PG:1)
	at lvx.<init>(PG:6)
	at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.<init>(PG:3)
	at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchLayout.<init>(PG:2)
	... 55 more
```

### Device Environment

Miui 13, android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Why do you patch an unsupported version and report an issue?

**Comment by HiddenDeath** [comment]
Maybe because it's on revanced.io site?

**Comment by HiddenDeath** [comment]
and what is the supported version then?

**Comment by inotia00** [comment]
revanced.io is a fake website

Please do not report issues here

Currently the latest supported version is v18.10.37

**Comment by HiddenDeath** [comment]
beuh

**Comment by s23ultra512** [comment]
> revanced.io is a fake website
> 
> Please do not report issues here
> 
> Currently the latest supported version is v18.10.37

What is the best way to download/update the app? I cant find a link and revanced.io is fake.
