### ISSUE TITLE
bug:New ambient patch not patching properly 

### ISSUE THREAD

**Issue by Abhigaruji** [inotia00/ReVanced_Extended#635]
### Type

Error while patching

### Application

V18.12.35

### Bug description

Title

### Steps to reproduce

Patching with new ambient patch

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Loading resource table... 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Loading resource table from file: revanced-cache/1.apk 
INFO: Skipping custom-branding-icon-afn-blue: Excluded by default 
INFO: Skipping custom-branding-icon-afn-red: Excluded by default 
INFO: Skipping custom-branding-icon-revancify: Excluded by default 
INFO: Skipping custom-branding-name: Excluded by default 
INFO: Skipping force-player-button-background: Excluded by default 
INFO: Skipping force-premium-heading: Excluded by default 
INFO: Merging inotia00-integrations-v0.101.3.apk 
INFO: Loading resource table... 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Decoding AndroidManifest.xml with resources... 
INFO: Loading resource table from file: revanced-cache/1.apk 
INFO: Regular manifest package... 
INFO: Decoding file-resources... 
INFO: Decoding values */* XMLs... 
SEVERE: bypass-ambient-mode-restrictions failed: 
app.revanced.patcher.patch.PatchResultError: Failed to resolve PowerSaveModeFingerprint
	at app.revanced.extensions.ExtensionsKt.toErrorResult(Extensions.kt:48)
	at app.revanced.patches.youtube.misc.ambientmode.patch.PowerSaveModePatch.execute(PowerSaveModePatch.kt:53)
	at app.revanced.patches.youtube.misc.ambientmode.patch.PowerSaveModePatch.execute(PowerSaveModePatch.kt:23)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: client-spoof succeeded 
INFO: custom-branding-icon-mmt succeeded 
INFO: custom-seekbar-color succeeded 
INFO: custom-video-speed succeeded 
INFO: default-video-quality succeeded 
INFO: default-video-speed succeeded 
INFO: disable-haptic-feedback succeeded 
INFO: disable-quic-protocol succeeded 
INFO: enable-external-browser succeeded 
INFO: enable-minimized-playback succeeded 
INFO: enable-old-layout succeeded 
INFO: enable-old-quality-layout succeeded 
INFO: enable-open-links-directly succeeded 
INFO: enable-seekbar-tapping succeeded 
INFO: enable-tablet-miniplayer succeeded 
INFO: enable-tablet-navigation-bar succeeded 
INFO: enable-timestamps-speed succeeded 
INFO: enable-wide-searchbar succeeded 
INFO: force-vp9-codec succeeded 
INFO: header-switch succeeded 
INFO: hide-account-menu succeeded 
INFO: hide-auto-captions succeeded 
INFO: hide-auto-player-popup-panels succeeded 
INFO: hide-autoplay-button succeeded 
INFO: hide-autoplay-preview succeeded 
INFO: hide-button-container succeeded 
INFO: hide-captions-button succeeded 
INFO: hide-cast-button succeeded 
INFO: hide-category-bar succeeded 
INFO: hide-channel-avatar-section succeeded 
INFO: hide-channel-watermark succeeded 
INFO: hide-collapse-button succeeded 
INFO: hide-comment-component succeeded 
INFO: hide-create-button succeeded 
INFO: hide-crowdfunding-box succeeded 
INFO: hide-email-address succeeded 
INFO: hide-endscreen-cards succeeded 
INFO: hide-endscreen-overlay succeeded 
INFO: hide-filmstrip-overlay succeeded 
INFO: hide-floating-microphone succeeded 
INFO: hide-flyout-panel succeeded 
INFO: hide-fullscreen-buttoncontainer succeeded 
INFO: hide-fullscreen-panels succeeded 
INFO: hide-general-ads succeeded 
INFO: hide-info-cards succeeded 
INFO: hide-live-chat-button succeeded 
INFO: hide-mix-playlists succeeded 
INFO: hide-music-button succeeded 
INFO: hide-next-prev-button succeeded 
INFO: hide-pip-notification succeeded 
INFO: hide-player-button-background succeeded 
INFO: hide-player-overlay-filter succeeded 
INFO: hide-seekbar succeeded 
INFO: hide-shorts-button succeeded 
INFO: hide-shorts-component succeeded 
INFO: hide-shorts-navbar succeeded 
INFO: hide-snackbar succeeded 
INFO: hide-startup-shorts-player succeeded 
INFO: hide-stories succeeded 
INFO: hide-suggested-actions succeeded 
INFO: hide-time-stamp succeeded 
INFO: hide-tooltip-content succeeded 
INFO: hide-video-ads succeeded 
INFO: layout-switch succeeded 
INFO: lift-vertical-video-restriction succeeded 
INFO: materialyou succeeded 
INFO: microg-support succeeded 
INFO: optimize-resource succeeded 
INFO: overlay-buttons succeeded 
INFO: patch-options succeeded 
INFO: protobuf-spoof succeeded 
INFO: return-youtube-dislike succeeded 
INFO: settings succeeded 
INFO: sponsorblock succeeded 
INFO: swipe-controls succeeded 
INFO: switch-create-notification succeeded 
INFO: theme succeeded 
INFO: translations succeeded 
INFO: Compiling resources 
INFO: Writing modified dex files 
INFO: Aligning YouTube-18-12-35.apk to YouTube-Revanced-18-12-35_aligned.apk 
INFO: Signing YouTube-Revanced-18-12-35_aligned.apk to YouTube-Revanced-18-12-35_signed.apk 
INFO: Found existing keystore: revanced.keystore 
INFO: Copying YouTube-Revanced-18-12-35_signed.apk to YouTube-Revanced-18-12-35.apk 
INFO: Cleaned up cache directory 
INFO: Finished 



Variant: nonRoot
Arch: arm64-v8a
App: YouTube-18-12-35.apk
CLI: inotia00-cli-v2.21.0.jar
Patches: inotia00-patches-v2.168.3.jar
Integrations: inotia00-integrations-v0.101.3.apk
Patches argument: -i bypass-ambient-mode-restrictions
-i client-spoof
-i custom-branding-icon-mmt
-i custom-seekbar-color
-i custom-video-speed
-i default-video-quality
-i default-video-speed
-i disable-haptic-feedback
-i disable-quic-protocol
-i enable-external-browser
-i enable-minimized-playback
-i enable-old-layout
-i enable-old-quality-layout
-i enable-open-links-directly
-i enable-seekbar-tapping
-i enable-tablet-miniplayer
-i enable-tablet-navigation-bar
-i enable-timestamps-speed
-i enable-wide-searchbar
-i force-vp9-codec
-i header-switch
-i hide-account-menu
-i hide-auto-captions
-i hide-auto-player-popup-panels
-i hide-autoplay-button
-i hide-autoplay-preview
-i hide-button-container
-i hide-captions-button
-i hide-cast-button
-i hide-category-bar
-i hide-channel-avatar-section
-i hide-channel-watermark
-i hide-collapse-button
-i hide-comment-component
-i hide-create-button
-i hide-crowdfunding-box
-i hide-email-address
-i hide-endscreen-cards
-i hide-endscreen-overlay
-i hide-filmstrip-overlay
-i hide-floating-microphone
-i hide-flyout-panel
-i hide-fullscreen-buttoncontainer
-i hide-fullscreen-panels
-i hide-general-ads
-i hide-info-cards
-i hide-live-chat-button
-i hide-mix-playlists
-i hide-music-button
-i hide-next-prev-button
-i hide-pip-notification
-i hide-player-button-background
-i hide-player-overlay-filter
-i hide-seekbar
-i hide-shorts-button
-i hide-shorts-component
-i hide-shorts-navbar
-i hide-snackbar
-i hide-startup-shorts-player
-i hide-stories
-i hide-suggested-actions
-i hide-time-stamp
-i hide-tooltip-content
-i hide-video-ads
-i layout-switch
-i lift-vertical-video-restriction
-i materialyou
-i microg-support
-i optimize-resource
-i overlay-buttons
-i patch-options
-i protobuf-spoof
-i return-youtube-dislike
-i settings
-i sponsorblock
-i swipe-controls
-i switch-create-notification
-i theme
-i translations
```

### Additional context

Patched using revancify 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
dammmm I uploaded a test build by mistake

I'll release a hotfix as soon as I get home
