### ISSUE TITLE
bug: custom-video-speed patch getting failed while patching

### ISSUE THREAD

**Issue by chandamanab** [inotia00/ReVanced_Extended#954]
### Type

Error while patching

### Application

YouTube 18.16.39

### Bug description

While patching YouTube 18.16.39 using latest patches the custom video speed patch is giving error.

### Steps to reproduce

Open revancify
Go to select patches and make sure custom video speed is selected
Try to patch YouTube 18.16.39 
Custom video speed patch will give an error

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping custom-branding-icon-afn-blue: Excluded by default 
INFO: Skipping custom-branding-icon-afn-red: Excluded by default 
INFO: Skipping custom-branding-icon-mmt: Excluded by default 
INFO: Skipping custom-branding-icon-revancify-blue: Excluded by default 
INFO: Skipping custom-branding-icon-revancify-red: Excluded by default 
INFO: Skipping custom-branding-name: Excluded by default 
INFO: Skipping disable-landscape-mode: Excluded by default 
INFO: Skipping force-hide-player-button-background: Excluded by default 
INFO: Skipping force-premium-heading: Excluded by default 
INFO: Skipping hide-double-tap-overlay-filter: Excluded by default 
INFO: Skipping materialyou: Excluded by default 
INFO: Skipping translations: Excluded by default 
INFO: Merging inotia00-integrations-v0.107.1.apk 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: bypass-ambient-mode-restrictions succeeded 
INFO: change-homepage succeeded 
INFO: custom-double-tap-length succeeded 
INFO: custom-seekbar-color succeeded 
SEVERE: custom-video-speed failed: 
app.revanced.patcher.patch.PatchResultError: 'custom-video-speed' depends on 'custom-speed-bytecode-patch' but the following error was raised: java.lang.NumberFormatException: empty String
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.base/java.lang.Float.parseFloat(Float.java:476)
	at app.revanced.patches.youtube.video.customspeed.bytecode.patch.CustomVideoSpeedBytecodePatch.execute(CustomVideoSpeedBytecodePatch.kt:43)
	at app.revanced.patches.youtube.video.customspeed.bytecode.patch.CustomVideoSpeedBytecodePatch.execute(CustomVideoSpeedBytecodePatch.kt:27)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)

	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: default-video-quality succeeded 
INFO: default-video-speed succeeded 
INFO: disable-haptic-feedback succeeded 
INFO: disable-quic-protocol succeeded 
INFO: disable-startup-shorts-player succeeded 
INFO: enable-external-browser succeeded 
INFO: enable-minimized-playback succeeded 
INFO: enable-old-quality-layout succeeded 
INFO: enable-open-links-directly succeeded 
INFO: enable-seekbar-tapping succeeded 
INFO: enable-tablet-miniplayer succeeded 
INFO: enable-tablet-navigation-bar succeeded 
INFO: enable-timestamps-speed succeeded 
INFO: enable-wide-searchbar succeeded 
INFO: force-vp9-codec succeeded 
INFO: header-switch succeeded 
INFO: hide-account-menu succeeded 
INFO: hide-auto-captions succeeded 
INFO: hide-auto-player-popup-panels succeeded 
INFO: hide-autoplay-button succeeded 
INFO: hide-autoplay-preview succeeded 
INFO: hide-button-container succeeded 
INFO: hide-captions-button succeeded 
INFO: hide-cast-button succeeded 
INFO: hide-category-bar succeeded 
INFO: hide-channel-avatar-section succeeded 
INFO: hide-channel-watermark succeeded 
INFO: hide-collapse-button succeeded 
INFO: hide-comment-component succeeded 
INFO: hide-crowdfunding-box succeeded 
INFO: hide-email-address succeeded 
INFO: hide-endscreen-cards succeeded 
INFO: hide-endscreen-overlay succeeded 
INFO: hide-filmstrip-overlay succeeded 
INFO: hide-floating-microphone succeeded 
INFO: hide-flyout-panel succeeded 
INFO: hide-fullscreen-panels succeeded 
INFO: hide-general-ads succeeded 
INFO: hide-get-premium succeeded 
INFO: hide-info-cards succeeded 
INFO: hide-live-chat-button succeeded 
INFO: hide-mix-playlists succeeded 
INFO: hide-music-button succeeded 
INFO: hide-navigation-buttons succeeded 
INFO: hide-navigation-label succeeded 
INFO: hide-pip-notification succeeded 
INFO: hide-player-button-background succeeded 
INFO: hide-player-overlay-filter succeeded 
INFO: hide-previous-next-button succeeded 
INFO: hide-quick-actions succeeded 
INFO: hide-search-terms succeeded 
INFO: hide-seekbar succeeded 
INFO: hide-shorts-component succeeded 
INFO: hide-shorts-navbar succeeded 
INFO: hide-snackbar succeeded 
INFO: hide-stories succeeded 
INFO: hide-suggested-actions succeeded 
INFO: hide-time-stamp succeeded 
INFO: hide-tooltip-content succeeded 
INFO: hide-video-ads succeeded 
INFO: layout-switch succeeded 
INFO: microg-support succeeded 
INFO: optimize-resource succeeded 
INFO: overlay-buttons succeeded 
INFO: patch-options succeeded 
INFO: protobuf-spoof succeeded 
INFO: return-youtube-dislike succeeded 
INFO: sponsorblock succeeded 
INFO: spoof-app-version succeeded 
INFO: swipe-controls succeeded 
INFO: theme succeeded 
INFO: Compiling resources 
INFO: Writing modified dex files 
INFO: Aligning YouTube-18-16-39.apk to YouTube-Revanced-18-16-39_aligned.apk 
INFO: Signing YouTube-Revanced-18-16-39_aligned.apk to YouTube-Revanced-18-16-39_signed.apk 
INFO: Found existing keystore: revanced.keystore 
INFO: Copying YouTube-Revanced-18-16-39_signed.apk to YouTube-Revanced-18-16-39.apk 
INFO: Cleaned up cache directory 
INFO: Finished 



Variant: nonRoot
Arch: arm64-v8a
App: YouTube-18-16-39.apk
CLI: inotia00-cli-v2.21.1.jar
Patches: inotia00-patches-v2.173.1.jar
Integrations: inotia00-integrations-v0.107.1.apk
Patches argument: -i bypass-ambient-mode-restrictions
-i change-homepage
-i custom-double-tap-length
-i custom-seekbar-color
-i custom-video-speed
-i default-video-quality
-i default-video-speed
-i disable-haptic-feedback
-i disable-quic-protocol
-i disable-startup-shorts-player
-i enable-external-browser
-i enable-minimized-playback
-i enable-old-quality-layout
-i enable-open-links-directly
-i enable-seekbar-tapping
-i enable-tablet-miniplayer
-i enable-tablet-navigation-bar
-i enable-timestamps-speed
-i enable-wide-searchbar
-i force-vp9-codec
-i header-switch
-i hide-account-menu
-i hide-auto-captions
-i hide-auto-player-popup-panels
-i hide-autoplay-button
-i hide-autoplay-preview
-i hide-button-container
-i hide-captions-button
-i hide-cast-button
-i hide-category-bar
-i hide-channel-avatar-section
-i hide-channel-watermark
-i hide-collapse-button
-i hide-comment-component
-i hide-crowdfunding-box
-i hide-email-address
-i hide-endscreen-cards
-i hide-endscreen-overlay
-i hide-filmstrip-overlay
-i hide-floating-microphone
-i hide-flyout-panel
-i hide-fullscreen-panels
-i hide-general-ads
-i hide-get-premium
-i hide-info-cards
-i hide-live-chat-button
-i hide-mix-playlists
-i hide-music-button
-i hide-navigation-buttons
-i hide-navigation-label
-i hide-pip-notification
-i hide-player-button-background
-i hide-player-overlay-filter
-i hide-previous-next-button
-i hide-quick-actions
-i hide-search-terms
-i hide-seekbar
-i hide-shorts-component
-i hide-shorts-navbar
-i hide-snackbar
-i hide-stories
-i hide-suggested-actions
-i hide-time-stamp
-i hide-tooltip-content
-i hide-video-ads
-i layout-switch
-i microg-support
-i optimize-resource
-i overlay-buttons
-i patch-options
-i protobuf-spoof
-i return-youtube-dislike
-i sponsorblock
-i spoof-app-version
-i swipe-controls
-i theme
```

### Device Environment

Android 13, Realme UI 4.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
What patch method did you use?

**Comment by Metallifani666** [comment]
You are getting this error because you didnt delete `Options.toml` file like patch notes asked you to do. Remove that file or reinstall your patching app and you are good to go after it.

**Comment by inotia00** [comment]
Thanks for replying on my behalf
