### ISSUE TITLE
Due to this patch, ReVanced Manager is giving error while compiling ReVanced Music.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#963]
### Type

Error while patching

### Application

YouTube Music v5.55.53

### Bug description

Due to this newly released patch called "Custom Branding Music Name", the manager is giving error while compiling ReVanced Music

### Steps to reproduce

Just select "Custom Branding Music Name" in ReVanced Manger and try to patch YT Music apk.

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied amoled
Applied background-play
Applied bitrate-default-value
Applied custom-branding-music-name
Applied disable-auto-captions
Applied enable-black-navbar
Applied enable-color-match-player
Applied enable-force-minimized-player
Applied enable-force-shuffle
Applied enable-opus-codec
Applied exclusive-audio-playback
Applied hide-button-shelf
Applied hide-carousel-shelf
Applied hide-category-bar
Applied hide-get-premium
Applied hide-music-ads
Applied hide-music-cast-button
Applied hide-new-playlist
Applied hide-playlist-card
Applied hide-taste-builder
Applied hide-upgrade-button
Applied minimized-playback-music
Applied music-microg-support
Applied optimize-resource-music
Applied patch-options
Applied remember-video-quality
Applied share-button-hook
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Os8MNrpluRv412SKirECmA==/app.revanced.manager.flutter-NzwsFJq3Mq1TOeUo4WNMkQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JJNMTK/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JJNMTK/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:365)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:126)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:212)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$kxvfcFiIKARIH6oxYjk9gWWxjp0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:22)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Os8MNrpluRv412SKirECmA==/app.revanced.manager.flutter-NzwsFJq3Mq1TOeUo4WNMkQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JJNMTK/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-JJNMTK/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:361)
	... 6 more
```

### Device Environment

Realme 7 Pro, running on Realme UI 3.0 (Android 12).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This issue only occurs in ReVanced Manager
Since, I'm not a maintainer of ReVanced Manager, so I cannot provide a valid fix for the issue

Instead, I provide a method to apply the patch in the [documentation](https://github.com/inotia00/revanced-documentation/wiki), so please proceed with the patch through a method other than ReVanced Manager

The method I recommend is [Revancify](https://github.com/inotia00/revanced-documentation/wiki/Method-4.-Using-Revancify-(Android---termux))
